name = "cinacoin-auth"
compatibility_date = "2024-12-01"
main = "src/index.ts"

[vars]
JWT_SECRET = "b1Kg7W1Ui6KFWv0xxtpjsLQlCrxw8j7Nd8Bj29NtGFc="
JWT_REFRESH_SECRET = "OFt/v5pHT6ugrOUf/ftd8WwkGeZ4cfumqKrBhh6HuW8="

[[d1_databases]]
binding = "DB"
database_name = "cinacoin-auth-db"
database_id = "7da0bdfd-cbdd-4bde-a4f2-dd410b4970e0"

[[routes]]
pattern = "auth.cinacoin.com/*"
zone_name = "cinacoin.com"
