name = "cinacoin-auth"
compatibility_date = "2024-12-01"
main = "src/index.ts"

[vars]
JWT_SECRET = "cinacoin-auth-jwt-secret-2026"
JWT_REFRESH_SECRET = "cinacoin-auth-refresh-secret-2026"

[[d1_databases]]
binding = "DB"
database_name = "cinacoin-auth-db"
database_id = "7da0bdfd-cbdd-4bde-a4f2-dd410b4970e0"
