import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  guideSidebar: [
    { type: 'doc', id: 'index', label: 'Home' },
  ],
  apiSidebar: [
    { type: 'autogenerated', dirName: 'api' },
  ],
};
export default sidebars;
