import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  guideSidebar: [{ type: 'category', label: 'Getting Started', link: { type: 'doc', id: 'guide/index' }, items: ['guide/quick-start','guide/installation','guide/configuration','guide/migrate-from-reown','guide/troubleshooting'] }],
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
  frameworkSidebar: [{ type: 'autogenerated', dirName: 'framework' }],
};
export default sidebars;
