{{- if eq .Release.Namespace "default" -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace | default "onchainux" }}
  labels:
    name: {{ .Release.Namespace | default "onchainux" }}
    managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: onchainux
{{- end }}
