/**
 * @cinacoin/wallet-registry — Wallet Registry Data
 *
 * 100+ wallet entries with standardized metadata.
 * Sources: WalletConnect Registry, EIP-6963, official docs.
 */

import type { WalletRegistryEntry } from "./types.js";

/** The authoritative wallet registry. */
export const WALLET_REGISTRY: ReadonlyArray<WalletRegistryEntry> = [
  // ═══════════════════════════════════════════════════════════
  // EVM — Tier 1 (Most Popular)
  // ═══════════════════════════════════════════════════════════
  {
    id: "metamask",
    name: "MetaMask",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/metamask",
    homepage: "https://metamask.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:56", "eip155:8453", "eip155:43114"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "metamask://",
    universalLink: "https://metamask.app.link",
    appStoreUrl: "https://apps.apple.com/app/metamask/id1438668043",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.metamask",
    extensionUrl: "https://chromewebstore.google.com/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "io.metamask",
    openSource: true,
    walletType: "hot",
    popularity: 99,
    description: "The most popular Ethereum wallet, available as a browser extension and mobile app.",
    developer: "ConsenSys",
    yearFounded: 2016,
    social: { twitter: "https://twitter.com/MetaMask", github: "https://github.com/MetaMask" },
  },
  {
    id: "rainbow",
    name: "Rainbow",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/rainbow",
    homepage: "https://rainbow.me",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:8453"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "rainbow://",
    universalLink: "https://rnbwapp.com",
    appStoreUrl: "https://apps.apple.com/app/rainbow-ethereum-wallet/id1457119021",
    playStoreUrl: "https://play.google.com/store/apps/details?id=me.rainbow",
    extensionUrl: "https://chromewebstore.google.com/detail/rainbow/opfgelmcmbiajamepnmloijbpoleiama",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "me.rainbow",
    openSource: true,
    walletType: "hot",
    popularity: 82,
    description: "A fun, friendly Ethereum wallet focused on DeFi and NFTs.",
    developer: "Rainbow",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/rainbowdotme", github: "https://github.com/rainbow-me" },
  },
  {
    id: "coinbase-wallet",
    name: "Coinbase Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/coinbase",
    homepage: "https://www.coinbase.com/wallet",
    supportedChainFamilies: ["evm", "solana"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:8453", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "cbwallet://",
    universalLink: "https://go.cb-w.com",
    appStoreUrl: "https://apps.apple.com/app/coinbase-wallet/id1278383455",
    playStoreUrl: "https://play.google.com/store/apps/details?id=org.toshi",
    extensionUrl: "https://chromewebstore.google.com/detail/coinbase-wallet/hnfanknocfeofbddgcijnmhnfnkdnaad",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "com.coinbase.wallet",
    openSource: false,
    walletType: "hot",
    popularity: 88,
    description: "Self-custody wallet from Coinbase with multi-chain support.",
    developer: "Coinbase",
    yearFounded: 2017,
    social: { twitter: "https://twitter.com/CoinbaseWallet" },
  },
  {
    id: "trust-wallet",
    name: "Trust Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/trust",
    homepage: "https://trustwallet.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "cosmos", "aptos", "sui", "ton", "hedera", "near", "starknet", "xrpl"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137", "eip155:43114", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["mobile", "browser_extension"],
    deepLink: "trust://",
    universalLink: "https://link.trustwallet.com",
    appStoreUrl: "https://apps.apple.com/app/trust-crypto-bitcoin-wallet/id1288339409",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.wallet.crypto.trustapp",
    extensionUrl: "https://chromewebstore.google.com/detail/trust-wallet/egjidjbpglichdcondbcbdnbbppckpln",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "com.trustwallet.app",
    openSource: true,
    walletType: "hot",
    popularity: 91,
    description: "Multi-chain crypto wallet supporting 65+ chains. Official Binance wallet.",
    developer: "Binance",
    yearFounded: 2017,
    social: { twitter: "https://twitter.com/TrustWallet", github: "https://github.com/trustwallet" },
  },
  {
    id: "zerion",
    name: "Zerion",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/zerion",
    homepage: "https://zerion.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:8453"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "zerion://",
    universalLink: "https://app.zerion.io",
    appStoreUrl: "https://apps.apple.com/app/zerion/id1456732164",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.zerion.android",
    extensionUrl: "https://chromewebstore.google.com/detail/zerion/klghhnkeealcohjajnjjcgbogebmnpma",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "io.zerion.wallet",
    openSource: true,
    walletType: "hot",
    popularity: 72,
    description: "Smart wallet with built-in DeFi portfolio management and swaps.",
    developer: "Zerion",
    yearFounded: 2016,
    social: { twitter: "https://twitter.com/zerion_io", github: "https://github.com/zeriontech" },
  },
  {
    id: "rabby",
    name: "Rabby Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/rabby",
    homepage: "https://rabby.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:56", "eip155:8453", "eip155:43114"],
    platforms: ["browser_extension", "desktop"],
    deepLink: "rabby://",
    universalLink: "https://rabby.io",
    appStoreUrl: "https://apps.apple.com/app/rabby-wallet/id1628947930",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.debank.rabby",
    extensionUrl: "https://chromewebstore.google.com/detail/rabby-wallet/acmacodkjbdgmoleebolmdjonilkdbch",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "io.rabby",
    openSource: true,
    walletType: "hot",
    popularity: 70,
    description: "DeFi-focused wallet with superior security and multi-chain support. By DeBank.",
    developer: "DeBank",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/Rabby_io", github: "https://github.com/RabbyHub" },
  },
  {
    id: "phantom",
    name: "Phantom",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/phantom",
    homepage: "https://phantom.app",
    supportedChainFamilies: ["solana", "evm", "bitcoin"],
    supportedChains: ["solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", "eip155:1", "eip155:137", "eip155:8453", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "phantom://",
    universalLink: "https://phantom.app",
    appStoreUrl: "https://apps.apple.com/app/phantom-crypto-wallet/id1598432977",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.phantom.app",
    extensionUrl: "https://chromewebstore.google.com/detail/phantom/bfnaelmomeimhlpmgjnjophhpkkoljpa",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "app.phantom",
    openSource: false,
    walletType: "hot",
    popularity: 90,
    description: "The leading Solana wallet, now multi-chain with Ethereum and Bitcoin support.",
    developer: "Phantom",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/phantom", github: "https://github.com/phantom" },
  },
  {
    id: "ledger",
    name: "Ledger Live",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/ledger",
    homepage: "https://www.ledger.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "polkadot", "cosmos", "near", "hedera", "algorand", "stellar", "cardano", "tron", "tezos", "elrond", "flow", "starknet"],
    platforms: ["mobile", "desktop", "hardware"],
    deepLink: "ledgerlive://",
    universalLink: "https://ledgerlive.onelink.me",
    appStoreUrl: "https://apps.apple.com/app/ledger-live/id1361671700",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.ledger.live",
    supportsWalletConnectV2: true,
    supportsEIP6963: false,
    rdns: "com.ledger.live",
    walletType: "cold",
    popularity: 85,
    description: "Hardware wallet companion app supporting 5500+ cryptocurrencies.",
    developer: "Ledger",
    yearFounded: 2014,
    social: { twitter: "https://twitter.com/Ledger", github: "https://github.com/LedgerHQ" },
  },
  {
    id: "trezor",
    name: "Trezor Suite",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/trezor",
    homepage: "https://trezor.io",
    supportedChainFamilies: ["evm", "bitcoin", "cardano", "stellar", "tezos"],
    platforms: ["desktop", "web", "hardware"],
    supportsWalletConnectV2: false,
    openSource: true,
    walletType: "cold",
    popularity: 78,
    description: "Hardware wallet with desktop and web interface. Pioneer of hardware wallets.",
    developer: "SatoshiLabs",
    yearFounded: 2013,
    social: { twitter: "https://twitter.com/Trezor", github: "https://github.com/trezor" },
  },
  {
    id: "uniswap-wallet",
    name: "Uniswap Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/uniswap",
    homepage: "https://wallet.uniswap.org",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:8453"],
    platforms: ["mobile"],
    deepLink: "uniswap://",
    universalLink: "https://wallet.uniswap.org",
    appStoreUrl: "https://apps.apple.com/app/uniswap-wallet/id6443944476",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.uniswap.mobile",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    supportsAccountAbstraction: true,
    popularity: 65,
    description: "Self-custody mobile wallet by Uniswap with built-in swap and limit orders.",
    developer: "Uniswap",
    yearFounded: 2023,
    social: { twitter: "https://twitter.com/Uniswap", github: "https://github.com/Uniswap" },
  },
  {
    id: "okx-wallet",
    name: "OKX Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/okx",
    homepage: "https://www.okx.com/web3",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "cosmos", "aptos", "sui", "ton", "starknet"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "okex://",
    universalLink: "https://www.okx.com",
    appStoreUrl: "https://apps.apple.com/app/okx/id1484717480",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.okinc.okex",
    extensionUrl: "https://chromewebstore.google.com/detail/okx-wallet/mcohilncbfahbmgdjkbpemcciiolgcge",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "com.okex",
    walletType: "hot",
    popularity: 75,
    description: "Multi-chain Web3 wallet from OKX exchange.",
    developer: "OKX",
    yearFounded: 2017,
    social: { twitter: "https://twitter.com/okx" },
  },
  {
    id: "imtoken",
    name: "imToken",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/imtoken",
    homepage: "https://token.im",
    supportedChainFamilies: ["evm", "bitcoin", "cosmos"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["mobile"],
    deepLink: "imtokenv2://",
    universalLink: "https://token.im",
    appStoreUrl: "https://apps.apple.com/app/imtoken/id1594723776",
    playStoreUrl: "https://play.google.com/store/apps/details?id=im.token.app",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 68,
    description: "One of the earliest Ethereum mobile wallets, popular in Asia.",
    developer: "imToken",
    yearFounded: 2016,
    social: { twitter: "https://twitter.com/imTokenOfficial" },
  },
  {
    id: "tokenpocket",
    name: "TokenPocket",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tokenpocket",
    homepage: "https://www.tokenpocket.pro",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "cosmos", "tron", "aptos", "near"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137", "eip155:43114"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "tpoutside://",
    universalLink: "https://www.tokenpocket.pro",
    appStoreUrl: "https://apps.apple.com/app/tokenpocket/id1436002486",
    playStoreUrl: "https://play.google.com/store/apps/details?id=vip.mytokenpocket",
    extensionUrl: "https://chromewebstore.google.com/detail/tokenpocket/mfgccjchihfkkindfppnaooecgfnefff",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 66,
    description: "Multi-chain wallet supporting 20+ public blockchains.",
    developer: "TokenPocket",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/TokenPocket_TP" },
  },
  {
    id: "safepal",
    name: "SafePal",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/safepal",
    homepage: "https://www.safepal.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "tron"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137"],
    platforms: ["browser_extension", "mobile", "hardware"],
    deepLink: "safepal://",
    universalLink: "https://www.safepal.com",
    appStoreUrl: "https://apps.apple.com/app/safepal/id1541662925",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.safepal.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/safepal/amkmjjmmflddogmhpjlojimipdpfnfji",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 55,
    description: "Hardware and software wallet backed by Binance Labs.",
    developer: "SafePal",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/SafePalWallet" },
  },
  {
    id: "bitget-wallet",
    name: "Bitget Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/bitget",
    homepage: "https://web3.bitget.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "tron", "aptos", "sui", "near", "ton"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137", "eip155:43114"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "bitkeep://",
    universalLink: "https://web3.bitget.com",
    appStoreUrl: "https://apps.apple.com/app/bitget-wallet/id1395301115",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.bitkeep.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/bitget-wallet/jiidiaatihmmhchjgbamgpeklnpdistg",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "com.bitget.wallet",
    walletType: "hot",
    popularity: 60,
    description: "Multi-chain Web3 wallet by Bitget (formerly BitKeep).",
    developer: "Bitget",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/BitgetWallet" },
  },
  {
    id: "exodus",
    name: "Exodus",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/exodus",
    homepage: "https://www.exodus.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "cardano", "stellar", "algorand", "tron", "hedera", "near", "cosmos", "aptos", "ton"],
    supportedChains: ["eip155:1", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["desktop", "mobile"],
    deepLink: "exodus://",
    universalLink: "https://www.exodus.com",
    appStoreUrl: "https://apps.apple.com/app/exodus-crypto-wallet/id1277214541",
    playStoreUrl: "https://play.google.com/store/apps/details?id=exodusmovement.exodus",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 63,
    description: "Beautiful multi-crypto wallet with built-in exchange. Desktop-first design.",
    developer: "Exodus Movement",
    yearFounded: 2015,
    social: { twitter: "https://twitter.com/ExodusWallet" },
  },
  {
    id: "solflare",
    name: "Solflare",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/solflare",
    homepage: "https://solflare.com",
    supportedChainFamilies: ["solana"],
    supportedChains: ["solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "solflare://",
    universalLink: "https://solflare.com",
    appStoreUrl: "https://apps.apple.com/app/solflare-wallet/id1580908064",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.solflare.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/solflare-wallet/bhhhlbepdkbapadjdnnojkbgioiodbic",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 58,
    description: "The first Solana wallet with full staking and DeFi integration.",
    developer: "Solflare",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/solflare_wallet", github: "https://github.com/solflare-wallet" },
  },
  {
    id: "backpack",
    name: "Backpack",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/backpack",
    homepage: "https://backpack.app",
    supportedChainFamilies: ["solana", "evm"],
    supportedChains: ["solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", "eip155:1"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "backpack://",
    universalLink: "https://backpack.app",
    appStoreUrl: "https://apps.apple.com/app/backpack/id6445964121",
    playStoreUrl: "https://play.google.com/store/apps/details?id=app.backpack.mobile",
    extensionUrl: "https://chromewebstore.google.com/detail/backpack/aflkmfhebedbjioipglgcbcmnbpgliof",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "app.backpack",
    openSource: true,
    walletType: "hot",
    popularity: 54,
    description: "Crypto wallet and xNFT browser by the founders of Magic Eden.",
    developer: "Coral / Magic Eden",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/Backpack", github: "https://github.com/coral-xyz" },
  },
  {
    id: "walletconnect",
    name: "WalletConnect",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/walletconnect",
    homepage: "https://walletconnect.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161"],
    platforms: ["mobile"],
    deepLink: "wc://",
    universalLink: "https://walletconnect.com",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 50,
    description: "Reference wallet implementation of the WalletConnect protocol.",
    developer: "WalletConnect Foundation",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/WalletConnect" },
  },
  // ═══════════════════════════════════════════════════════════
  // EVM — Tier 2 (Popular)
  // ═══════════════════════════════════════════════════════════
  {
    id: "frame",
    name: "Frame",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/frame",
    homepage: "https://frame.sh",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10"],
    platforms: ["desktop"],
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "sh.frame",
    openSource: true,
    walletType: "hot",
    popularity: 45,
    description: "Fast, privacy-focused Ethereum desktop wallet.",
    developer: "Frame",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/0xFrame", github: "https://github.com/floating" },
  },
  {
    id: "enkrypt",
    name: "Enkrypt",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/enkrypt",
    homepage: "https://www.enkrypt.com",
    supportedChainFamilies: ["evm", "polkadot"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/enkrypt-eth-polkadot-web/kkpllkodjeloidieedojogacfhpaihoh",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "com.enkrypt",
    walletType: "hot",
    popularity: 40,
    description: "Multi-chain wallet extension for Ethereum and Polkadot by MyCrypto.",
    developer: "MyCrypto",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/enkrypt" },
  },
  {
    id: "taho",
    name: "Taho",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tally",
    homepage: "https://taho.xyz",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:8453"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/taho/eajafomhmkipbjmfmhebemolkcicgfmd",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "xyz.taho",
    openSource: true,
    walletType: "hot",
    popularity: 42,
    description: "Community-owned, open-source Ethereum wallet. Previously Tally.",
    developer: "Taho",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/taho_xyz", github: "https://github.com/tahowallet" },
  },
  {
    id: "safeheron",
    name: "Safeheron",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/safeheron",
    homepage: "https://www.safeheron.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/safeheron/aiaghdjafodppgppdkgbmmgdcehbfmke",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 35,
    description: "Open-source self-custody wallet with MPC for secure key management.",
    developer: "Safeheron",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/Safeheron" },
  },
  {
    id: "ronin",
    name: "Ronin Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/ronin",
    homepage: "https://wallet.roninchain.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:2020"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "ronin://",
    universalLink: "https://wallet.roninchain.com",
    appStoreUrl: "https://apps.apple.com/app/ronin-wallet/id1616597823",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.skymavis.roninwallet",
    extensionUrl: "https://chromewebstore.google.com/detail/ronin-wallet/fnlmbmmdngkddcabnbgbommkcbjgokhj",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 52,
    description: "Official wallet for the Ronin blockchain (Axie Infinity ecosystem).",
    developer: "Sky Mavis",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/RoninWallet" },
  },
  {
    id: "core",
    name: "Core",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/core",
    homepage: "https://core.app",
    supportedChainFamilies: ["evm", "bitcoin"],
    supportedChains: ["eip155:1", "eip155:1116", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "core://",
    universalLink: "https://core.app",
    appStoreUrl: "https://apps.apple.com/app/core-wallet/id6443857931",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.avaxwallet",
    extensionUrl: "https://chromewebstore.google.com/detail/core-crypto-wallet-nft-ex/agoakfejjabomempkjlepdflaleeobhb",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 48,
    description: "Multi-chain browser wallet by Avalanche (Core Web3 Wallet).",
    developer: "Avalanche / Core",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/CryptoCoreApp" },
  },
  {
    id: "subwallet",
    name: "SubWallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/subwallet",
    homepage: "https://subwallet.app",
    supportedChainFamilies: ["evm", "polkadot"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "subwallet://",
    universalLink: "https://subwallet.app",
    appStoreUrl: "https://apps.apple.com/app/subwallet/id1608591765",
    playStoreUrl: "https://play.google.com/store/apps/details?id=app.subwallet.mobile",
    extensionUrl: "https://chromewebstore.google.com/detail/subwallet-polkadot-wallet/onhogfjeacnfoofkfgppdlbmlmnplgbn",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 36,
    description: "Multi-chain wallet for Polkadot and Ethereum ecosystems.",
    developer: "SubWallet",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/SubWalletApp", github: "https://github.com/Koniverse" },
  },
  {
    id: "talisman",
    name: "Talisman",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/talisman",
    homepage: "https://talisman.xyz",
    supportedChainFamilies: ["evm", "polkadot"],
    supportedChains: ["eip155:1"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/talisman-polkadot-wallet/fijngjgcjhjmmpcmkeiomlglpeiijkld",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "xyz.talisman",
    openSource: true,
    walletType: "hot",
    popularity: 34,
    description: "Ethereum and Polkadot wallet focused on security and UX.",
    developer: "Talisman",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/talismansmh", github: "https://github.com/TalismanSociety" },
  },
  {
    id: "nifty",
    name: "Nifty Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/nifty",
    homepage: "https://niftywallet.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/nifty-wallet/jbdaocneiiagmjnhpegcmpjkhggoicbf",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 30,
    description: "Multi-chain browser wallet with built-in swap and bridge.",
    developer: "Nifty",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/NiftyWallet" },
  },
  {
    id: "math-wallet",
    name: "Math Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/math",
    homepage: "https://mathwallet.org",
    supportedChainFamilies: ["evm", "solana", "cosmos", "polkadot", "near", "tron"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "mathwallet://",
    universalLink: "https://mathwallet.org",
    appStoreUrl: "https://apps.apple.com/app/math-wallet/id1444698701",
    playStoreUrl: "https://play.google.com/store/apps/details?id=mathwallet.android",
    extensionUrl: "https://chromewebstore.google.com/detail/math-wallet/afbcbjpbjdadlapmclkcinemddpiplgm",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 33,
    description: "Universal multi-chain wallet supporting 10+ blockchain ecosystems.",
    developer: "MathWallet",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/Mathwallet" },
  },
  {
    id: "huobi-wallet",
    name: "HTX Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/huobi",
    homepage: "https://www.htx.com",
    supportedChainFamilies: ["evm", "tron"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    appStoreUrl: "https://apps.apple.com/app/huobi-global/id1390818779",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.huobi.global",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 32,
    description: "HTX exchange integrated multi-chain wallet.",
    developer: "HTX",
    yearFounded: 2013,
    social: { twitter: "https://twitter.com/HTX_Global" },
  },
  // ═══════════════════════════════════════════════════════════
  // EVM — Tier 3 (Niche / Regional / Emerging)
  // ═══════════════════════════════════════════════════════════
  {
    id: "onto",
    name: "ONTO Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/onto",
    homepage: "https://onto.app",
    supportedChainFamilies: ["evm", "solana", "polkadot", "ontology", "eos"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    deepLink: "ontopro://",
    universalLink: "https://onto.app",
    appStoreUrl: "https://apps.apple.com/app/onto/id1436019325",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.github.ontio.onto",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 28,
    description: "Ontology-based multi-chain identity wallet.",
    developer: "Ontology",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/OntologyNetwork" },
  },
  {
    id: "atoken",
    name: "AToken",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/atoken",
    homepage: "https://atoken.com",
    supportedChainFamilies: ["evm", "tron"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    deepLink: "atoken://",
    universalLink: "https://atoken.com",
    appStoreUrl: "https://apps.apple.com/app/atoken/id1435488960",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.alink.aATP",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 22,
    description: "Multi-chain mobile wallet with staking support.",
    developer: "AToken",
    yearFounded: 2018,
  },
  {
    id: "coin98",
    name: "Coin98 Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/coin98",
    homepage: "https://coin98.com",
    supportedChainFamilies: ["evm", "solana", "cosmos", "near", "terra", "harmony", "kcc"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "coin98://",
    universalLink: "https://coin98.com",
    appStoreUrl: "https://apps.apple.com/app/coin98-super-app/id1561947711",
    playStoreUrl: "https://play.google.com/store/apps/details?id=coin98.crypto.finance.media",
    extensionUrl: "https://chromewebstore.google.com/detail/coin98-wallet/aeachknmefphepccionboohckonoeemg",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 44,
    description: "DeFi-focused multi-chain wallet with built-in DEX aggregator.",
    developer: "Coin98",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/coin98_wallet" },
  },
  {
    id: "frontier",
    name: "Frontier",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/frontier",
    homepage: "https://www.frontier.xyz",
    supportedChainFamilies: ["evm", "solana", "cosmos", "terra", "harmony", "near"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137"],
    platforms: ["browser_extension", "mobile", "hardware"],
    deepLink: "frontier://",
    universalLink: "https://www.frontier.xyz",
    appStoreUrl: "https://apps.apple.com/app/frontier-crypto-defi-wallet/id1499596111",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.frontierwallet",
    extensionUrl: "https://chromewebstore.google.com/detail/frontier-wallet/kppfdiipphfccemcignhifpjkapfbihd",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 38,
    description: "Multi-chain DeFi wallet with Ledger hardware integration.",
    developer: "Frontier",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/FrontierDotXYZ" },
  },
  {
    id: "grindery",
    name: "Grindery Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/grindery",
    homepage: "https://www.grindery.com",
    supportedChainFamilies: ["evm", "solana"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile"],
    deepLink: "grindery://",
    universalLink: "https://www.grindery.com",
    appStoreUrl: "https://apps.apple.com/app/grindery-wallet/id6443488748",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.grindery.wallet",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 18,
    description: "Wallet for the Grindery multi-chain ecosystem.",
    developer: "Grindery",
    yearFounded: 2022,
  },
  {
    id: "fireblocks",
    name: "Fireblocks",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/fireblocks",
    homepage: "https://www.fireblocks.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "near", "stellar"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["web"],
    supportsWalletConnectV2: true,
    walletType: "custodial",
    popularity: 46,
    description: "Enterprise-grade digital asset custody platform.",
    developer: "Fireblocks",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/fireblocks_io" },
  },
  {
    id: "sequence",
    name: "Sequence Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/sequence",
    homepage: "https://sequence.xyz",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:8453"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "sequence://",
    universalLink: "https://sequence.xyz",
    appStoreUrl: "https://apps.apple.com/app/sequence-wallet/id1627894683",
    playStoreUrl: "https://play.google.com/store/apps/details?id=xyz.sequence.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/sequence-wallet/oknboefhahgkmjlbdlhnhdmokbhgaham",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "xyz.sequence",
    walletType: "smart_contract",
    supportsAccountAbstraction: true,
    popularity: 37,
    description: "Smart contract wallet built for gaming and NFTs. By Horizon (Immutable).",
    developer: "Immutable",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/0xSequence" },
  },
  {
    id: "ambire",
    name: "Ambire Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/ambire",
    homepage: "https://www.ambire.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10"],
    platforms: ["browser_extension", "web"],
    extensionUrl: "https://chromewebstore.google.com/detail/ambire-smart-wallet/kpckgngjbnenjjingobdgcmbkfbhcbcf",
    supportsWalletConnectV2: true,
    walletType: "smart_contract",
    supportsAccountAbstraction: true,
    popularity: 26,
    description: "Open-source smart contract wallet with gasless transactions.",
    developer: "Ambire",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/AmbireWallet", github: "https://github.com/AmbireTech" },
  },
  {
    id: "loopring",
    name: "Loopring Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/loopring",
    homepage: "https://loopring.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1"],
    platforms: ["mobile"],
    deepLink: "loopring://",
    universalLink: "https://loopring.io",
    appStoreUrl: "https://apps.apple.com/app/loopring-wallet/id1558659968",
    playStoreUrl: "https://play.google.com/store/apps/details?id=loopring.org",
    supportsWalletConnectV2: true,
    walletType: "smart_contract",
    popularity: 25,
    description: "ZK rollup Layer 2 wallet for Ethereum with low-fee trading.",
    developer: "Loopring",
    yearFounded: 2017,
    social: { twitter: "https://twitter.com/loopringorg" },
  },
  {
    id: "argent",
    name: "Argent",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/argent",
    homepage: "https://www.argent.xyz",
    supportedChainFamilies: ["evm", "starknet"],
    supportedChains: ["eip155:1"],
    platforms: ["mobile"],
    deepLink: "argent://",
    universalLink: "https://argent.xyz",
    appStoreUrl: "https://apps.apple.com/app/argent/id1358741812",
    playStoreUrl: "https://play.google.com/store/apps/details?id=im.argent.contractwalletclient",
    supportsWalletConnectV2: true,
    walletType: "smart_contract",
    supportsAccountAbstraction: true,
    popularity: 41,
    description: "Smart contract wallet for Ethereum and Starknet with account recovery.",
    developer: "Argent",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/argentHQ" },
  },
  // ═══════════════════════════════════════════════════════════
  // Solana-focused
  // ═══════════════════════════════════════════════════════════
  {
    id: "sollet",
    name: "Sollet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/sollet",
    homepage: "https://www.sollet.io",
    supportedChainFamilies: ["solana"],
    supportedChains: ["solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["web"],
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 24,
    description: "One of the original Solana web wallets.",
    developer: "Project Serum",
    yearFounded: 2020,
  },
  {
    id: "solfire",
    name: "Solfire Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/solfire",
    homepage: "https://solfire.com",
    supportedChainFamilies: ["solana"],
    supportedChains: ["solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/solfire/abc",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 20,
    description: "Lightweight Solana browser extension wallet.",
    developer: "Solfire",
    yearFounded: 2022,
  },
  {
    id: "brave-wallet",
    name: "Brave Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/brave",
    homepage: "https://brave.com/wallet",
    supportedChainFamilies: ["evm", "solana"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["browser_extension"],
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "com.brave.wallet",
    openSource: true,
    walletType: "hot",
    popularity: 56,
    description: "Built-in multi-chain wallet in the Brave browser.",
    developer: "Brave Software",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/brave", github: "https://github.com/brave/brave-wallet" },
  },
  // ═══════════════════════════════════════════════════════════
  // Cosmos / IBC Ecosystem
  // ═══════════════════════════════════════════════════════════
  {
    id: "keplr",
    name: "Keplr",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/keplr",
    homepage: "https://www.keplr.app",
    supportedChainFamilies: ["cosmos"],
    supportedChains: ["cosmos:cosmoshub-4", "cosmos:osmosis-1", "cosmos:juno-1", "cosmos:injective-1"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "keplrwallet://",
    universalLink: "https://www.keplr.app",
    appStoreUrl: "https://apps.apple.com/app/keplr-wallet/id1567119399",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.chainapsis.keplr",
    extensionUrl: "https://chromewebstore.google.com/detail/keplr/dmkamcknogkgcdfhhbddcghachkejeap",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 62,
    description: "The leading wallet for Cosmos/IBC ecosystem.",
    developer: "Chainapsis",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/keplrwallet", github: "https://github.com/chainapsis" },
  },
  {
    id: "leap",
    name: "Leap Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/leap",
    homepage: "https://www.leapwallet.io",
    supportedChainFamilies: ["cosmos", "evm"],
    supportedChains: ["cosmos:cosmoshub-4", "cosmos:osmosis-1", "eip155:1"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "leapcosmos://",
    universalLink: "https://www.leapwallet.io",
    appStoreUrl: "https://apps.apple.com/app/leap-cosmos-wallet/id1633501428",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.leapwallet.cosmos",
    extensionUrl: "https://chromewebstore.google.com/detail/leap-cosmos-wallet/fcfcfllfndlomdhbehjjcoimbgafcncg",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 50,
    description: "Cosmos ecosystem wallet with staking and IBC transfer support.",
    developer: "Leap Wallet",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/LeapWallet" },
  },
  {
    id: "station",
    name: "Station (Terra)",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/terra",
    homepage: "https://terra.money",
    supportedChainFamilies: ["cosmos"],
    supportedChains: ["cosmos:columbus-5", "cosmos:phoenix-1"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "station://",
    universalLink: "https://terra.money",
    appStoreUrl: "https://apps.apple.com/app/terra-station/id1589711895",
    playStoreUrl: "https://play.google.com/store/apps/details?id=earth.terra.station",
    extensionUrl: "https://chromewebstore.google.com/detail/terra-station/aiifbnmgebopokdgljpcbmolbbimefnp",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 29,
    description: "Official Terra ecosystem wallet.",
    developer: "Terraform Labs",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/terra_money" },
  },
  {
    id: "xdefi",
    name: "XDEFI Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/xdefi",
    homepage: "https://www.xdefi.io",
    supportedChainFamilies: ["evm", "bitcoin", "cosmos", "thorchain"],
    supportedChains: ["eip155:1", "eip155:56", "bip122:000000000019d6689c085ae165831e93", "cosmos:thorchain-mainnet-v1"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/xdefi-wallet/hmeobnfnfcbbkhdaccgchmejnfhpdgpn",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "io.xdefi",
    openSource: true,
    walletType: "hot",
    popularity: 43,
    description: "Multi-chain Web3 wallet with THORChain and Bitcoin support.",
    developer: "XDEFI",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/xdefi_wallet", github: "https://github.com/XDeFi-tech" },
  },
  // ═══════════════════════════════════════════════════════════
  // Bitcoin
  // ═══════════════════════════════════════════════════════════
  {
    id: "blue-wallet",
    name: "BlueWallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/bluewallet",
    homepage: "https://bluewallet.io",
    supportedChainFamilies: ["bitcoin"],
    supportedChains: ["bip122:000000000019d6689c085ae165831e93"],
    platforms: ["mobile", "desktop"],
    deepLink: "bluewallet://",
    universalLink: "https://bluewallet.io",
    appStoreUrl: "https://apps.apple.com/app/bluewallet-bitcoin-wallet/id1376878040",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.bluewallet.bluewallet",
    openSource: true,
    walletType: "hot",
    popularity: 51,
    description: "Bitcoin-only wallet with Lightning Network support.",
    developer: "BlueWallet",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/bluewalletio", github: "https://github.com/BlueWallet" },
  },
  {
    id: "sparrow-wallet",
    name: "Sparrow Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/sparrow",
    homepage: "https://sparrowwallet.com",
    supportedChainFamilies: ["bitcoin"],
    supportedChains: ["bip122:000000000019d6689c085ae165831e93"],
    platforms: ["desktop"],
    openSource: true,
    walletType: "hot",
    popularity: 35,
    description: "Bitcoin desktop wallet focused on privacy and advanced features.",
    developer: "Craig Raw",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/SparrowWallet", github: "https://github.com/sparrowwallet" },
  },
  {
    id: "electrum",
    name: "Electrum",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/electrum",
    homepage: "https://electrum.org",
    supportedChainFamilies: ["bitcoin"],
    supportedChains: ["bip122:000000000019d6689c085ae165831e93"],
    platforms: ["desktop", "cli"],
    openSource: true,
    walletType: "hot",
    popularity: 53,
    description: "The original Bitcoin lightweight wallet, since 2011.",
    developer: "Thomas Voegtlin",
    yearFounded: 2011,
    social: { twitter: "https://twitter.com/ElectrumWallet", github: "https://github.com/spesmilo/electrum" },
  },
  {
    id: "xverse",
    name: "Xverse Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/xverse",
    homepage: "https://www.xverse.app",
    supportedChainFamilies: ["bitcoin"],
    supportedChains: ["bip122:000000000019d6689c085ae165831e93"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "xverse://",
    universalLink: "https://www.xverse.app",
    appStoreUrl: "https://apps.apple.com/app/xverse-wallet/id1640649756",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.xverse.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/xverse-wallet/idnnbdaxmphpflfnlkmjfbmikopedbbj",
    supportsWalletConnectV2: true,
    openSource: false,
    walletType: "hot",
    popularity: 39,
    description: "Bitcoin wallet with Ordinals and BRC-20 support.",
    developer: "Secret Key Labs",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/xverseApp" },
  },
  {
    id: "unisat",
    name: "UniSat Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/unisat",
    homepage: "https://unisat.io",
    supportedChainFamilies: ["bitcoin"],
    supportedChains: ["bip122:000000000019d6689c085ae165831e93"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/unisat/ppbibelpcjmhbdihakflkdcocmkgbkbc",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 34,
    description: "Bitcoin wallet for Ordinals and BRC-20 tokens.",
    developer: "UniSat",
    yearFounded: 2023,
    social: { twitter: "https://twitter.com/unisat_wallet" },
  },
  // ═══════════════════════════════════════════════════════════
  // Aptos / Sui
  // ═══════════════════════════════════════════════════════════
  {
    id: "petra",
    name: "Petra Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/petra",
    homepage: "https://petra.app",
    supportedChainFamilies: ["aptos"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/petra-aptos-wallet/ejbalmkoplchlggaogmmbbjmmghlmbnn",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 38,
    description: "Leading wallet for the Aptos blockchain.",
    developer: "Petra",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/petra_app" },
  },
  {
    id: "martian",
    name: "Martian Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/martian",
    homepage: "https://martianwallet.xyz",
    supportedChainFamilies: ["aptos", "sui", "bitcoin"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "martian://",
    universalLink: "https://martianwallet.xyz",
    appStoreUrl: "https://apps.apple.com/app/martian-wallet/id6443407689",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.martianwallet",
    extensionUrl: "https://chromewebstore.google.com/detail/martian-aptos-wallet/efbglaiasppcgjgdgklmdofjhfljgmci",
    supportsWalletConnectV2: true,
    openSource: false,
    walletType: "hot",
    popularity: 32,
    description: "Multi-chain wallet for Aptos, Sui, and Bitcoin.",
    developer: "Martian",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/MartianWallet" },
  },
  {
    id: "sui-wallet",
    name: "Sui Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/suiwallet",
    homepage: "https://suiwallet.com",
    supportedChainFamilies: ["sui"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/sui-wallet/opcgpfmipidbgponhmajmpahiigminig",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 30,
    description: "Official wallet for the Sui blockchain.",
    developer: "Mysten Labs",
    yearFounded: 2023,
    social: { twitter: "https://twitter.com/SuiNetwork", github: "https://github.com/MystenLabs/sui-wallet" },
  },
  {
    id: "suro-wallet",
    name: "Suro Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/suiwallet",
    homepage: "https://suro.app",
    supportedChainFamilies: ["sui"],
    platforms: ["mobile"],
    deepLink: "suro://",
    universalLink: "https://suro.app",
    appStoreUrl: "https://apps.apple.com/app/suro/id6444458424",
    playStoreUrl: "https://play.google.com/store/apps/details?id=app.suro.wallet",
    walletType: "hot",
    popularity: 20,
    description: "Mobile-first wallet for the Sui ecosystem.",
    developer: "Suro",
    yearFounded: 2023,
    social: { twitter: "https://twitter.com/suro_app" },
  },
  // ═══════════════════════════════════════════════════════════
  // NEAR
  // ═══════════════════════════════════════════════════════════
  {
    id: "here-wallet",
    name: "HERE Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/here",
    homepage: "https://www.herewallet.app",
    supportedChainFamilies: ["near"],
    platforms: ["mobile", "browser_extension"],
    deepLink: "herewallet://",
    universalLink: "https://www.herewallet.app",
    appStoreUrl: "https://apps.apple.com/app/here-wallet/id1627690576",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.herewallet.app",
    extensionUrl: "https://chromewebstore.google.com/detail/here-wallet/aaaomknclhhlcgfogemampkdcgjbhkdm",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 27,
    description: "Mobile-first wallet for the NEAR Protocol.",
    developer: "HERE Wallet",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/HEREwallet" },
  },
  {
    id: "near-wallet",
    name: "NEAR Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/near",
    homepage: "https://wallet.near.org",
    supportedChainFamilies: ["near"],
    platforms: ["web"],
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 40,
    description: "Official NEAR Protocol web wallet.",
    developer: "NEAR Foundation",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/NEARProtocol" },
  },
  {
    id: "sender",
    name: "Sender Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/sender",
    homepage: "https://senderwallet.io",
    supportedChainFamilies: ["near", "evm"],
    supportedChains: ["eip155:1"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/sender-wallet/epapihdplmajcdmbkfedegpdgcgkdmfh",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 25,
    description: "Multi-chain wallet for NEAR and EVM chains.",
    developer: "Sender Wallet",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/SenderWallet" },
  },
  // ═══════════════════════════════════════════════════════════
  // Tron
  // ═══════════════════════════════════════════════════════════
  {
    id: "tronlink",
    name: "TronLink",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tronlink",
    homepage: "https://www.tronlink.org",
    supportedChainFamilies: ["tron", "evm"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "tronlink://",
    universalLink: "https://www.tronlink.org",
    appStoreUrl: "https://apps.apple.com/app/tronlink/id1439361739",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.tronlink.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/tronlink- wallet/ibnejdfjmmkpcnlpebklmnkoeoihofec",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 47,
    description: "Official Tron blockchain wallet.",
    developer: "TronLink",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/Tronlinkwallet" },
  },
  // ═══════════════════════════════════════════════════════════
  // TON
  // ═══════════════════════════════════════════════════════════
  {
    id: "tonkeeper",
    name: "Tonkeeper",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tonkeeper",
    homepage: "https://tonkeeper.com",
    supportedChainFamilies: ["ton"],
    platforms: ["mobile", "browser_extension"],
    deepLink: "tonkeeper://",
    universalLink: "https://tonkeeper.com",
    appStoreUrl: "https://apps.apple.com/app/tonkeeper/id1455019088",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.ton_keeper",
    extensionUrl: "https://chromewebstore.google.com/detail/tonkeeper/nbdhibgjnjpnkajaghbffjbkcgljfgdi",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 55,
    description: "The leading TON blockchain wallet.",
    developer: "Tonkeeper",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/ton_keeper" },
  },
  {
    id: "tonhub",
    name: "Tonhub",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tonhub",
    homepage: "https://tonhub.com",
    supportedChainFamilies: ["ton"],
    platforms: ["mobile"],
    deepLink: "tonhub://",
    universalLink: "https://tonhub.com",
    appStoreUrl: "https://apps.apple.com/app/tonhub-wallet/id1605678378",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.parallax.tonhub",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 35,
    description: "Secure TON wallet with DeFi integration.",
    developer: "Ton Foundation",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/tonhub_app" },
  },
  {
    id: "mytonwallet",
    name: "MyTonWallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/mytonwallet",
    homepage: "https://mytonwallet.io",
    supportedChainFamilies: ["ton"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/mytonwallet/nmepcmlhncfifkbgmmhfbkncjnbmncbj",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 22,
    description: "Open-source TON wallet with multi-device sync.",
    developer: "MyTonWallet",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/mytonwallet_io" },
  },
  // ═══════════════════════════════════════════════════════════
  // Starknet
  // ═══════════════════════════════════════════════════════════
  {
    id: "braavos",
    name: "Braavos",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/braavos",
    homepage: "https://braavos.app",
    supportedChainFamilies: ["starknet"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "braavos://",
    universalLink: "https://braavos.app",
    appStoreUrl: "https://apps.apple.com/app/braavos-smart-wallet/id6445956473",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.braavos.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/braavos/jnlgamecbpmbajjfhmmmlhejkemejdma",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "smart_contract",
    supportsAccountAbstraction: true,
    popularity: 44,
    description: "Leading Starknet wallet with hardware-grade security.",
    developer: "Braavos",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/BraavosWallet" },
  },
  {
    id: "argent-x",
    name: "Argent X",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/argentx",
    homepage: "https://www.argent.xyz/argent-x",
    supportedChainFamilies: ["starknet"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "argent://",
    universalLink: "https://www.argent.xyz",
    extensionUrl: "https://chromewebstore.google.com/detail/argent-x/dlcobpjiigpikoobohmabnhhmhfdnnii",
    supportsWalletConnectV2: true,
    walletType: "smart_contract",
    supportsAccountAbstraction: true,
    popularity: 40,
    description: "Starknet wallet by Argent with social recovery.",
    developer: "Argent",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/argentHQ" },
  },
  // ═══════════════════════════════════════════════════════════
  // Hedera
  // ═══════════════════════════════════════════════════════════
  {
    id: "blade",
    name: "Blade Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/blade",
    homepage: "https://blade.me",
    supportedChainFamilies: ["hedera"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/blade-hedera-wallet/mcocohpcbgafiiikaifmmgldfomcjfep",
    walletType: "hot",
    popularity: 23,
    description: "Hedera wallet with staking and DeFi support.",
    developer: "Blade",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/Blade_Hedera" },
  },
  {
    id: "hashpack",
    name: "HashPack",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/hashpack",
    homepage: "https://www.hashpack.app",
    supportedChainFamilies: ["hedera"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "hashpack://",
    universalLink: "https://www.hashpack.app",
    appStoreUrl: "https://apps.apple.com/app/hashpack/id6443840635",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com/hashpack/app",
    extensionUrl: "https://chromewebstore.google.com/detail/hashpack/gjagmgiddbbiigjhllhcfpglbgphicgj",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 30,
    description: "Most popular Hedera wallet with token management.",
    developer: "HashPack",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/itshashpack" },
  },
  // ═══════════════════════════════════════════════════════════
  // XRPL
  // ═══════════════════════════════════════════════════════════
  {
    id: "xumm",
    name: "Xaman (XUMM)",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/xumm",
    homepage: "https://xaman.app",
    supportedChainFamilies: ["xrpl"],
    platforms: ["mobile"],
    deepLink: "xumm://",
    universalLink: "https://xaman.app",
    appStoreUrl: "https://apps.apple.com/app/xumm/id1470248019",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.xrplfoundation.xumm",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 36,
    description: "The premier XRPL wallet for signing transactions.",
    developer: "XRPL Foundation / Wietse Wind",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/xumm" },
  },
  // ═══════════════════════════════════════════════════════════
  // Cardano
  // ═══════════════════════════════════════════════════════════
  {
    id: "eternl",
    name: "Eternl",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/eternl",
    homepage: "https://eternl.io",
    supportedChainFamilies: ["cardano"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "eternl://",
    universalLink: "https://eternl.io",
    appStoreUrl: "https://apps.apple.com/app/eternl/id6446363156",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.eternl.mobile",
    extensionUrl: "https://chromewebstore.google.com/detail/eternl/khclkbglgdgbdgkgbfhbpkgbpkgbdfhg",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 42,
    description: "Feature-rich Cardano wallet with NFT and DeFi support.",
    developer: "Eternl",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/Eternl_io" },
  },
  {
    id: "nami",
    name: "Nami",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/nami",
    homepage: "https://namiwallet.io",
    supportedChainFamilies: ["cardano"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/nami/lpfcbjknjpeeillaihoekokdamcmoken",
    openSource: true,
    walletType: "hot",
    popularity: 38,
    description: "Simple and elegant Cardano browser wallet.",
    developer: "Berry Pool",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/namiwallet" },
  },
  {
    id: "yoroi",
    name: "Yoroi",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/yoroi",
    homepage: "https://yoroi-wallet.com",
    supportedChainFamilies: ["cardano"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "yoroi://",
    universalLink: "https://yoroi-wallet.com",
    appStoreUrl: "https://apps.apple.com/app/yoroi-wallet/id1468288179",
    playStoreUrl: "https://play.google.com/store/apps/details?id=co.jp.emurgo.yoroi",
    extensionUrl: "https://chromewebstore.google.com/detail/yoroi/ppbibelpcjmhbdihakflkdcocmkgbkbc",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 45,
    description: "Light Cardano wallet by EMURGO. One of the first Cardano wallets.",
    developer: "EMURGO",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/YoroiWallet" },
  },
  // ═══════════════════════════════════════════════════════════
  // Social / Embedded / Embedded Wallets
  // ═══════════════════════════════════════════════════════════
  {
    id: "dynamic",
    name: "Dynamic",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/dynamic",
    homepage: "https://www.dynamic.xyz",
    supportedChainFamilies: ["evm", "solana", "aptos"],
    supportedChains: ["eip155:1", "eip155:137", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["web"],
    supportsWalletConnectV2: true,
    walletType: "embedded",
    supportsAccountAbstraction: true,
    popularity: 36,
    description: "Embedded wallet SDK for seamless Web3 onboarding.",
    developer: "Dynamic",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/dynamic_xyz" },
  },
  {
    id: "privy",
    name: "Privy",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/privy",
    homepage: "https://www.privy.io",
    supportedChainFamilies: ["evm", "solana"],
    supportedChains: ["eip155:1", "eip155:137", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["web"],
    walletType: "embedded",
    supportsAccountAbstraction: true,
    popularity: 42,
    description: "Authentication and embedded wallet infrastructure for Web3 apps.",
    developer: "Privy",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/privy_io" },
  },
  {
    id: "web3auth",
    name: "Web3Auth",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/web3auth",
    homepage: "https://web3auth.io",
    supportedChainFamilies: ["evm", "solana"],
    supportedChains: ["eip155:1"],
    platforms: ["web"],
    walletType: "social",
    supportsAccountAbstraction: true,
    popularity: 44,
    description: "Decentralized authentication and key management platform.",
    developer: "Web3Auth",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/Web3Auth" },
  },
  {
    id: "particle-network",
    name: "Particle Network",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/particle",
    homepage: "https://particle.network",
    supportedChainFamilies: ["evm", "solana", "aptos", "sui", "ton"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["web", "mobile"],
    walletType: "social",
    supportsAccountAbstraction: true,
    popularity: 33,
    description: "Chain abstraction platform with social login and wallet-as-a-service.",
    developer: "Particle Network",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/ParticleNtwrk" },
  },
  {
    id: "thirdweb",
    name: "Thirdweb In-App Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/thirdweb",
    homepage: "https://thirdweb.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:8453"],
    platforms: ["web"],
    walletType: "embedded",
    supportsAccountAbstraction: true,
    popularity: 40,
    description: "Embedded wallets and Web3 infrastructure by thirdweb.",
    developer: "thirdweb",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/thirdweb_", github: "https://github.com/thirdweb-dev" },
  },
  // ═══════════════════════════════════════════════════════════
  // More EVM wallets
  // ═══════════════════════════════════════════════════════════
  {
    id: "onekey",
    name: "OneKey",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/onekey",
    homepage: "https://onekey.so",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "aptos", "sui", "near", "cosmos", "cardano", "ton"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["browser_extension", "mobile", "desktop", "hardware"],
    deepLink: "onekey://",
    universalLink: "https://onekey.so",
    appStoreUrl: "https://apps.apple.com/app/onekey/id1609559473",
    playStoreUrl: "https://play.google.com/store/apps/details?id=so.onekey.app.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/onekey/jnmbobjmhlngoefaiojfljckilhhlhcj",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 50,
    description: "Open-source multi-chain wallet with hardware wallet support.",
    developer: "OneKey",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/OneKeyHQ", github: "https://github.com/OneKeyHQ" },
  },
  {
    id: "atomic",
    name: "Atomic Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/atomic",
    homepage: "https://atomicwallet.io",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "cardano", "stellar", "algorand", "tron", "hedera", "cosmos"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["desktop", "mobile"],
    deepLink: "atomic://",
    universalLink: "https://atomicwallet.io",
    appStoreUrl: "https://apps.apple.com/app/atomic-wallet/id1438600830",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.atomicwallet",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 35,
    description: "Multi-currency non-custodial wallet with built-in exchange.",
    developer: "Atomic Wallet",
    yearFounded: 2017,
    social: { twitter: "https://twitter.com/AtomicWallet" },
  },
  {
    id: "guarda",
    name: "Guarda Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/guarda",
    homepage: "https://guarda.com",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "cardano", "tron", "stellar", "polkadot", "cosmos", "near", "algorand", "hedera"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["browser_extension", "mobile", "desktop", "web"],
    deepLink: "guarda://",
    universalLink: "https://guarda.com",
    appStoreUrl: "https://apps.apple.com/app/guarda-crypto-wallet/id1372359351",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.crypto.multiwallet",
    extensionUrl: "https://chromewebstore.google.com/detail/guarda-wallet/hpglfhgfnhbgfhgfhgfhgfhgfhgfhgfh",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 31,
    description: "Multi-platform wallet supporting 50+ blockchains.",
    developer: "Guarda",
    yearFounded: 2017,
    social: { twitter: "https://twitter.com/Guarda_wallet" },
  },
  {
    id: "infinity-wallet",
    name: "Infinity Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/infinity",
    homepage: "https://infinitywallet.io",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "polkadot", "cosmos", "near"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["desktop"],
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 20,
    description: "Desktop multi-chain wallet with hardware support.",
    developer: "Infinity Wallet",
    yearFounded: 2022,
  },
  {
    id: "fox-wallet",
    name: "FoxWallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/foxwallet",
    homepage: "https://foxwallet.com",
    supportedChainFamilies: ["evm", "bsc", "harmony", "cronos"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    deepLink: "foxwallet://",
    universalLink: "https://foxwallet.com",
    appStoreUrl: "https://apps.apple.com/app/foxwallet/id1614001480",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.foxwallet",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 19,
    description: "Web3 mobile wallet with DeFi focus.",
    developer: "FoxWallet",
    yearFounded: 2021,
  },
  {
    id: "pillect",
    name: "Pillect Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/pillect",
    homepage: "https://pillect.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile"],
    deepLink: "pillect://",
    universalLink: "https://pillect.com",
    appStoreUrl: "https://apps.apple.com/app/pillect/id1614001481",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.pillect",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 15,
    description: "Multi-chain DeFi wallet.",
    developer: "Pillect",
    yearFounded: 2022,
  },
  {
    id: "tavern-wallet",
    name: "Tavern Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tavern",
    homepage: "https://tavernwallet.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1"],
    platforms: ["web"],
    walletType: "hot",
    popularity: 12,
    description: "Simple web wallet for quick transactions.",
    developer: "Tavern",
    yearFounded: 2023,
  },
  {
    id: "cyberconnect",
    name: "CyberConnect Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/cyberconnect",
    homepage: "https://cyberconnect.me",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["web"],
    supportsWalletConnectV2: true,
    walletType: "social",
    popularity: 28,
    description: "Social graph wallet for decentralized social.",
    developer: "CyberConnect",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/CyberConnectHQ" },
  },
  {
    id: "mask-network",
    name: "Mask Network",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/mask",
    homepage: "https://mask.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/mask-network/dbeefadbfjcbmgfnfkfhfjcbmgfnfkfh",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 24,
    description: "Web3 bridge connecting social platforms to decentralized networks.",
    developer: "Mask Network",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/realMaskNetwork" },
  },
  {
    id: "gem-wallet",
    name: "Gem Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/gemwallet",
    homepage: "https://gemwallet.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "aptos", "cosmos", "near"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile"],
    deepLink: "gemwallet://",
    universalLink: "https://gemwallet.com",
    appStoreUrl: "https://apps.apple.com/app/gem-wallet-crypto-defi/id6444634568",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.gemwallet",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 25,
    description: "Open-source multi-chain mobile wallet with privacy focus.",
    developer: "Gem Wallet",
    yearFounded: 2023,
    social: { twitter: "https://twitter.com/gemwalletcom", github: "https://github.com/gemwalletcom" },
  },
  {
    id: "zengo",
    name: "ZenGo",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/zengo",
    homepage: "https://zengo.com",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "polkadot", "cosmos", "ton", "near", "algorand", "hedera", "flow"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile"],
    deepLink: "zengo://",
    universalLink: "https://zengo.com",
    appStoreUrl: "https://apps.apple.com/app/zengo-crypto-nft-wallet/id1475296939",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.zengo.wallet",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 43,
    description: "Seedless wallet with biometric MPC security. No private keys to lose.",
    developer: "ZenGo",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/ZenGo" },
  },
  {
    id: "cryptocom",
    name: "Crypto.com DeFi Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/cryptocom",
    homepage: "https://crypto.com/defi-wallet",
    supportedChainFamilies: ["evm", "cosmos"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile", "browser_extension"],
    deepLink: "cryptowallet://",
    universalLink: "https://crypto.com/defi-wallet",
    appStoreUrl: "https://apps.apple.com/app/crypto-com-defi-wallet/id1512011270",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.crypto.defiwallet",
    extensionUrl: "https://chromewebstore.google.com/detail/crypto-com-defi-wallet/hfhgkbdalhbflcmkfhfljcbmgfnfkfh",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 49,
    description: "DeFi wallet by Crypto.com with multi-chain support.",
    developer: "Crypto.com",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/cryptocom" },
  },
  {
    id: "binance-wallet",
    name: "Binance Web3 Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/binance",
    homepage: "https://www.binance.com/web3wallet",
    supportedChainFamilies: ["evm", "solana", "bitcoin"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    appStoreUrl: "https://apps.apple.com/app/binance/id1436011491",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.binance.dev",
    supportsWalletConnectV2: true,
    walletType: "custodial",
    popularity: 65,
    description: "Web3 wallet integrated into the Binance app.",
    developer: "Binance",
    yearFounded: 2023,
    social: { twitter: "https://twitter.com/binance" },
  },
  {
    id: "block-wallet",
    name: "BlockWallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/blockwallet",
    homepage: "https://blockwallet.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/blockwallet/iffmfpagmhkgffgffgfhgfhgfhgfhgfh",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "io.blockwallet",
    openSource: true,
    walletType: "hot",
    popularity: 18,
    description: "Privacy-focused fork of MetaMask with zero tracking.",
    developer: "BlockWallet",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/BlockWallet_", github: "https://github.com/block-wallet" },
  },
  {
    id: "liquality",
    name: "Liquality Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/liquality",
    homepage: "https://liquality.io",
    supportedChainFamilies: ["evm", "bitcoin", "near"],
    supportedChains: ["eip155:1", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/liquality-wallet/kpfopkcmahbgfmjfcbfclmfhfgbfhcje",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 16,
    description: "Multi-chain wallet with atomic swap capability.",
    developer: "Liquality",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/LiqualityIO" },
  },
  {
    id: "unstoppable",
    name: "Unstoppable Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/unstoppable",
    homepage: "https://unstoppable.money",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "cardano", "polkadot", "cosmos"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    deepLink: "unstoppable://",
    universalLink: "https://unstoppable.money",
    appStoreUrl: "https://apps.apple.com/app/unstoppable-crypto-wallet/id1447619907",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.horizontalsystems.bankwallet",
    openSource: true,
    walletType: "hot",
    popularity: 27,
    description: "Open-source multi-chain wallet focused on privacy and security.",
    developer: "Horizontal Systems",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/UnstoppableByHS", github: "https://github.com/horizontalsystems" },
  },
  {
    id: "pocket-universe",
    name: "Pocket Universe",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/pocketuniverse",
    homepage: "https://www.pocketuniverse.app",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/pocket-universe/epapihdplmajcdmbkfedegpdgcgkdmfi",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 22,
    description: "Security-focused wallet that simulates transactions before signing.",
    developer: "Pocket Universe",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/pocketuniverse3" },
  },
  {
    id: "ripio",
    name: "Ripio Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/ripio",
    homepage: "https://ripio.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile"],
    deepLink: "ripio://",
    universalLink: "https://ripio.com",
    appStoreUrl: "https://apps.apple.com/app/ripio/id1447046828",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.ripio",
    walletType: "hot",
    popularity: 14,
    description: "Latin American focused crypto wallet and exchange.",
    developer: "Ripio",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/RipioInc" },
  },
  {
    id: "wallacy",
    name: "Wallacy",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/wallacy",
    homepage: "https://wallacy.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    walletType: "hot",
    popularity: 10,
    description: "Simple mobile crypto wallet.",
    developer: "Wallacy",
    yearFounded: 2022,
  },
  // ═══════════════════════════════════════════════════════════
  // Gaming / NFT focused wallets
  // ═══════════════════════════════════════════════════════════
  {
    id: "gamestop",
    name: "GameStop Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/gamestop",
    homepage: "https://nft.gamestop.com/wallet",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "gamestop://",
    universalLink: "https://nft.gamestop.com",
    appStoreUrl: "https://apps.apple.com/app/gamestop-wallet/id1618139316",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.gamestop.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/gamestop-wallet/annmjhdbfhjbkdmhjhdbkdmhjhdbkdmh",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 26,
    description: "NFT-focused wallet by GameStop.",
    developer: "GameStop",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/GameStop" },
  },
  {
    id: "eloop",
    name: "ELOOP Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/eloop",
    homepage: "https://eloop.wallet",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1"],
    platforms: ["mobile"],
    walletType: "hot",
    popularity: 11,
    description: "Gaming-focused Web3 wallet.",
    developer: "ELOOP",
    yearFounded: 2023,
  },
  // ═══════════════════════════════════════════════════════════
  // Additional emerging wallets
  // ═══════════════════════════════════════════════════════════
  {
    id: "clv-wallet",
    name: "CLV Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/clv",
    homepage: "https://clv.org",
    supportedChainFamilies: ["evm", "bitcoin", "polkadot"],
    supportedChains: ["eip155:1"],
    platforms: ["mobile"],
    deepLink: "clv://",
    universalLink: "https://clv.org",
    appStoreUrl: "https://apps.apple.com/app/clv-wallet/id1571005876",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.clv.wallet",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 15,
    description: "Multi-chain wallet by Clover Finance.",
    developer: "Clover Finance",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/clover_finance" },
  },
  {
    id: "tp-wallet",
    name: "TP Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tpwallet",
    homepage: "https://www.tpwallet.io",
    supportedChainFamilies: ["evm", "solana", "tron"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    deepLink: "tpoutside://",
    universalLink: "https://www.tpwallet.io",
    appStoreUrl: "https://apps.apple.com/app/tp-wallet/id1435673937",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.tokenpocket.tpwallet",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 21,
    description: "Multi-chain mobile wallet by TokenPocket team.",
    developer: "TP",
    yearFounded: 2018,
  },
  {
    id: "cool-wallet",
    name: "CoolWallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/coolwallet",
    homepage: "https://www.coolwallet.io",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "cardano", "polkadot", "cosmos", "aptos", "sui", "hedera"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile", "hardware"],
    deepLink: "coolwallet://",
    universalLink: "https://www.coolwallet.io",
    appStoreUrl: "https://apps.apple.com/app/coolwallet-s/id1464191401",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.coolbitx.cwsapp",
    supportsWalletConnectV2: true,
    walletType: "cold",
    popularity: 32,
    description: "Bluetooth hardware wallet with mobile app.",
    developer: "CoolBitX",
    yearFounded: 2015,
    social: { twitter: "https://twitter.com/CoolBitX_" },
  },
  {
    id: "dcent",
    name: "D'CENT Biometric Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/dcent",
    homepage: "https://dcentwallet.com",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "cardano", "cosmos", "polkadot", "hedera", "xrpl"],
    supportedChains: ["eip155:1"],
    platforms: ["hardware"],
    deepLink: "dcent://",
    universalLink: "https://dcentwallet.com",
    appStoreUrl: "https://apps.apple.com/app/dcent-hardware-wallet/id1452898941",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.kr.iotrust.dcent.wallet",
    supportsWalletConnectV2: true,
    walletType: "cold",
    popularity: 28,
    description: "Biometric hardware wallet with fingerprint authentication.",
    developer: "IoTrust",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/DcentWallet" },
  },
  {
    id: "keyring-pro",
    name: "Keyring Pro",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/keyring",
    homepage: "https://keyring.pro",
    supportedChainFamilies: ["evm", "solana"],
    supportedChains: ["eip155:1"],
    platforms: ["mobile"],
    deepLink: "keyring://",
    universalLink: "https://keyring.pro",
    appStoreUrl: "https://apps.apple.com/app/keyring-pro/id1583856512",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.keyring",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 17,
    description: "Secure multi-chain wallet for DeFi users.",
    developer: "Keyring",
    yearFounded: 2021,
  },
  {
    id: "infinitex",
    name: "Infinitex",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/infinitex",
    homepage: "https://infinitex.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile"],
    walletType: "smart_contract",
    supportsAccountAbstraction: true,
    popularity: 13,
    description: "Account abstraction wallet for gasless transactions.",
    developer: "Infinitex",
    yearFounded: 2023,
  },
  {
    id: "burner-wallet",
    name: "Burner Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/burner",
    homepage: "https://www.burnerwallet.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1"],
    platforms: ["web"],
    walletType: "hot",
    popularity: 14,
    description: "Disposable web wallet for events and demos.",
    developer: "Burner Wallet",
    yearFounded: 2017,
  },
];

/** Total wallet count. */
export const WALLET_COUNT = WALLET_REGISTRY.length;
