/**
 * Website App Middleware
 * Applies security headers to all responses
 * 
 * SECURITY: Uses nonce-based CSP (auto-generated per request).
 * Next.js inline scripts will receive nonce via the nonce prop.
 */
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { securityHeadersMiddleware } from '@cinacoin/next/server';

// Create security headers middleware with website-specific CSP overrides
// Nonce is auto-generated by securityHeadersMiddleware and injected into script-src/style-src
export const middleware = securityHeadersMiddleware({
  cspOverrides: {
    'script-src': ["'self'", 'https://api.cinacoin.com'],
    'style-src': ["'self'"],
    'img-src': ["'self'", 'data:', 'blob:', 'https:', 'http:'], // Allow all images
    'font-src': ["'self'", 'data:'], // Allow font files
    'connect-src': [
      "'self'",
      'https://*.walletconnect.com',
      'https://*.walletconnect.org',
      'wss://*.walletconnect.com',
      'https://api.cinacoin.com',
      'https://rpc.cinacoin.com',
    ],
    'frame-src': ["'self'", 'https://*.walletconnect.com'], // WalletConnect modal
  },
});

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
};
