/**
 * EVM Chain Registry — Auto-generated from chainid.network.
 *
 * DO NOT EDIT MANUALLY. Run `pnpm fetch-chains` to regenerate.
 *
 * Generated: 2026-06-04T00:49:35.176Z
 * Chain count: 150
 */

import type { ChainRegistryEntry, ChainCategory } from './types.js';

/* ------------------------------------------------------------------ */
/*  Chain Registry Data                                                */
/* ------------------------------------------------------------------ */

export const CHAIN_REGISTRY: ChainRegistryEntry[] = [
  {
    id: 1,
    name: 'Ethereum Mainnet',
    shortName: 'eth',
    rpcUrls: ['https://api.mycryptoapi.com/eth', 'https://cloudflare-eth.com', 'https://ethereum-rpc.publicnode.com', 'wss://ethereum-rpc.publicnode.com', 'https://mainnet.gateway.tenderly.co'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://etherscan.io',
    icon: 'ethereum.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 2,
    name: 'Expanse Network',
    shortName: 'exp',
    rpcUrls: ['https://node.expanse.tech'],
    nativeCurrency: { name: 'Expanse Network Ether', symbol: 'EXP', decimals: 18 },
    blockExplorer: '',
    icon: 'expanse.tech',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 3,
    name: 'Ropsten',
    shortName: 'rop',
    rpcUrls: [],
    nativeCurrency: { name: 'Ropsten Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://ropsten.etherscan.io',
    icon: 'github.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 4,
    name: 'Rinkeby',
    shortName: 'rin',
    rpcUrls: [],
    nativeCurrency: { name: 'Rinkeby Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://rinkeby.etherscan.io',
    icon: 'www.rinkeby.io',
    testnet: false,
    category: 'l2' as const,
  },
  {
    id: 5,
    name: 'Goerli',
    shortName: 'gor',
    rpcUrls: ['https://rpc.goerli.mudit.blog/', 'https://ethereum-goerli-rpc.publicnode.com', 'wss://ethereum-goerli-rpc.publicnode.com', 'https://goerli.gateway.tenderly.co', 'wss://goerli.gateway.tenderly.co'],
    nativeCurrency: { name: 'Goerli Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://goerli.etherscan.io',
    icon: 'goerli.net',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 7,
    name: 'ThaiChain',
    shortName: 'tch',
    rpcUrls: ['https://rpc.dome.cloud', 'https://rpc.thaichain.org'],
    nativeCurrency: { name: 'ThaiChain Ether', symbol: 'TCH', decimals: 18 },
    blockExplorer: 'https://exp.thaichain.org',
    icon: 'thaichain.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 8,
    name: 'Ubiq',
    shortName: 'ubq',
    rpcUrls: ['https://rpc.octano.dev', 'https://pyrus2.ubiqscan.io'],
    nativeCurrency: { name: 'Ubiq Ether', symbol: 'UBQ', decimals: 18 },
    blockExplorer: 'https://ubiqscan.io',
    icon: 'ubiqsmart.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 9,
    name: 'Quai Network Mainnet',
    shortName: 'quai',
    rpcUrls: ['https://rpc.quai.network/cyprus1'],
    nativeCurrency: { name: 'Quai', symbol: 'QUAI', decimals: 18 },
    blockExplorer: 'https://quaiscan.io',
    icon: 'qu.ai',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 10,
    name: 'OP Mainnet',
    shortName: 'oeth',
    rpcUrls: ['https://mainnet.optimism.io', 'https://optimism-rpc.publicnode.com', 'wss://optimism-rpc.publicnode.com', 'https://optimism.gateway.tenderly.co', 'wss://optimism.gateway.tenderly.co'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://optimistic.etherscan.io',
    icon: 'optimism.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 11,
    name: 'Metadium Mainnet',
    shortName: 'meta',
    rpcUrls: ['https://api.metadium.com/prod'],
    nativeCurrency: { name: 'Metadium Mainnet Ether', symbol: 'META', decimals: 18 },
    blockExplorer: '',
    icon: 'metadium.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 12,
    name: 'Metadium Testnet',
    shortName: 'kal',
    rpcUrls: ['https://api.metadium.com/dev'],
    nativeCurrency: { name: 'Metadium Testnet Ether', symbol: 'KAL', decimals: 18 },
    blockExplorer: '',
    icon: 'metadium.com',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 13,
    name: 'Diode Testnet Staging',
    shortName: 'dstg',
    rpcUrls: ['https://staging.diode.io:8443/', 'wss://staging.diode.io:8443/ws'],
    nativeCurrency: { name: 'Staging Diodes', symbol: 'sDIODE', decimals: 18 },
    blockExplorer: '',
    icon: 'diode.io',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 14,
    name: 'Flare Mainnet',
    shortName: 'flr',
    rpcUrls: ['https://flare-api.flare.network/ext/C/rpc', 'https://flare.rpc.thirdweb.com', 'https://flare-bundler.etherspot.io', 'https://rpc.ankr.com/flare', 'https://01-gravelines-003-01.rpc.tatum.io/ext/bc/C/rpc'],
    nativeCurrency: { name: 'Flare', symbol: 'FLR', decimals: 18 },
    blockExplorer: 'https://flare-explorer.flare.network',
    icon: 'flare.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 15,
    name: 'Diode Prenet',
    shortName: 'diode',
    rpcUrls: ['https://prenet.diode.io:8443/', 'wss://prenet.diode.io:8443/ws'],
    nativeCurrency: { name: 'Diodes', symbol: 'DIODE', decimals: 18 },
    blockExplorer: '',
    icon: 'diode.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 16,
    name: 'Songbird Testnet Coston',
    shortName: 'cflr',
    rpcUrls: ['https://coston-api.flare.network/ext/C/rpc', 'https://songbird-testnet-coston.rpc.thirdweb.com', 'https://01-gravelines-004-01.rpc.tatum.io/ext/bc/C/rpc', 'https://02-chicago-004-02.rpc.tatum.io/ext/bc/C/rpc', 'https://02-tokyo-004-03.rpc.tatum.io/ext/bc/C/rpc'],
    nativeCurrency: { name: 'Coston Flare', symbol: 'CFLR', decimals: 18 },
    blockExplorer: 'https://coston-explorer.flare.network',
    icon: 'flare.network',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 17,
    name: 'ThaiChain 2.0 ThaiFi',
    shortName: 'tfi',
    rpcUrls: ['https://rpc.thaifi.com'],
    nativeCurrency: { name: 'Thaifi Ether', symbol: 'TFI', decimals: 18 },
    blockExplorer: '',
    icon: 'exp.thaifi.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 18,
    name: 'ThunderCore Testnet',
    shortName: 'TST',
    rpcUrls: ['https://testnet-rpc.thundercore.com', 'https://thundercore-testnet.drpc.org', 'wss://thundercore-testnet.drpc.org'],
    nativeCurrency: { name: 'ThunderCore Testnet Token', symbol: 'TST', decimals: 18 },
    blockExplorer: 'https://explorer-testnet.thundercore.com',
    icon: 'thundercore.com',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 19,
    name: 'Songbird Canary-Network',
    shortName: 'sgb',
    rpcUrls: ['https://songbird-api.flare.network/ext/C/rpc', 'https://01-gravelines-006-01.rpc.tatum.io/ext/bc/C/rpc', 'https://01-vinthill-006-02.rpc.tatum.io/ext/bc/C/rpc', 'https://02-tokyo-006-03.rpc.tatum.io/ext/bc/C/rpc', 'https://rpc.au.cc/songbird'],
    nativeCurrency: { name: 'Songbird', symbol: 'SGB', decimals: 18 },
    blockExplorer: 'https://songbird-explorer.flare.network',
    icon: 'flare.network',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 20,
    name: 'Elastos Smart Chain',
    shortName: 'esc',
    rpcUrls: ['https://api.elastos.io/eth'],
    nativeCurrency: { name: 'Elastos', symbol: 'ELA', decimals: 18 },
    blockExplorer: 'https://esc.elastos.io',
    icon: 'www.elastos.org',
    testnet: false,
    category: 'sidechain' as const,
  },
  {
    id: 21,
    name: 'Elastos Smart Chain Testnet',
    shortName: 'esct',
    rpcUrls: ['https://api-testnet.elastos.io/eth'],
    nativeCurrency: { name: 'Elastos', symbol: 'tELA', decimals: 18 },
    blockExplorer: 'https://esc-testnet.elastos.io',
    icon: 'www.elastos.org',
    testnet: false,
    category: 'sidechain' as const,
  },
  {
    id: 24,
    name: 'KardiaChain Mainnet',
    shortName: 'kardiachain',
    rpcUrls: ['https://rpc.kardiachain.io'],
    nativeCurrency: { name: 'KardiaChain', symbol: 'KAI', decimals: 18 },
    blockExplorer: '',
    icon: 'kardiachain.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 25,
    name: 'Cronos Mainnet',
    shortName: 'cro',
    rpcUrls: ['https://evm.cronos.org', 'https://cronos-evm-rpc.publicnode.com', 'wss://cronos-evm-rpc.publicnode.com', 'https://cronos.drpc.org', 'wss://cronos.drpc.org'],
    nativeCurrency: { name: 'Cronos', symbol: 'CRO', decimals: 18 },
    blockExplorer: 'https://explorer.cronos.org',
    icon: 'cronos.org',
    testnet: false,
    category: 'sidechain' as const,
  },
  {
    id: 26,
    name: 'Genesis L1 testnet',
    shortName: 'L1test',
    rpcUrls: ['https://testrpc.genesisl1.org'],
    nativeCurrency: { name: 'L1 testcoin', symbol: 'L1test', decimals: 18 },
    blockExplorer: 'https://testnet.genesisl1.org',
    icon: 'www.genesisl1.com',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 27,
    name: 'ShibaChain',
    shortName: 'shib',
    rpcUrls: ['https://rpc.shibchain.org'],
    nativeCurrency: { name: 'SHIBA INU COIN', symbol: 'SHIB', decimals: 18 },
    blockExplorer: 'https://exp.shibchain.org',
    icon: 'shibchain.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 29,
    name: 'Genesis L1',
    shortName: 'L1',
    rpcUrls: ['https://rpc.genesisl1.org'],
    nativeCurrency: { name: 'L1 coin', symbol: 'L1', decimals: 18 },
    blockExplorer: 'https://explorer.genesisl1.org',
    icon: 'www.genesisl1.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 30,
    name: 'Rootstock Mainnet',
    shortName: 'rsk',
    rpcUrls: ['https://public-node.rsk.co', 'https://mycrypto.rsk.co'],
    nativeCurrency: { name: 'Smart Bitcoin', symbol: 'RBTC', decimals: 18 },
    blockExplorer: 'https://explorer.rsk.co',
    icon: 'rootstock.io',
    testnet: false,
    category: 'sidechain' as const,
  },
  {
    id: 31,
    name: 'Rootstock Testnet',
    shortName: 'trsk',
    rpcUrls: ['https://public-node.testnet.rsk.co', 'https://mycrypto.testnet.rsk.co'],
    nativeCurrency: { name: 'Testnet Smart Bitcoin', symbol: 'tRBTC', decimals: 18 },
    blockExplorer: 'https://explorer.testnet.rsk.co',
    icon: 'rootstock.io',
    testnet: false,
    category: 'sidechain' as const,
  },
  {
    id: 32,
    name: 'GoodData Testnet',
    shortName: 'GooDT',
    rpcUrls: ['https://test2.goodata.io'],
    nativeCurrency: { name: 'GoodData Testnet Ether', symbol: 'GooD', decimals: 18 },
    blockExplorer: '',
    icon: 'www.goodata.org',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 33,
    name: 'GoodData Mainnet',
    shortName: 'GooD',
    rpcUrls: ['https://rpc.goodata.io'],
    nativeCurrency: { name: 'GoodData Mainnet Ether', symbol: 'GooD', decimals: 18 },
    blockExplorer: '',
    icon: 'www.goodata.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 34,
    name: 'SecureChain Mainnet',
    shortName: 'scai',
    rpcUrls: ['https://mainnet-rpc.scai.network'],
    nativeCurrency: { name: 'SecureChain', symbol: 'SCAI', decimals: 18 },
    blockExplorer: 'https://explorer.securechain.ai',
    icon: 'securechain.ai',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 35,
    name: 'TBWG Chain',
    shortName: 'tbwg',
    rpcUrls: ['https://rpc.tbwg.io'],
    nativeCurrency: { name: 'TBWG Ether', symbol: 'TBG', decimals: 18 },
    blockExplorer: '',
    icon: 'tbwg.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 36,
    name: 'Dxchain Mainnet',
    shortName: 'dx',
    rpcUrls: ['https://mainnet.dxchain.com'],
    nativeCurrency: { name: 'Dxchain', symbol: 'DX', decimals: 18 },
    blockExplorer: 'https://dxscan.io',
    icon: 'www.dxchain.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 37,
    name: 'CONX Chain',
    shortName: 'conx',
    rpcUrls: ['https://dimension-evm-rpc.xpla.dev'],
    nativeCurrency: { name: 'XPLA', symbol: 'XPLA', decimals: 18 },
    blockExplorer: 'https://explorer.conx.xyz/mainnet',
    icon: 'conx.xyz',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 38,
    name: 'Valorbit',
    shortName: 'val',
    rpcUrls: ['https://rpc.valorbit.com/v2'],
    nativeCurrency: { name: 'Valorbit', symbol: 'VAL', decimals: 18 },
    blockExplorer: '',
    icon: 'valorbit.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 39,
    name: 'U2U Solaris Mainnet',
    shortName: 'u2u',
    rpcUrls: ['https://rpc-mainnet.u2u.xyz'],
    nativeCurrency: { name: 'U2U Network', symbol: 'U2U', decimals: 18 },
    blockExplorer: 'https://u2uscan.xyz',
    icon: 'u2u.xyz',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 40,
    name: 'Telos EVM Mainnet',
    shortName: 'TelosEVM',
    rpcUrls: ['https://rpc.telos.net', 'https://telos.drpc.org', 'wss://telos.drpc.org'],
    nativeCurrency: { name: 'Telos', symbol: 'TLOS', decimals: 18 },
    blockExplorer: 'https://teloscan.io',
    icon: 'telos.net',
    testnet: false,
    category: 'sidechain' as const,
  },
  {
    id: 41,
    name: 'Telos EVM Testnet',
    shortName: 'TelosEVMTestnet',
    rpcUrls: ['https://rpc.testnet.telos.net', 'https://telos-testnet.drpc.org', 'wss://telos-testnet.drpc.org'],
    nativeCurrency: { name: 'Telos', symbol: 'TLOS', decimals: 18 },
    blockExplorer: 'https://testnet.teloscan.io',
    icon: 'telos.net',
    testnet: false,
    category: 'sidechain' as const,
  },
  {
    id: 42,
    name: 'LUKSO Mainnet',
    shortName: 'lukso',
    rpcUrls: ['https://42.rpc.thirdweb.com', 'https://rpc.lukso.sigmacore.io', 'https://rpc.mainnet.lukso.network', 'wss://ws-rpc.mainnet.lukso.network'],
    nativeCurrency: { name: 'LUKSO', symbol: 'LYX', decimals: 18 },
    blockExplorer: 'https://explorer.lukso.network',
    icon: 'lukso.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 43,
    name: 'Darwinia Pangolin Testnet',
    shortName: 'pangolin',
    rpcUrls: ['https://pangolin-rpc.darwinia.network'],
    nativeCurrency: { name: 'Pangolin Network Native Token', symbol: 'PRING', decimals: 18 },
    blockExplorer: 'https://pangolin.subscan.io',
    icon: 'darwinia.network',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 44,
    name: 'Crab Network',
    shortName: 'crab',
    rpcUrls: ['https://crab-rpc.darwinia.network', 'https://crab-rpc.dcdao.box'],
    nativeCurrency: { name: 'Crab Network Native Token', symbol: 'CRAB', decimals: 18 },
    blockExplorer: 'https://crab-scan.darwinia.network',
    icon: 'crab.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 45,
    name: 'Darwinia Pangoro Testnet',
    shortName: 'pangoro',
    rpcUrls: ['https://pangoro-rpc.darwinia.network'],
    nativeCurrency: { name: 'Pangoro Network Native Token', symbol: 'ORING', decimals: 18 },
    blockExplorer: 'https://pangoro.subscan.io',
    icon: 'darwinia.network',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 46,
    name: 'Darwinia Network',
    shortName: 'darwinia',
    rpcUrls: ['https://rpc.darwinia.network', 'https://darwinia-rpc.dcdao.box', 'https://darwinia-rpc.dwellir.com', 'https://darwinia.rpc.subquery.network/public'],
    nativeCurrency: { name: 'Darwinia Network Native Token', symbol: 'RING', decimals: 18 },
    blockExplorer: 'https://explorer.darwinia.network',
    icon: 'darwinia.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 47,
    name: 'Acria IntelliChain',
    shortName: 'aic',
    rpcUrls: ['https://aic.acria.ai'],
    nativeCurrency: { name: 'ACRIA', symbol: 'ACRIA', decimals: 18 },
    blockExplorer: 'https://explorer.acria.ai',
    icon: 'acria.ai',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 48,
    name: 'Ennothem Mainnet Proterozoic',
    shortName: 'etmp',
    rpcUrls: ['https://rpc.etm.network'],
    nativeCurrency: { name: 'Ennothem', symbol: 'ETMP', decimals: 18 },
    blockExplorer: 'https://etmscan.network',
    icon: 'etm.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 49,
    name: 'Ennothem Testnet Pioneer',
    shortName: 'etmpTest',
    rpcUrls: ['https://rpc.pioneer.etm.network'],
    nativeCurrency: { name: 'Ennothem', symbol: 'ETMP', decimals: 18 },
    blockExplorer: 'https://pioneer.etmscan.network',
    icon: 'etm.network',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 50,
    name: 'XDC Network',
    shortName: 'xdc',
    rpcUrls: ['https://erpc.xinfin.network', 'https://rpc.xinfin.network', 'https://rpc1.xinfin.network', 'https://rpc.xdcrpc.com', 'https://erpc.xdcrpc.com'],
    nativeCurrency: { name: 'XinFin', symbol: 'XDC', decimals: 18 },
    blockExplorer: 'https://xdcscan.com',
    icon: 'xinfin.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 51,
    name: 'XDC Apothem Network',
    shortName: 'txdc',
    rpcUrls: ['https://rpc.apothem.network', 'https://erpc.apothem.network', 'https://apothem.xdcrpc.com'],
    nativeCurrency: { name: 'XinFin', symbol: 'TXDC', decimals: 18 },
    blockExplorer: 'https://testnet.xdcscan.com',
    icon: 'xinfin.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 52,
    name: 'CoinEx Smart Chain Mainnet',
    shortName: 'cet',
    rpcUrls: ['https://rpc.coinex.net'],
    nativeCurrency: { name: 'CoinEx Chain Native Token', symbol: 'cet', decimals: 18 },
    blockExplorer: 'https://www.coinex.net',
    icon: 'www.coinex.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 53,
    name: 'CoinEx Smart Chain Testnet',
    shortName: 'tcet',
    rpcUrls: ['https://testnet-rpc.coinex.net/'],
    nativeCurrency: { name: 'CoinEx Chain Test Native Token', symbol: 'cett', decimals: 18 },
    blockExplorer: 'https://testnet.coinex.net',
    icon: 'www.coinex.org',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 54,
    name: 'Openpiece Mainnet',
    shortName: 'OP',
    rpcUrls: ['https://mainnet.openpiece.io'],
    nativeCurrency: { name: 'Belly', symbol: 'BELLY', decimals: 18 },
    blockExplorer: 'https://bellyscan.com',
    icon: 'cryptopiece.online',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 55,
    name: 'Zyx Mainnet',
    shortName: 'ZYX',
    rpcUrls: ['https://rpc-1.zyx.network/', 'https://rpc-2.zyx.network/', 'https://rpc-3.zyx.network/', 'https://rpc-4.zyx.network/', 'https://rpc-5.zyx.network/'],
    nativeCurrency: { name: 'Zyx', symbol: 'ZYX', decimals: 18 },
    blockExplorer: 'https://zyxscan.com',
    icon: 'zyx.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 56,
    name: 'BNB Smart Chain Mainnet',
    shortName: 'bnb',
    rpcUrls: ['https://bsc-dataseed1.bnbchain.org', 'https://bsc-dataseed2.bnbchain.org', 'https://bsc-dataseed3.bnbchain.org', 'https://bsc-dataseed4.bnbchain.org', 'https://bsc-dataseed1.defibit.io'],
    nativeCurrency: { name: 'BNB Chain Native Token', symbol: 'BNB', decimals: 18 },
    blockExplorer: 'https://bscscan.com',
    icon: 'www.bnbchain.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 57,
    name: 'Syscoin Mainnet',
    shortName: 'sys',
    rpcUrls: ['https://rpc.syscoin.org', 'https://syscoin.public-rpc.com', 'https://57.rpc.thirdweb.com', 'wss://rpc.syscoin.org/wss', 'https://syscoin-evm.publicnode.com'],
    nativeCurrency: { name: 'Syscoin', symbol: 'SYS', decimals: 18 },
    blockExplorer: 'https://explorer.syscoin.org',
    icon: 'www.syscoin.org',
    testnet: false,
    category: 'sidechain' as const,
  },
  {
    id: 58,
    name: 'Ontology Mainnet',
    shortName: 'OntologyMainnet',
    rpcUrls: ['http://dappnode1.ont.io:20339', 'http://dappnode2.ont.io:20339', 'http://dappnode3.ont.io:20339', 'http://dappnode4.ont.io:20339', 'https://dappnode1.ont.io:10339'],
    nativeCurrency: { name: 'ONG', symbol: 'ONG', decimals: 18 },
    blockExplorer: 'https://explorer.ont.io',
    icon: 'ont.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 60,
    name: 'GoChain',
    shortName: 'go',
    rpcUrls: ['https://rpc.gochain.io'],
    nativeCurrency: { name: 'GoChain Ether', symbol: 'GO', decimals: 18 },
    blockExplorer: 'https://explorer.gochain.io',
    icon: 'gochain.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 61,
    name: 'Ethereum Classic',
    shortName: 'etc',
    rpcUrls: ['https://etc.rivet.link', 'https://besu-at.etc-network.info', 'https://geth-at.etc-network.info', 'https://etc.etcdesktop.com', 'https://etc.mytokenpocket.vip'],
    nativeCurrency: { name: 'Ether', symbol: 'ETC', decimals: 18 },
    blockExplorer: 'https://etc.blockscout.com',
    icon: 'ethereumclassic.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 63,
    name: 'Mordor Testnet',
    shortName: 'metc',
    rpcUrls: ['https://rpc.mordor.etccooperative.org', 'https://geth-mordor.etc-network.info'],
    nativeCurrency: { name: 'Mordor Ether', symbol: 'METC', decimals: 18 },
    blockExplorer: 'https://etc-mordor.blockscout.com',
    icon: 'ethereumclassic.org',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 64,
    name: 'Ellaism',
    shortName: 'ellaism',
    rpcUrls: ['https://jsonrpc.ellaism.org'],
    nativeCurrency: { name: 'Ellaism Ether', symbol: 'ELLA', decimals: 18 },
    blockExplorer: '',
    icon: 'ellaism.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 65,
    name: 'OKExChain Testnet',
    shortName: 'tokt',
    rpcUrls: ['https://exchaintestrpc.okex.org'],
    nativeCurrency: { name: 'OKExChain Global Utility Token in testnet', symbol: 'OKT', decimals: 18 },
    blockExplorer: 'https://www.oklink.com/okexchain-test',
    icon: 'www.okex.com',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 66,
    name: 'OKXChain Mainnet',
    shortName: 'okt',
    rpcUrls: ['https://exchainrpc.okex.org', 'https://okc-mainnet.gateway.pokt.network/v1/lb/6275309bea1b320039c893ff'],
    nativeCurrency: { name: 'OKXChain Global Utility Token', symbol: 'OKT', decimals: 18 },
    blockExplorer: 'https://www.oklink.com/en/okc',
    icon: 'www.okex.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 67,
    name: 'DBChain Testnet',
    shortName: 'dbm',
    rpcUrls: ['http://test-rpc.dbmbp.com'],
    nativeCurrency: { name: 'DBChain Testnet', symbol: 'DBM', decimals: 18 },
    blockExplorer: '',
    icon: 'test.dbmbp.com',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 68,
    name: 'SoterOne Mainnet',
    shortName: 'SO1',
    rpcUrls: ['https://rpc.soter.one'],
    nativeCurrency: { name: 'SoterOne Mainnet Ether', symbol: 'SOTER', decimals: 18 },
    blockExplorer: '',
    icon: 'www.soterone.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 69,
    name: 'Optimism Kovan',
    shortName: 'okov',
    rpcUrls: ['https://kovan.optimism.io/'],
    nativeCurrency: { name: 'Kovan Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://kovan-optimistic.etherscan.io',
    icon: 'optimism.io',
    testnet: false,
    category: 'l2' as const,
  },
  {
    id: 70,
    name: 'Hoo Smart Chain',
    shortName: 'hsc',
    rpcUrls: ['https://http-mainnet.hoosmartchain.com', 'https://http-mainnet2.hoosmartchain.com', 'wss://ws-mainnet.hoosmartchain.com', 'wss://ws-mainnet2.hoosmartchain.com'],
    nativeCurrency: { name: 'Hoo Smart Chain Native Token', symbol: 'HOO', decimals: 18 },
    blockExplorer: 'https://www.hooscan.com',
    icon: 'www.hoosmartchain.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 71,
    name: 'Conflux eSpace (Testnet)',
    shortName: 'cfxtest',
    rpcUrls: ['https://evmtestnet.confluxrpc.com'],
    nativeCurrency: { name: 'CFX', symbol: 'CFX', decimals: 18 },
    blockExplorer: 'https://evmtestnet.confluxscan.net',
    icon: 'confluxnetwork.org',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 72,
    name: 'DxChain Testnet',
    shortName: 'dxc',
    rpcUrls: ['https://testnet-http.dxchain.com'],
    nativeCurrency: { name: 'DxChain Testnet', symbol: 'DX', decimals: 18 },
    blockExplorer: '',
    icon: 'testnet.dxscan.io',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 73,
    name: 'FNCY',
    shortName: 'FNCY',
    rpcUrls: ['https://fncy-seed1.fncy.world'],
    nativeCurrency: { name: 'FNCY', symbol: 'FNCY', decimals: 18 },
    blockExplorer: 'https://fncyscan.fncy.world',
    icon: 'fncyscan.fncy.world',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 74,
    name: 'IDChain Mainnet',
    shortName: 'idchain',
    rpcUrls: ['https://idchain.one/rpc/', 'wss://idchain.one/ws/'],
    nativeCurrency: { name: 'EIDI', symbol: 'EIDI', decimals: 18 },
    blockExplorer: 'https://explorer.idchain.one',
    icon: 'idchain.one',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 75,
    name: 'Decimal Smart Chain Mainnet',
    shortName: 'DSC',
    rpcUrls: ['https://node.decimalchain.com/web3/', 'https://node1-mainnet.decimalchain.com/web3/', 'https://node2-mainnet.decimalchain.com/web3/', 'https://node3-mainnet.decimalchain.com/web3/', 'https://node4-mainnet.decimalchain.com/web3/'],
    nativeCurrency: { name: 'Decimal', symbol: 'DEL', decimals: 18 },
    blockExplorer: 'https://explorer.decimalchain.com',
    icon: 'decimalchain.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 76,
    name: 'Mix',
    shortName: 'mix',
    rpcUrls: ['https://rpc2.mix-blockchain.org:8647'],
    nativeCurrency: { name: 'Mix Ether', symbol: 'MIX', decimals: 18 },
    blockExplorer: '',
    icon: 'mix-blockchain.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 77,
    name: 'POA Network Sokol',
    shortName: 'spoa',
    rpcUrls: ['https://sokol.poa.network', 'wss://sokol.poa.network/wss', 'ws://sokol.poa.network:8546'],
    nativeCurrency: { name: 'POA Sokol Ether', symbol: 'SPOA', decimals: 18 },
    blockExplorer: 'https://blockscout.com/poa/sokol',
    icon: 'poa.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 78,
    name: 'PrimusChain mainnet',
    shortName: 'primuschain',
    rpcUrls: ['https://ethnode.primusmoney.com/mainnet'],
    nativeCurrency: { name: 'Primus Ether', symbol: 'PETH', decimals: 18 },
    blockExplorer: '',
    icon: 'primusmoney.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 79,
    name: 'Zenith Mainnet',
    shortName: 'zenith',
    rpcUrls: ['https://dataserver-us-1.zenithchain.co/', 'https://dataserver-asia-3.zenithchain.co/', 'https://dataserver-asia-4.zenithchain.co/', 'https://dataserver-asia-2.zenithchain.co/', 'https://dataserver-asia-5.zenithchain.co/'],
    nativeCurrency: { name: 'ZENITH', symbol: 'ZENITH', decimals: 18 },
    blockExplorer: 'https://scan.zenithchain.co',
    icon: 'www.zenithchain.co',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 80,
    name: 'GeneChain',
    shortName: 'GeneChain',
    rpcUrls: ['https://rpc.genechain.io'],
    nativeCurrency: { name: 'RNA', symbol: 'RNA', decimals: 18 },
    blockExplorer: 'https://scan.genechain.io',
    icon: 'scan.genechain.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 81,
    name: 'Japan Open Chain Mainnet',
    shortName: 'joc',
    rpcUrls: ['https://rpc-1.japanopenchain.org:8545', 'https://rpc-2.japanopenchain.org:8545', 'https://rpc-3.japanopenchain.org'],
    nativeCurrency: { name: 'Japan Open Chain Token', symbol: 'JOC', decimals: 18 },
    blockExplorer: 'https://explorer.japanopenchain.org',
    icon: 'www.japanopenchain.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 82,
    name: 'Meter Mainnet',
    shortName: 'Meter',
    rpcUrls: ['https://rpc.meter.io'],
    nativeCurrency: { name: 'Meter', symbol: 'MTR', decimals: 18 },
    blockExplorer: 'https://scan.meter.io',
    icon: 'www.meter.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 83,
    name: 'Meter Testnet',
    shortName: 'MeterTest',
    rpcUrls: ['https://rpctest.meter.io'],
    nativeCurrency: { name: 'Meter', symbol: 'MTR', decimals: 18 },
    blockExplorer: 'https://scan-warringstakes.meter.io',
    icon: 'www.meter.io',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 84,
    name: 'Linqto Devnet',
    shortName: 'linqto-devnet',
    rpcUrls: ['https://linqto-dev.com'],
    nativeCurrency: { name: 'XRP', symbol: 'XRP', decimals: 18 },
    blockExplorer: 'https://explorer.linqto-dev.com',
    icon: 'linqto.com',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 85,
    name: 'GateChain Testnet',
    shortName: 'gttest',
    rpcUrls: ['https://testnet.gatenode.cc'],
    nativeCurrency: { name: 'GateToken', symbol: 'GT', decimals: 18 },
    blockExplorer: 'https://www.gatescan.org/testnet',
    icon: 'www.gatechain.io',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 86,
    name: 'GateChain Mainnet',
    shortName: 'gt',
    rpcUrls: ['https://evm.gatenode.cc'],
    nativeCurrency: { name: 'GateToken', symbol: 'GT', decimals: 18 },
    blockExplorer: 'https://www.gatescan.org',
    icon: 'www.gatechain.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 87,
    name: 'Nova Network',
    shortName: 'nnw',
    rpcUrls: ['https://connect.novanetwork.io', 'https://0x57.redjackstudio.com', 'https://rpc.novanetwork.io:9070'],
    nativeCurrency: { name: 'Supernova', symbol: 'SNT', decimals: 18 },
    blockExplorer: 'https://explorer.novanetwork.io',
    icon: 'novanetwork.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 88,
    name: 'Viction',
    shortName: 'vic',
    rpcUrls: ['https://rpc.viction.xyz'],
    nativeCurrency: { name: 'Viction', symbol: 'VIC', decimals: 18 },
    blockExplorer: '',
    icon: 'viction.xyz',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 89,
    name: 'Viction Testnet',
    shortName: 'vict',
    rpcUrls: ['https://rpc-testnet.viction.xyz'],
    nativeCurrency: { name: 'Viction', symbol: 'VIC', decimals: 18 },
    blockExplorer: '',
    icon: 'viction.xyz',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 90,
    name: 'Garizon Stage0',
    shortName: 'gar-s0',
    rpcUrls: ['https://s0.garizon.net/rpc'],
    nativeCurrency: { name: 'Garizon', symbol: 'GAR', decimals: 18 },
    blockExplorer: 'https://explorer.garizon.com',
    icon: 'garizon.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 91,
    name: 'Garizon Stage1',
    shortName: 'gar-s1',
    rpcUrls: ['https://s1.garizon.net/rpc'],
    nativeCurrency: { name: 'Garizon', symbol: 'GAR', decimals: 18 },
    blockExplorer: 'https://explorer.garizon.com',
    icon: 'garizon.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 92,
    name: 'Garizon Stage2',
    shortName: 'gar-s2',
    rpcUrls: ['https://s2.garizon.net/rpc'],
    nativeCurrency: { name: 'Garizon', symbol: 'GAR', decimals: 18 },
    blockExplorer: 'https://explorer.garizon.com',
    icon: 'garizon.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 93,
    name: 'Garizon Stage3',
    shortName: 'gar-s3',
    rpcUrls: ['https://s3.garizon.net/rpc'],
    nativeCurrency: { name: 'Garizon', symbol: 'GAR', decimals: 18 },
    blockExplorer: 'https://explorer.garizon.com',
    icon: 'garizon.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 94,
    name: 'SwissDLT',
    shortName: 'sdlt',
    rpcUrls: ['https://rpc.swissdlt.ch'],
    nativeCurrency: { name: 'BCTS', symbol: 'BCTS', decimals: 18 },
    blockExplorer: 'https://explorer.swissdlt.ch',
    icon: 'bcts.ch',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 95,
    name: 'CamDL Mainnet',
    shortName: 'camdl',
    rpcUrls: ['https://rpc1.camdl.gov.kh/'],
    nativeCurrency: { name: 'CADL', symbol: 'CADL', decimals: 18 },
    blockExplorer: 'https://explorer.camdl.gov.kh',
    icon: 'camdl.gov.kh',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 96,
    name: 'KUB Mainnet',
    shortName: 'kub',
    rpcUrls: ['https://rpc.bitkubchain.io', 'wss://wss.bitkubchain.io'],
    nativeCurrency: { name: 'KUB Coin', symbol: 'KUB', decimals: 18 },
    blockExplorer: 'https://kubscan.com',
    icon: 'www.kubchain.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 97,
    name: 'BNB Smart Chain Testnet',
    shortName: 'bnbt',
    rpcUrls: ['https://data-seed-prebsc-1-s1.bnbchain.org:8545', 'https://data-seed-prebsc-2-s1.bnbchain.org:8545', 'https://data-seed-prebsc-1-s2.bnbchain.org:8545', 'https://data-seed-prebsc-2-s2.bnbchain.org:8545', 'https://data-seed-prebsc-1-s3.bnbchain.org:8545'],
    nativeCurrency: { name: 'BNB Chain Native Token', symbol: 'tBNB', decimals: 18 },
    blockExplorer: 'https://testnet.bscscan.com',
    icon: 'www.bnbchain.org',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 98,
    name: 'Six Protocol',
    shortName: 'six',
    rpcUrls: ['https://sixnet-rpc-evm.sixprotocol.net'],
    nativeCurrency: { name: 'SIX evm token', symbol: 'SIX', decimals: 18 },
    blockExplorer: 'https://sixscan.io/sixnet',
    icon: 'six.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 99,
    name: 'POA Network Core',
    shortName: 'poa',
    rpcUrls: ['https://core.poa.network'],
    nativeCurrency: { name: 'POA Network Core Ether', symbol: 'POA', decimals: 18 },
    blockExplorer: 'https://blockscout.com/poa/core',
    icon: 'poa.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 100,
    name: 'Gnosis',
    shortName: 'gno',
    rpcUrls: ['https://rpc.gnosischain.com', 'https://rpc.gnosis.gateway.fm', 'https://rpc.ankr.com/gnosis', 'https://gnosischain-rpc.gateway.pokt.network', 'https://gnosis-mainnet.public.blastapi.io'],
    nativeCurrency: { name: 'xDAI', symbol: 'XDAI', decimals: 18 },
    blockExplorer: 'https://gnosisscan.io',
    icon: 'docs.gnosischain.com',
    testnet: false,
    category: 'sidechain' as const,
  },
  {
    id: 101,
    name: 'EtherInc',
    shortName: 'eti',
    rpcUrls: ['https://api.einc.io/jsonrpc/mainnet'],
    nativeCurrency: { name: 'EtherInc Ether', symbol: 'ETI', decimals: 18 },
    blockExplorer: '',
    icon: 'einc.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 102,
    name: 'Web3Games Testnet',
    shortName: 'tw3g',
    rpcUrls: ['https://testnet-rpc-0.web3games.org/evm', 'https://testnet-rpc-1.web3games.org/evm', 'https://testnet-rpc-2.web3games.org/evm'],
    nativeCurrency: { name: 'Web3Games', symbol: 'W3G', decimals: 18 },
    blockExplorer: '',
    icon: 'web3games.org',
    testnet: false,
    category: 'gaming' as const,
  },
  {
    id: 103,
    name: 'WorldLand Mainnet',
    shortName: 'WLC',
    rpcUrls: ['https://seoul.worldland.foundation', 'https://seoul2.worldland.foundation'],
    nativeCurrency: { name: 'Worldland', symbol: 'WLC', decimals: 18 },
    blockExplorer: 'https://scan.worldland.foundation',
    icon: 'worldland.foundation',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 104,
    name: 'Kaiba Lightning Chain Testnet',
    shortName: 'tklc',
    rpcUrls: ['https://klc.live/'],
    nativeCurrency: { name: 'Kaiba Testnet Token', symbol: 'tKAIBA', decimals: 18 },
    blockExplorer: 'https://kaibascan.io',
    icon: 'kaibadefi.com',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 105,
    name: 'Web3Games Devnet',
    shortName: 'dw3g',
    rpcUrls: ['https://devnet.web3games.org/evm'],
    nativeCurrency: { name: 'Web3Games', symbol: 'W3G', decimals: 18 },
    blockExplorer: 'https://explorer-devnet.web3games.org',
    icon: 'web3games.org',
    testnet: false,
    category: 'gaming' as const,
  },
  {
    id: 106,
    name: 'Velas EVM Mainnet',
    shortName: 'vlx',
    rpcUrls: ['https://evmexplorer.velas.com/rpc', 'https://explorer.velas.com/rpc'],
    nativeCurrency: { name: 'Velas', symbol: 'VLX', decimals: 18 },
    blockExplorer: 'https://evmexplorer.velas.com',
    icon: 'velas.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 107,
    name: 'Nebula Testnet',
    shortName: 'ntn',
    rpcUrls: ['https://testnet.rpc.novanetwork.io'],
    nativeCurrency: { name: 'Nebula X', symbol: 'NBX', decimals: 18 },
    blockExplorer: 'https://explorer.novanetwork.io',
    icon: 'novanetwork.io',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 108,
    name: 'ThunderCore Mainnet',
    shortName: 'TT',
    rpcUrls: ['https://mainnet-rpc.thundercore.com', 'https://mainnet-rpc.thundertoken.net', 'https://mainnet-rpc.thundercore.io'],
    nativeCurrency: { name: 'ThunderCore Token', symbol: 'TT', decimals: 18 },
    blockExplorer: 'https://viewblock.io/thundercore',
    icon: 'thundercore.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 109,
    name: 'Shibarium',
    shortName: 'shibariumecosystem',
    rpcUrls: ['https://rpc.shibrpc.com', 'https://shib.nownodes.io'],
    nativeCurrency: { name: 'BONE Shibarium', symbol: 'BONE', decimals: 18 },
    blockExplorer: 'https://www.shibariumscan.io',
    icon: 'shibariumecosystem.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 110,
    name: 'Proton Testnet',
    shortName: 'xpr',
    rpcUrls: ['https://protontestnet.greymass.com/'],
    nativeCurrency: { name: 'Proton', symbol: 'XPR', decimals: 4 },
    blockExplorer: '',
    icon: 'protonchain.com',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 111,
    name: 'EtherLite Chain',
    shortName: 'ETL',
    rpcUrls: ['https://rpc.etherlite.org'],
    nativeCurrency: { name: 'EtherLite', symbol: 'ETL', decimals: 18 },
    blockExplorer: '',
    icon: 'etherlite.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 112,
    name: 'Coinbit Mainnet',
    shortName: 'coinbit',
    rpcUrls: ['https://coinbit-rpc-mainnet.chain.sbcrypto.app'],
    nativeCurrency: { name: 'Gas IDR', symbol: 'GIDR', decimals: 18 },
    blockExplorer: 'https://coinbit-explorer.chain.sbcrypto.app',
    icon: 'crypto.stockbit.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 113,
    name: 'Dehvo',
    shortName: 'deh',
    rpcUrls: ['https://connect.dehvo.com', 'https://rpc.dehvo.com', 'https://rpc1.dehvo.com', 'https://rpc2.dehvo.com'],
    nativeCurrency: { name: 'Dehvo', symbol: 'Deh', decimals: 18 },
    blockExplorer: 'https://explorer.dehvo.com',
    icon: 'dehvo.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 114,
    name: 'Flare Testnet Coston2',
    shortName: 'c2flr',
    rpcUrls: ['https://coston2-api.flare.network/ext/C/rpc', 'https://flare-testnet-coston2.rpc.thirdweb.com', 'https://flaretestnet-bundler.etherspot.io', 'https://01-gravelines-005-01.rpc.tatum.io/ext/bc/C/rpc', 'https://02-chicago-005-02.rpc.tatum.io/ext/bc/C/rpc'],
    nativeCurrency: { name: 'Coston2 Flare', symbol: 'C2FLR', decimals: 18 },
    blockExplorer: 'https://coston2-explorer.flare.network',
    icon: 'flare.network',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 117,
    name: 'Uptick Mainnet',
    shortName: 'auptick',
    rpcUrls: ['https://json-rpc.uptick.network'],
    nativeCurrency: { name: 'Uptick', symbol: 'UPTICK', decimals: 18 },
    blockExplorer: 'https://evm-explorer.uptick.network',
    icon: 'www.uptick.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 118,
    name: 'Arcology Testnet',
    shortName: 'arcology',
    rpcUrls: ['https://testnet.arcology.network/rpc'],
    nativeCurrency: { name: 'Arcology Coin', symbol: 'Acol', decimals: 18 },
    blockExplorer: 'https://testnet.arcology.network/explorer',
    icon: 'arcology.network',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 119,
    name: 'ENULS Mainnet',
    shortName: 'enuls',
    rpcUrls: ['https://evmapi.nuls.io', 'https://evmapi2.nuls.io'],
    nativeCurrency: { name: 'NULS', symbol: 'NULS', decimals: 18 },
    blockExplorer: 'https://evmscan.nuls.io',
    icon: 'nuls.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 120,
    name: 'ENULS Testnet',
    shortName: 'enulst',
    rpcUrls: ['https://beta.evmapi.nuls.io', 'https://beta.evmapi2.nuls.io'],
    nativeCurrency: { name: 'NULS', symbol: 'NULS', decimals: 18 },
    blockExplorer: 'https://beta.evmscan.nuls.io',
    icon: 'nuls.io',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 121,
    name: 'Realchain Mainnet',
    shortName: 'REAL',
    rpcUrls: ['https://rcl-dataseed1.rclsidechain.com', 'https://rcl-dataseed2.rclsidechain.com', 'https://rcl-dataseed3.rclsidechain.com', 'https://rcl-dataseed4.rclsidechain.com', 'wss://rcl-dataseed1.rclsidechain.com/v1/'],
    nativeCurrency: { name: 'Realchain', symbol: 'REAL', decimals: 18 },
    blockExplorer: 'https://rclscan.com',
    icon: 'www.rclsidechain.com',
    testnet: false,
    category: 'defi' as const,
  },
  {
    id: 122,
    name: 'Fuse Mainnet',
    shortName: 'fuse',
    rpcUrls: ['https://rpc.fuse.io', 'https://fuse.drpc.org', 'wss://fuse.drpc.org'],
    nativeCurrency: { name: 'Fuse', symbol: 'FUSE', decimals: 18 },
    blockExplorer: 'https://explorer.fuse.io',
    icon: 'fuse.io',
    testnet: false,
    category: 'sidechain' as const,
  },
  {
    id: 123,
    name: 'Fuse Sparknet',
    shortName: 'spark',
    rpcUrls: ['https://rpc.fusespark.io'],
    nativeCurrency: { name: 'Spark', symbol: 'SPARK', decimals: 18 },
    blockExplorer: '',
    icon: 'docs.fuse.io',
    testnet: false,
    category: 'sidechain' as const,
  },
  {
    id: 124,
    name: 'Decentralized Web Mainnet',
    shortName: 'dwu',
    rpcUrls: ['https://decentralized-web.tech/dw_rpc.php'],
    nativeCurrency: { name: 'Decentralized Web Utility', symbol: 'DWU', decimals: 18 },
    blockExplorer: '',
    icon: 'decentralized-web.tech',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 125,
    name: 'OYchain Testnet',
    shortName: 'OYchainTestnet',
    rpcUrls: ['https://rpc.testnet.oychain.io'],
    nativeCurrency: { name: 'OYchain Token', symbol: 'OY', decimals: 18 },
    blockExplorer: 'https://explorer.testnet.oychain.io',
    icon: 'www.oychain.io',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 126,
    name: 'OYchain Mainnet',
    shortName: 'OYchainMainnet',
    rpcUrls: ['https://rpc.mainnet.oychain.io'],
    nativeCurrency: { name: 'OYchain Token', symbol: 'OY', decimals: 18 },
    blockExplorer: 'https://explorer.oychain.io',
    icon: 'www.oychain.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 128,
    name: 'Huobi ECO Chain Mainnet',
    shortName: 'heco',
    rpcUrls: ['https://http-mainnet.hecochain.com', 'wss://ws-mainnet.hecochain.com'],
    nativeCurrency: { name: 'Huobi ECO Chain Native Token', symbol: 'HT', decimals: 18 },
    blockExplorer: 'https://hecoinfo.com',
    icon: 'www.hecochain.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 129,
    name: 'Innovator Chain',
    shortName: 'Innovator',
    rpcUrls: ['https://rpc.innovatorchain.com'],
    nativeCurrency: { name: 'INOV8', symbol: 'INOV8', decimals: 18 },
    blockExplorer: 'https://evm.innovatorchain.com',
    icon: 'innovatorchain.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 130,
    name: 'Unichain',
    shortName: 'unichain',
    rpcUrls: ['https://mainnet.unichain.org', 'https://unichain-rpc.publicnode.com', 'wss://unichain-rpc.publicnode.com'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://uniscan.xyz',
    icon: 'unichain.org',
    testnet: false,
    category: 'l2' as const,
  },
  {
    id: 131,
    name: 'Engram Testnet',
    shortName: 'tgram',
    rpcUrls: ['https://tokioswift.engram.tech', 'https://tokio-archive.engram.tech'],
    nativeCurrency: { name: 'Engram Tokio Testnet', symbol: 'tGRAM', decimals: 18 },
    blockExplorer: 'https://tokioscan-v2.engram.tech',
    icon: 'engramnet.io',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 132,
    name: 'Namefi Chain Mainnet',
    shortName: 'nfic',
    rpcUrls: ['https://rpc.chain.namefi.io'],
    nativeCurrency: { name: 'Namefi Coin', symbol: 'NFIC', decimals: 18 },
    blockExplorer: '',
    icon: 'namefi.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 133,
    name: 'HashKey Chain Testnet',
    shortName: 'HSKT',
    rpcUrls: ['https://testnet.hsk.xyz'],
    nativeCurrency: { name: 'HashKey EcoPoints', symbol: 'HSK', decimals: 18 },
    blockExplorer: 'https://testnet-explorer.hsk.xyz',
    icon: 'hashkeychain.net',
    testnet: false,
    category: 'l2' as const,
  },
  {
    id: 134,
    name: 'iExec Sidechain',
    shortName: 'rlc',
    rpcUrls: ['https://bellecour.iex.ec'],
    nativeCurrency: { name: 'xRLC', symbol: 'xRLC', decimals: 18 },
    blockExplorer: 'https://blockscout.bellecour.iex.ec',
    icon: 'iex.ec',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 135,
    name: 'Alyx Chain Testnet',
    shortName: 'AlyxTestnet',
    rpcUrls: ['https://testnet-rpc.alyxchain.com'],
    nativeCurrency: { name: 'Alyx Testnet Native Token', symbol: 'ALYX', decimals: 18 },
    blockExplorer: 'https://testnet.alyxscan.com',
    icon: 'www.alyxchain.com',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 136,
    name: 'Deamchain Mainnet',
    shortName: 'deam',
    rpcUrls: ['https://mainnet.deamchain.com'],
    nativeCurrency: { name: 'Deamchain Native Token', symbol: 'DEAM', decimals: 18 },
    blockExplorer: 'https://scan.deamchain.com',
    icon: 'deamchain.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 137,
    name: 'Polygon Mainnet',
    shortName: 'pol',
    rpcUrls: ['https://polygon.drpc.org', 'wss://polygon.drpc.org', 'https://rpc-mainnet.matic.quiknode.pro', 'https://polygon-bor-rpc.publicnode.com', 'wss://polygon-bor-rpc.publicnode.com'],
    nativeCurrency: { name: 'POL', symbol: 'POL', decimals: 18 },
    blockExplorer: 'https://polygonscan.com',
    icon: 'polygon.technology',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 138,
    name: 'Defi Oracle Meta Mainnet',
    shortName: 'dfio-meta-main',
    rpcUrls: ['https://rpc-http-pub.d-bis.org', 'wss://rpc-ws-pub.d-bis.org', 'https://rpc.d-bis.org', 'wss://rpc.d-bis.org', 'https://rpc2.d-bis.org'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.d-bis.org',
    icon: 'd-bis.org',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 139,
    name: 'WoopChain Mainnet',
    shortName: 'woop',
    rpcUrls: ['https://rpc.woop.ai/rpc'],
    nativeCurrency: { name: 'WoopCoin', symbol: 'WOOC', decimals: 18 },
    blockExplorer: 'https://explorer.wikiwoop.com',
    icon: 'wikiwoop.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 140,
    name: 'Eteria Mainnet',
    shortName: 'ERA',
    rpcUrls: ['https://mainnet.eteria.io/v1'],
    nativeCurrency: { name: 'Eteria', symbol: 'ERA', decimals: 18 },
    blockExplorer: 'https://explorer.eteria.io',
    icon: 'eteria.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 141,
    name: 'Openpiece Testnet',
    shortName: 'OPtest',
    rpcUrls: ['https://testnet.openpiece.io'],
    nativeCurrency: { name: 'Belly', symbol: 'BELLY', decimals: 18 },
    blockExplorer: 'https://testnet.bellyscan.com',
    icon: 'cryptopiece.online',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 142,
    name: 'DAX CHAIN',
    shortName: 'dax',
    rpcUrls: ['https://rpc.prodax.io'],
    nativeCurrency: { name: 'Prodax', symbol: 'DAX', decimals: 18 },
    blockExplorer: '',
    icon: 'prodax.io',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 143,
    name: 'Monad',
    shortName: 'mon',
    rpcUrls: ['https://rpc.monad.xyz'],
    nativeCurrency: { name: 'Monad', symbol: 'MON', decimals: 18 },
    blockExplorer: 'https://monadvision.com',
    icon: 'monad.xyz',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 144,
    name: 'PHI Network v2',
    shortName: 'PHI',
    rpcUrls: ['https://connect.phi.network'],
    nativeCurrency: { name: 'PHI', symbol: 'Φ', decimals: 18 },
    blockExplorer: 'https://phiscan.com',
    icon: 'phi.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 145,
    name: 'SoraAI Testnet',
    shortName: 'SETH',
    rpcUrls: ['https://rpc-testnet.soraai.bot'],
    nativeCurrency: { name: 'SoraETH', symbol: 'SETH', decimals: 18 },
    blockExplorer: 'https://explorer.soraai.bot',
    icon: 'soraai.bot',
    testnet: false,
    category: 'l2' as const,
  },
  {
    id: 146,
    name: 'Sonic Mainnet',
    shortName: 'sonic',
    rpcUrls: ['https://rpc.soniclabs.com', 'https://sonic-rpc.publicnode.com', 'wss://sonic-rpc.publicnode.com'],
    nativeCurrency: { name: 'Sonic', symbol: 'S', decimals: 18 },
    blockExplorer: 'https://sonicscan.org',
    icon: 'soniclabs.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 147,
    name: 'Flag Mainnet',
    shortName: 'FLAG',
    rpcUrls: ['https://mainnet-rpc.flagscan.xyz'],
    nativeCurrency: { name: 'Flag', symbol: 'FLAG', decimals: 18 },
    blockExplorer: 'https://flagscan.xyz',
    icon: 'flagscan.xyz',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 148,
    name: 'ShimmerEVM',
    shortName: 'shimmerevm',
    rpcUrls: ['https://json-rpc.evm.shimmer.network'],
    nativeCurrency: { name: 'SMR', symbol: 'SMR', decimals: 18 },
    blockExplorer: 'https://explorer.evm.shimmer.network',
    icon: 'shimmer.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 150,
    name: 'Six Protocol Testnet',
    shortName: 'sixt',
    rpcUrls: ['https://rpc-evm.fivenet.sixprotocol.net'],
    nativeCurrency: { name: 'SIX testnet evm token', symbol: 'tSIX', decimals: 18 },
    blockExplorer: 'https://sixscan.io/fivenet',
    icon: 'six.network',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 151,
    name: 'Redbelly Network Mainnet',
    shortName: 'rbn',
    rpcUrls: ['https://governors.mainnet.redbelly.network'],
    nativeCurrency: { name: 'Redbelly Network Coin', symbol: 'RBNT', decimals: 18 },
    blockExplorer: 'https://redbelly.routescan.io',
    icon: 'redbelly.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 153,
    name: 'Redbelly Network Testnet',
    shortName: 'rbn-testnet',
    rpcUrls: ['https://governors.testnet.redbelly.network'],
    nativeCurrency: { name: 'Redbelly Network Coin', symbol: 'RBNT', decimals: 18 },
    blockExplorer: 'https://redbelly.testnet.routescan.io',
    icon: 'redbelly.network',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 155,
    name: 'Tenet Testnet',
    shortName: 'tenet-testnet',
    rpcUrls: ['https://rpc.testnet.tenet.org'],
    nativeCurrency: { name: 'TENET', symbol: 'TENET', decimals: 18 },
    blockExplorer: 'https://testnet.tenetscan.io',
    icon: 'tenet.org',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 156,
    name: 'OEBlock Testnet',
    shortName: 'obe',
    rpcUrls: ['https://testnet-rpc.oeblock.com'],
    nativeCurrency: { name: 'OEBlock', symbol: 'OEB', decimals: 18 },
    blockExplorer: 'https://testnet.oescan.io',
    icon: 'www.oeblock.com',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 157,
    name: 'Puppynet',
    shortName: 'puppynet',
    rpcUrls: ['https://puppynet.shibrpc.com'],
    nativeCurrency: { name: 'BONE', symbol: 'BONE', decimals: 18 },
    blockExplorer: 'https://puppyscan.shib.io',
    icon: 'shibariumecosystem.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 158,
    name: 'Roburna Mainnet',
    shortName: 'rba',
    rpcUrls: ['https://dataseed.roburna.com'],
    nativeCurrency: { name: 'Roburna', symbol: 'RBA', decimals: 18 },
    blockExplorer: 'https://rbascan.com',
    icon: 'www.roburna.com',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 159,
    name: 'Roburna Testnet',
    shortName: 'rbat',
    rpcUrls: ['https://preseed-testnet-1.roburna.com'],
    nativeCurrency: { name: 'Roburna', symbol: 'RBAT', decimals: 18 },
    blockExplorer: 'https://testnet.rbascan.com',
    icon: 'www.roburna.com',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 160,
    name: 'Armonia Eva Chain Mainnet',
    shortName: 'eva',
    rpcUrls: ['https://evascan.io/api/eth-rpc/'],
    nativeCurrency: { name: 'Armonia Multichain Native Token', symbol: 'AMAX', decimals: 18 },
    blockExplorer: '',
    icon: 'amax.network',
    testnet: false,
    category: 'mainnet' as const,
  },
  {
    id: 161,
    name: 'Armonia Eva Chain Testnet',
    shortName: 'wall-e',
    rpcUrls: ['https://testnet.evascan.io/api/eth-rpc/'],
    nativeCurrency: { name: 'Armonia Multichain Native Token', symbol: 'AMAX', decimals: 18 },
    blockExplorer: 'https://testnet.evascan.io',
    icon: 'amax.network',
    testnet: true,
    category: 'testnet' as const,
  },
  {
    id: 162,
    name: 'Lightstreams Testnet',
    shortName: 'tpht',
    rpcUrls: ['https://node.sirius.lightstreams.io'],
    nativeCurrency: { name: 'Lightstreams PHT', symbol: 'PHT', decimals: 18 },
    blockExplorer: '',
    icon: 'explorer.sirius.lightstreams.io',
    testnet: true,
    category: 'testnet' as const,
  }
];

/* ------------------------------------------------------------------ */
/*  Lookup Maps                                                        */
/* ------------------------------------------------------------------ */

/** Map from numeric chain ID to registry entry. */
export const CHAIN_BY_ID: Map<number, ChainRegistryEntry> = new Map(
  CHAIN_REGISTRY.map(c => [c.id, c])
);

/** Map from lowercase chain name to registry entry. */
export const CHAIN_BY_NAME: Map<string, ChainRegistryEntry> = new Map(
  CHAIN_REGISTRY.map(c => [c.name.toLowerCase(), c])
);

/* ------------------------------------------------------------------ */
/*  Search & Filter Helpers                                            */
/* ------------------------------------------------------------------ */

/** Search chains by name or shortName (fuzzy match). */
export function searchChains(query: string): ChainRegistryEntry[] {
  const q = query.toLowerCase();
  return CHAIN_REGISTRY.filter(
    c =>
      c.name.toLowerCase().includes(q) ||
      c.shortName.toLowerCase().includes(q) ||
      c.category.includes(q) ||
      String(c.id).includes(q),
  );
}

/** Get all chains matching a category. */
export function getChainsByCategory(category: ChainCategory): ChainRegistryEntry[] {
  return CHAIN_REGISTRY.filter(c => c.category === category);
}
