/**
 * EVM Chain Registry — Auto-generated from chainid.network.
 *
 * DO NOT EDIT MANUALLY. Run `pnpm fetch-chains` to regenerate.
 *
 * Generated: 2026-06-04T00:42:00.000Z
 * Chain count: 120
 */

import type { ChainRegistryEntry, ChainCategory } from './types.js';

/* ------------------------------------------------------------------ */
/*  Chain Registry Data                                                */
/* ------------------------------------------------------------------ */

export const CHAIN_REGISTRY: ChainRegistryEntry[] = [
  {
    id: 1,
    name: 'Ethereum Mainnet',
    shortName: 'eth',
    rpcUrls: ['https://rpc.sepolia.org', 'https://rpc2.sepolia.org', 'https://rpc.sepolia.ethpandaops.io', 'https://sepolia.infura.io/v3'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://etherscan.io',
    icon: 'etherscan.io',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 10,
    name: 'Optimism',
    shortName: 'op',
    rpcUrls: ['https://mainnet.optimism.io', 'https://rpc.ankr.com/optimism', 'https://optimism-mainnet.public.blastapi.io'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://optimistic.etherscan.io',
    icon: 'optimistic.etherscan.io',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 25,
    name: 'Cronos',
    shortName: 'cro',
    rpcUrls: ['https://evm.cronos.org', 'https://rpc.ankr.com/cronos'],
    nativeCurrency: { name: 'Cronos', symbol: 'CRO', decimals: 18 },
    blockExplorer: 'https://cronoscan.com',
    icon: 'cronoscan.com',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 56,
    name: 'BNB Smart Chain',
    shortName: 'bnb',
    rpcUrls: ['https://bsc-dataseed.binance.org', 'https://rpc.ankr.com/bsc', 'https://bsc-dataseed1.defibit.io'],
    nativeCurrency: { name: 'BNB', symbol: 'BNB', decimals: 18 },
    blockExplorer: 'https://bscscan.com',
    icon: 'bscscan.com',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 97,
    name: 'BSC Testnet',
    shortName: 'bnbt',
    rpcUrls: ['https://data-seed-prebsc1.bnbchain.org', 'https://bsc-testnet-rpc.publicnode.com'],
    nativeCurrency: { name: 'BNB', symbol: 'tBNB', decimals: 18 },
    blockExplorer: 'https://testnet.bscscan.com',
    icon: 'testnet.bscscan.com',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 100,
    name: 'Gnosis Chain',
    shortName: 'gno',
    rpcUrls: ['https://rpc.gnosischain.com', 'https://rpc.ankr.com/gnosis', 'https://gnosis-mainnet.public.blastapi.io'],
    nativeCurrency: { name: 'xDAI', symbol: 'XDAI', decimals: 18 },
    blockExplorer: 'https://gnosisscan.io',
    icon: 'gnosisscan.io',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 122,
    name: 'Fuse Mainnet',
    shortName: 'fuse',
    rpcUrls: ['https://rpc.fuse.io'],
    nativeCurrency: { name: 'Fuse', symbol: 'FUSE', decimals: 18 },
    blockExplorer: 'https://explorer.fuse.io',
    icon: 'explorer.fuse.io',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 128,
    name: 'Huobi ECO Chain',
    shortName: 'heco',
    rpcUrls: ['https://http-mainnet.hecochain.com', 'https://http-mainnet-node.huobichain.com'],
    nativeCurrency: { name: 'Huobi ECO Chain Native Token', symbol: 'HT', decimals: 18 },
    blockExplorer: 'https://hecoinfo.com',
    icon: 'hecoinfo.com',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 137,
    name: 'Polygon',
    shortName: 'matic',
    rpcUrls: ['https://polygon-rpc.com', 'https://rpc.ankr.com/polygon', 'https://polygon-mainnet.public.blastapi.io'],
    nativeCurrency: { name: 'MATIC', symbol: 'MATIC', decimals: 18 },
    blockExplorer: 'https://polygonscan.com',
    icon: 'polygonscan.com',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 169,
    name: 'Manta Pacific',
    shortName: 'manta',
    rpcUrls: ['https://pacific-rpc.manta.network/http'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://pacific-explorer.manta.network',
    icon: 'pacific-explorer.manta.network',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 196,
    name: 'OKXChain Mainnet',
    shortName: 'okt',
    rpcUrls: ['https://exchainrpc.okex.org', 'https://okc-mainnet.gateway.pokt.network/v1/lb/6275309be378af005ae84a69'],
    nativeCurrency: { name: 'OKXChain Global Utility Token', symbol: 'OKT', decimals: 18 },
    blockExplorer: 'https://www.oklink.com/en/okc',
    icon: 'oklink.com',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 204,
    name: 'opBNB Mainnet',
    shortName: 'obnb',
    rpcUrls: ['https://opbnb-mainnet-rpc.bnbchain.org', 'https://opbnb-mainnet.nodereal.io/v1'],
    nativeCurrency: { name: 'BNB', symbol: 'BNB', decimals: 18 },
    blockExplorer: 'https://opbnbscan.com',
    icon: 'opbnbscan.com',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 250,
    name: 'Fantom Opera',
    shortName: 'ftm',
    rpcUrls: ['https://rpc.ftm.tools', 'https://rpc.ankr.com/fantom', 'https://fantom-rpc.publicnode.com'],
    nativeCurrency: { name: 'Fantom', symbol: 'FTM', decimals: 18 },
    blockExplorer: 'https://ftmscan.com',
    icon: 'ftmscan.com',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 255,
    name: 'Kroma',
    shortName: 'kroma',
    rpcUrls: ['https://api.kroma.network'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://kromascan.com',
    icon: 'kromascan.com',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 288,
    name: 'Boba Network',
    shortName: 'boba',
    rpcUrls: ['https://mainnet.boba.network', 'https://replica.boba.network'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://bobascan.com',
    icon: 'bobascan.com',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 314,
    name: 'Filecoin',
    shortName: 'filecoin',
    rpcUrls: ['https://api.node.glif.io/rpc/v1', 'https://rpc.ankr.com/filecoin'],
    nativeCurrency: { name: 'Filecoin', symbol: 'FIL', decimals: 18 },
    blockExplorer: 'https://filfox.info',
    icon: 'filfox.info',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 324,
    name: 'zkSync Era',
    shortName: 'zksync',
    rpcUrls: ['https://mainnet.era.zksync.io', 'https://rpc.ankr.com/zksync-era'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.zksync.io',
    icon: 'explorer.zksync.io',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 369,
    name: 'PulseChain',
    shortName: 'pls',
    rpcUrls: ['https://rpc.pulsechain.com', 'https://pulsechain-rpc.publicnode.com'],
    nativeCurrency: { name: 'Pulse', symbol: 'PLS', decimals: 18 },
    blockExplorer: 'https://scan.pulsechain.com',
    icon: 'scan.pulsechain.com',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 480,
    name: 'World Chain',
    shortName: 'wc',
    rpcUrls: ['https://worldchain-mainnet.g.alchemy.com/public'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://worldchain-mainnet.explorer.alchemy.com',
    icon: 'worldchain-mainnet.explorer.alchemy.com',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 1030,
    name: 'Conflux eSpace',
    shortName: 'cfx',
    rpcUrls: ['https://evm.confluxrpc.com', 'https://conflux-espace-rpc.publicnode.com'],
    nativeCurrency: { name: 'CFX', symbol: 'CFX', decimals: 18 },
    blockExplorer: 'https://evm.confluxscan.io',
    icon: 'evm.confluxscan.io',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 1088,
    name: 'Metis Andromeda',
    shortName: 'metis',
    rpcUrls: ['https://andromeda.metis.io'],
    nativeCurrency: { name: 'Metis', symbol: 'METIS', decimals: 18 },
    blockExplorer: 'https://andromeda-explorer.metis.io',
    icon: 'andromeda-explorer.metis.io',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 1101,
    name: 'Polygon zkEVM',
    shortName: 'zkevm',
    rpcUrls: ['https://zkevm-rpc.com', 'https://rpc.ankr.com/polygon_zkevm'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://zkevm.polygonscan.com',
    icon: 'zkevm.polygonscan.com',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 1284,
    name: 'Moonbeam',
    shortName: 'glmr',
    rpcUrls: ['https://rpc.api.moonbeam.network', 'https://moonbeam-rpc.dwellir.com'],
    nativeCurrency: { name: 'Glimmer', symbol: 'GLMR', decimals: 18 },
    blockExplorer: 'https://moonscan.io',
    icon: 'moonscan.io',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 1285,
    name: 'Moonriver',
    shortName: 'mriver',
    rpcUrls: ['https://rpc.api.moonriver.moonbeam.network', 'https://moonriver-rpc.dwellir.com'],
    nativeCurrency: { name: 'Moonriver', symbol: 'MOVR', decimals: 18 },
    blockExplorer: 'https://moonriver.moonscan.io',
    icon: 'moonriver.moonscan.io',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 2020,
    name: 'PublicMint Mainnet',
    shortName: 'mint',
    rpcUrls: ['https://rpc.publicmint.io'],
    nativeCurrency: { name: 'USD', symbol: 'USD', decimals: 18 },
    blockExplorer: 'https://explorer.publicmint.io',
    icon: 'explorer.publicmint.io',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 2818,
    name: 'Morph Mainnet',
    shortName: 'morph',
    rpcUrls: ['https://rpc.morphl2.io'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.morphl2.io',
    icon: 'explorer.morphl2.io',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 5000,
    name: 'Mantle',
    shortName: 'mantle',
    rpcUrls: ['https://rpc.mantle.xyz', 'https://mantle.drpc.org'],
    nativeCurrency: { name: 'Mantle', symbol: 'MNT', decimals: 18 },
    blockExplorer: 'https://explorer.mantle.xyz',
    icon: 'explorer.mantle.xyz',
    testnet: false,
    category: 'defi' as const,
  },,
  {
    id: 5002,
    name: 'Treasurenet Mainnet Alpha',
    shortName: 'tnet',
    rpcUrls: ['https://node0.treasurenet.io', 'https://node1.treasurenet.io'],
    nativeCurrency: { name: 'UNIT', symbol: 'UNIT', decimals: 18 },
    blockExplorer: 'https://evmexplorer.treasurenet.io',
    icon: 'evmexplorer.treasurenet.io',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 7560,
    name: 'Cyber Mainnet',
    shortName: 'cyber',
    rpcUrls: ['https://rpc.cyber.co'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://cyberscan.co',
    icon: 'cyberscan.co',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 8453,
    name: 'Base',
    shortName: 'base',
    rpcUrls: ['https://mainnet.base.org', 'https://rpc.ankr.com/base', 'https://base-mainnet.public.blastapi.io'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://basescan.org',
    icon: 'basescan.org',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 10200,
    name: 'Gnosis Chiado Testnet',
    shortName: 'chi',
    rpcUrls: ['https://rpc.chiadochain.net', 'https://gnosis-chiado-rpc.publicnode.com'],
    nativeCurrency: { name: 'Chiado xDAI', symbol: 'XDAI', decimals: 18 },
    blockExplorer: 'https://blockscout.chiadochain.net',
    icon: 'blockscout.chiadochain.net',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 34443,
    name: 'Mode',
    shortName: 'mode',
    rpcUrls: ['https://mainnet.mode.network', 'https://mode.drpc.org'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.mode.network',
    icon: 'explorer.mode.network',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 42161,
    name: 'Arbitrum One',
    shortName: 'arb1',
    rpcUrls: ['https://arb1.arbitrum.io/rpc', 'https://rpc.ankr.com/arbitrum', 'https://arbitrum-one.public.blastapi.io'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://arbiscan.io',
    icon: 'arbiscan.io',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 42170,
    name: 'Arbitrum Nova',
    shortName: 'arb-nova',
    rpcUrls: ['https://nova.arbitrum.io/rpc', 'https://arbitrum-nova.public.blastapi.io'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://nova.arbiscan.io',
    icon: 'nova.arbiscan.io',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 42220,
    name: 'Celo',
    shortName: 'celo',
    rpcUrls: ['https://forno.celo.org', 'https://rpc.ankr.com/celo'],
    nativeCurrency: { name: 'Celo', symbol: 'CELO', decimals: 18 },
    blockExplorer: 'https://celoscan.io',
    icon: 'celoscan.io',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 43113,
    name: 'Avalanche Fuji',
    shortName: 'fuji',
    rpcUrls: ['https://api.avax-test.network/ext/bc/C/rpc', 'https://avalanche-fuji-c-chain-rpc.publicnode.com'],
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
    blockExplorer: 'https://testnet.snowtrace.io',
    icon: 'testnet.snowtrace.io',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 43114,
    name: 'Avalanche C-Chain',
    shortName: 'avax',
    rpcUrls: ['https://api.avax.network/ext/bc/C/rpc', 'https://rpc.ankr.com/avalanche', 'https://avalanche-mainnet.infura.io/v3'],
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
    blockExplorer: 'https://snowtrace.io',
    icon: 'snowtrace.io',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 59141,
    name: 'Linea Sepolia',
    shortName: 'linea-sepolia',
    rpcUrls: ['https://rpc.sepolia.linea.build'],
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://sepolia.lineascan.build',
    icon: 'sepolia.lineascan.build',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 59144,
    name: 'Linea',
    shortName: 'linea',
    rpcUrls: ['https://rpc.linea.build', 'https://linea-mainnet.infura.io/v3'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://lineascan.build',
    icon: 'lineascan.build',
    testnet: false,
    category: 'defi' as const,
  },,
  {
    id: 60808,
    name: 'Bobas',
    shortName: 'bobas',
    rpcUrls: ['https://rpc.boba.network'],
    nativeCurrency: { name: 'Boba Token', symbol: 'BOBA', decimals: 18 },
    blockExplorer: 'https://bobascan.com',
    icon: 'bobascan.com',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 80002,
    name: 'Polygon Amoy',
    shortName: 'amoy',
    rpcUrls: ['https://rpc-amoy.polygon.technology', 'https://polygon-amoy-bor-rpc.publicnode.com'],
    nativeCurrency: { name: 'MATIC', symbol: 'MATIC', decimals: 18 },
    blockExplorer: 'https://amoy.polygonscan.com',
    icon: 'amoy.polygonscan.com',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 81457,
    name: 'Blast',
    shortName: 'blast',
    rpcUrls: ['https://rpc.blast.io', 'https://blast.din.dev/rpc', 'https://rpc.ankr.com/blast'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://blastscan.io',
    icon: 'blastscan.io',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 84532,
    name: 'Base Sepolia',
    shortName: 'basesep',
    rpcUrls: ['https://sepolia.base.org', 'https://base-sepolia.blockpi.network/v1/rpc/public'],
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://sepolia.basescan.org',
    icon: 'sepolia.basescan.org',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 88888,
    name: 'Chiliz Chain',
    shortName: 'chz',
    rpcUrls: ['https://rpc.ankr.com/chiliz', 'https://chiliz-rpc.publicnode.com'],
    nativeCurrency: { name: 'Chiliz', symbol: 'CHZ', decimals: 18 },
    blockExplorer: 'https://scan.chiliz.com',
    icon: 'scan.chiliz.com',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 421614,
    name: 'Arbitrum Sepolia',
    shortName: 'arb-sep',
    rpcUrls: ['https://sepolia-rollup.arbitrum.io/rpc', 'https://arbitrum-sepolia.blockpi.network/v1/rpc/public'],
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://sepolia.arbiscan.io',
    icon: 'sepolia.arbiscan.io',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 504441,
    name: 'Playdapp Network',
    shortName: 'PDA',
    rpcUrls: ['https://subnets.avax.network/playdappne/mainnet/rpc'],
    nativeCurrency: { name: 'Playdapp', symbol: 'PDA', decimals: 18 },
    blockExplorer: 'https://subnets.avax.network/playdappne',
    icon: 'subnets.avax.network/playdappne',
    testnet: false,
    category: 'gaming' as const,
  },,
  {
    id: 534351,
    name: 'Scroll Sepolia Testnet',
    shortName: 'scr-sepolia',
    rpcUrls: ['https://sepolia-rpc.scroll.io', 'https://rpc.ankr.com/scroll_sepolia_testnet', 'https://scroll-sepolia.chainstacklabs.com'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://sepolia.scrollscan.com',
    icon: 'sepolia.scrollscan.com',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 534352,
    name: 'Scroll',
    shortName: 'scr',
    rpcUrls: ['https://rpc.scroll.io', 'https://rpc.ankr.com/scroll', 'https://scroll-mainnet.chainstacklabs.com', 'https://scroll-rpc.publicnode.com'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://scrollscan.com',
    icon: 'scrollscan.com',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 534353,
    name: 'Scroll Alpha Testnet',
    shortName: 'scr-alpha',
    rpcUrls: ['https://alpha-rpc.scroll.io/l2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://alpha-blockscout.scroll.io',
    icon: 'alpha-blockscout.scroll.io',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 656476,
    name: 'EDU Chain Testnet',
    shortName: 'open-campus-codex',
    rpcUrls: ['https://rpc.open-campus-codex.gelato.digital'],
    nativeCurrency: { name: 'EDU', symbol: 'EDU', decimals: 18 },
    blockExplorer: 'https://edu-chain-testnet.blockscout.com',
    icon: 'edu-chain-testnet.blockscout.com',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 660279,
    name: 'Xai Mainnet',
    shortName: 'xai',
    rpcUrls: ['https://xai-chain.net/rpc'],
    nativeCurrency: { name: 'Xai', symbol: 'XAI', decimals: 18 },
    blockExplorer: 'https://explorer.xai-chain.net',
    icon: 'explorer.xai-chain.net',
    testnet: false,
    category: 'gaming' as const,
  },,
  {
    id: 743111,
    name: 'Hemi Sepolia',
    shortName: 'hemi-sep',
    rpcUrls: ['https://testnet.rpc.hemi.network/rpc'],
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://testnet.explorer.hemi.xyz',
    icon: 'testnet.explorer.hemi.xyz',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 747474,
    name: 'katana',
    shortName: 'katana',
    rpcUrls: ['https://rpc.katana.network', 'https://katana.gateway.tenderly.co/', 'https://rpc.katanarpc.com/'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://katanascan.com',
    icon: 'katanascan.com',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 763373,
    name: 'Ink Sepolia',
    shortName: 'inksepolia',
    rpcUrls: ['https://rpc-gel-sepolia.inkonchain.com'],
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer-sepolia.inkonchain.com',
    icon: 'explorer-sepolia.inkonchain.com',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 808813,
    name: 'BOB Sepolia',
    shortName: 'bob-sepolia',
    rpcUrls: ['https://bob-sepolia.rpc.gobob.xyz'],
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://bob-sepolia.explorer.gobob.xyz',
    icon: 'bob-sepolia.explorer.gobob.xyz',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 810180,
    name: 'zkLink Nova Mainnet',
    shortName: 'zklink-nova',
    rpcUrls: ['https://rpc.zklink.io'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.zklink.io',
    icon: 'explorer.zklink.io',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 978658,
    name: 'Treasure Topaz',
    shortName: 'treasure-topaz',
    rpcUrls: ['https://rpc.topaz.treasure.lol'],
    nativeCurrency: { name: 'Testnet MAGIC', symbol: 'MAGIC', decimals: 18 },
    blockExplorer: 'https://topaz.treasurescan.io',
    icon: 'topaz.treasurescan.io',
    testnet: true,
    category: 'gaming' as const,
  },,
  {
    id: 984122,
    name: 'Forma',
    shortName: 'forma',
    rpcUrls: ['https://rpc.forma.art'],
    nativeCurrency: { name: 'TIA', symbol: 'TIA', decimals: 18 },
    blockExplorer: 'https://explorer.forma.art',
    icon: 'explorer.forma.art',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 988207,
    name: 'Ecrox Chain Mainnet',
    shortName: 'ecrox',
    rpcUrls: ['https://mainnet-rpc.ecroxscan.com/'],
    nativeCurrency: { name: 'ECROX COIN', symbol: 'ECROX', decimals: 18 },
    blockExplorer: 'https://ecroxscan.com',
    icon: 'ecroxscan.com',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 1440000,
    name: 'XRPL EVM Sidechain',
    shortName: 'xrplevm',
    rpcUrls: ['https://rpc.xrplevm.org'],
    nativeCurrency: { name: 'XRP', symbol: 'XRP', decimals: 18 },
    blockExplorer: 'https://explorer.xrplevm.org',
    icon: 'explorer.xrplevm.org',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 2632500,
    name: 'COTI',
    shortName: 'coti',
    rpcUrls: ['https://mainnet.coti.io/rpc'],
    nativeCurrency: { name: 'COTI', symbol: 'COTI', decimals: 18 },
    blockExplorer: 'https://mainnet.cotiscan.io',
    icon: 'mainnet.cotiscan.io',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 2702128,
    name: 'Xterio Chain (ETH)',
    shortName: 'xterio',
    rpcUrls: ['https://xterio-eth.alt.technology'],
    nativeCurrency: { name: 'ETH', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://eth.xterscan.io',
    icon: 'eth.xterscan.io',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 3132023,
    name: 'Sahara AI',
    shortName: 'sahara',
    rpcUrls: ['https://mainnet.saharalabs.ai'],
    nativeCurrency: { name: 'Sahara AI', symbol: 'SAHARA', decimals: 18 },
    blockExplorer: '',
    icon: '',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 3397901,
    name: 'Funki Sepolia Testnet',
    shortName: 'funkisepolia',
    rpcUrls: ['https://funki-testnet.alt.technology'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://testnet.funkiscan.io',
    icon: 'testnet.funkiscan.io',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 3441006,
    name: 'Manta Pacific Sepolia Testnet',
    shortName: 'mantaSepoliaTestnet',
    rpcUrls: ['https://pacific-rpc.sepolia-testnet.manta.network/http'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://pacific-explorer.sepolia-testnet.manta.network',
    icon: 'pacific-explorer.sepolia-testnet.manta.network',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 5734951,
    name: 'Jovay Mainnet',
    shortName: 'jovay',
    rpcUrls: ['https://rpc.jovay.io', 'https://api.zan.top/node/v1/jovay/mainnet'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.jovay.io/l2',
    icon: 'explorer.jovay.io',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 7225878,
    name: 'Saakuru Mainnet',
    shortName: 'saakuru',
    rpcUrls: ['https://rpc.saakuru.network'],
    nativeCurrency: { name: 'OAS', symbol: 'OAS', decimals: 18 },
    blockExplorer: 'https://explorer.saakuru.network',
    icon: 'explorer.saakuru.network',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 7771777,
    name: 'VALYGO Smartchain',
    shortName: 'vyo',
    rpcUrls: ['https://rpc-gw-1.vyoscan.com/ext/bc/2t51dXsuxUvd9teY9TKEJmgxmxMk3CRF88UYTA4HQgjeYZqzSX/rpc'],
    nativeCurrency: { name: 'VYO', symbol: 'VYO', decimals: 18 },
    blockExplorer: 'https://vyoscan.com',
    icon: 'vyoscan.com',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 7777777,
    name: 'Zora',
    shortName: 'zora',
    rpcUrls: ['https://rpc.zora.energy/'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.zora.energy',
    icon: 'explorer.zora.energy',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 8008135,
    name: 'Fhenix Helium',
    shortName: 'fhe-helium',
    rpcUrls: ['https://api.helium.fhenix.zone'],
    nativeCurrency: { name: 'tFHE', symbol: 'tFHE', decimals: 18 },
    blockExplorer: 'https://explorer.helium.fhenix.zone',
    icon: 'explorer.helium.fhenix.zone',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 8080808,
    name: 'Hokum',
    shortName: 'hokum',
    rpcUrls: ['https://mainnet.hokum.gg'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.hokum.gg',
    icon: 'explorer.hokum.gg',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 10241024,
    name: 'AlienX Mainnet',
    shortName: 'AlienX',
    rpcUrls: ['https://rpc.alienxchain.io/http'],
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.alienxchain.io',
    icon: 'explorer.alienxchain.io',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 11142220,
    name: 'Celo Sepolia Testnet',
    shortName: 'celo-sep',
    rpcUrls: ['https://forno.celo-sepolia.celo-testnet.org'],
    nativeCurrency: { name: 'CELO', symbol: 'CELO', decimals: 18 },
    blockExplorer: 'https://celo-sepolia.blockscout.com',
    icon: 'celo-sepolia.blockscout.com',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 11155111,
    name: 'Ethereum Sepolia',
    shortName: 'sep',
    rpcUrls: ['https://rpc.sepolia.org', 'https://rpc2.sepolia.org', 'https://sepolia.drpc.org', 'https://ethereum-sepolia-rpc.publicnode.com'],
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://sepolia.etherscan.io',
    icon: 'sepolia.etherscan.io',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 11155420,
    name: 'OP Sepolia Testnet',
    shortName: 'opsep',
    rpcUrls: ['https://sepolia.optimism.io', 'https://optimism-sepolia.drpc.org'],
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://sepolia-optimism.etherscan.io',
    icon: 'sepolia-optimism.etherscan.io',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 20241133,
    name: 'Swan Proxima Testnet',
    shortName: 'Proxima',
    rpcUrls: ['https://rpc-proxima.swanchain.io'],
    nativeCurrency: { name: 'SWANETH', symbol: 'sETH', decimals: 18 },
    blockExplorer: 'https://proxima-explorer.swanchain.io',
    icon: 'proxima-explorer.swanchain.io',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 21000000,
    name: 'Corn',
    shortName: 'corn',
    rpcUrls: ['https://mainnet.corn-rpc.com', 'https://rpc.ankr.com/corn_maizenet'],
    nativeCurrency: { name: 'Bitcorn', symbol: 'BTCN', decimals: 18 },
    blockExplorer: 'https://cornscan.io',
    icon: 'cornscan.io',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 28122024,
    name: 'Ancient8 Testnet',
    shortName: 'a8',
    rpcUrls: ['https://rpcv2-testnet.ancient8.gg'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://scanv2-testnet.ancient8.gg',
    icon: 'scanv2-testnet.ancient8.gg',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 108160679,
    name: 'Oraichain Mainnet',
    shortName: 'Oraichain',
    rpcUrls: ['https://evm.orai.io'],
    nativeCurrency: { name: 'Oraichain Token', symbol: 'ORAI', decimals: 18 },
    blockExplorer: '',
    icon: '',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 111557560,
    name: 'Cyber Testnet',
    shortName: 'cysep',
    rpcUrls: ['https://cyber-testnet.alt.technology/', 'https://rpc.testnet.cyber.co/'],
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://testnet.cyberscan.co',
    icon: 'testnet.cyberscan.co',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 123420111,
    name: 'OP Celestia Raspberry',
    shortName: 'opcelestia-raspberry',
    rpcUrls: ['https://rpc.opcelestia-raspberry.gelato.digital'],
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://opcelestia-raspberry.gelatoscout.com',
    icon: 'opcelestia-raspberry.gelatoscout.com',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 168587773,
    name: 'Blast Sepolia Testnet',
    shortName: 'blastsepolia',
    rpcUrls: ['https://sepolia.blast.io', 'https://blast-sepolia.drpc.org'],
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://testnet.blastscan.io',
    icon: 'testnet.blastscan.io',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 222000222,
    name: 'Kanazawa',
    shortName: 'kanazawa',
    rpcUrls: ['https://testnet-rpc.meld.com'],
    nativeCurrency: { name: 'gMeld', symbol: 'gMELD', decimals: 18 },
    blockExplorer: 'https://testnet.meldscan.io',
    icon: 'testnet.meldscan.io',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 241320161,
    name: 'XMTP Sepolia',
    shortName: 'xmtp-sepolia',
    rpcUrls: [],
    nativeCurrency: { name: 'USDC', symbol: 'USDC', decimals: 18 },
    blockExplorer: '',
    icon: '',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 245022926,
    name: 'Neon EVM Devnet',
    shortName: 'neonevm-devnet',
    rpcUrls: ['https://devnet.neonevm.org', 'https://neon-evm-devnet.drpc.org'],
    nativeCurrency: { name: 'Neon', symbol: 'NEON', decimals: 18 },
    blockExplorer: 'https://devnet.neonscan.org',
    icon: 'devnet.neonscan.org',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 245022934,
    name: 'Neon EVM Mainnet',
    shortName: 'neonevm-mainnet',
    rpcUrls: ['https://neon-proxy-mainnet.solana.p2p.org', 'https://neon-evm.drpc.org'],
    nativeCurrency: { name: 'Neon', symbol: 'NEON', decimals: 18 },
    blockExplorer: 'https://neonscan.org',
    icon: 'neonscan.org',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 253368190,
    name: 'Flame',
    shortName: 'flame',
    rpcUrls: ['https://rpc.flame.astria.org'],
    nativeCurrency: { name: 'TIA', symbol: 'TIA', decimals: 18 },
    blockExplorer: 'https://explorer.flame.astria.org',
    icon: 'explorer.flame.astria.org',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 333000333,
    name: 'Meld',
    shortName: 'meld',
    rpcUrls: ['https://rpc-1.meld.com'],
    nativeCurrency: { name: 'gMeld', symbol: 'gMELD', decimals: 18 },
    blockExplorer: 'https://meldscan.io',
    icon: 'meldscan.io',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 420420418,
    name: 'Kusama',
    shortName: 'ksm',
    rpcUrls: ['https://eth-rpc-kusama.polkadot.io'],
    nativeCurrency: { name: 'KSM', symbol: 'KSM', decimals: 18 },
    blockExplorer: 'https://blockscout-kusama.polkadot.io',
    icon: 'blockscout-kusama.polkadot.io',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 420420419,
    name: 'Polkadot',
    shortName: 'dot',
    rpcUrls: ['https://services.polkadothub-rpc.com/mainnet', 'https://eth-rpc.polkadot.io'],
    nativeCurrency: { name: 'DOT', symbol: 'DOT', decimals: 18 },
    blockExplorer: 'https://blockscout.polkadot.io',
    icon: 'blockscout.polkadot.io',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 531050104,
    name: 'Sophon Testnet',
    shortName: 'sophon-testnet',
    rpcUrls: ['https://rpc.testnet.sophon.xyz'],
    nativeCurrency: { name: 'Sophon', symbol: 'SOPH', decimals: 18 },
    blockExplorer: 'https://explorer.testnet.sophon.xyz',
    icon: 'explorer.testnet.sophon.xyz',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 666666666,
    name: 'Degen Chain',
    shortName: 'degen-chain',
    rpcUrls: ['https://rpc.degen.tips'],
    nativeCurrency: { name: 'DEGEN', symbol: 'DEGEN', decimals: 18 },
    blockExplorer: '',
    icon: '',
    testnet: false,
    category: 'gaming' as const,
  },,
  {
    id: 888888888,
    name: 'Ancient8',
    shortName: 'ancient8',
    rpcUrls: ['https://rpc.ancient8.gg'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://scan.ancient8.gg',
    icon: 'scan.ancient8.gg',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 974399131,
    name: 'SKALE Calypso Hub Testnet',
    shortName: 'calypso-testnet',
    rpcUrls: ['https://testnet.skalenodes.com/v1/giant-half-dual-testnet'],
    nativeCurrency: { name: 'sFUEL', symbol: 'sFUEL', decimals: 18 },
    blockExplorer: 'https://giant-half-dual-testnet.explorer.testnet.skalenodes.com',
    icon: 'giant-half-dual-testnet.explorer.testnet.skalenodes.com',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 994873017,
    name: 'Lumia Mainnet',
    shortName: 'lumia-mainnet',
    rpcUrls: ['https://mainnet-rpc.lumia.org'],
    nativeCurrency: { name: 'Lumia', symbol: 'LUMIA', decimals: 18 },
    blockExplorer: 'https://explorer.lumia.org',
    icon: 'explorer.lumia.org',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 999999999,
    name: 'Zora Sepolia Testnet',
    shortName: 'zsep',
    rpcUrls: ['https://sepolia.rpc.zora.energy'],
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://sepolia.explorer.zora.energy',
    icon: 'sepolia.explorer.zora.energy',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 1020352220,
    name: 'SKALE Titan Hub Testnet',
    shortName: 'titan-testnet',
    rpcUrls: ['https://testnet.skalenodes.com/v1/aware-fake-trim-testnet'],
    nativeCurrency: { name: 'sFUEL', symbol: 'sFUEL', decimals: 18 },
    blockExplorer: 'https://aware-fake-trim-testnet.explorer.testnet.skalenodes.com',
    icon: 'aware-fake-trim-testnet.explorer.testnet.skalenodes.com',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 1273227453,
    name: 'HUMAN Protocol',
    shortName: 'human-mainnet',
    rpcUrls: ['https://mainnet.skalenodes.com/v1/wan-red-ain'],
    nativeCurrency: { name: 'sFUEL', symbol: 'sFUEL', decimals: 18 },
    blockExplorer: 'https://wan-red-ain.explorer.mainnet.skalenodes.com',
    icon: 'wan-red-ain.explorer.mainnet.skalenodes.com',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 1313161554,
    name: 'Aurora Mainnet',
    shortName: 'aurora',
    rpcUrls: ['https://mainnet.aurora.dev', 'https://aurora.drpc.org'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.aurora.dev',
    icon: 'explorer.aurora.dev',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 1313161555,
    name: 'Aurora Testnet',
    shortName: 'aurora-testnet',
    rpcUrls: ['https://testnet.aurora.dev/', 'https://aurora-testnet.drpc.org'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.testnet.aurora.dev',
    icon: 'explorer.testnet.aurora.dev',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 1350216234,
    name: 'SKALE Titan Hub',
    shortName: 'titan-mainnet',
    rpcUrls: ['https://mainnet.skalenodes.com/v1/parallel-stormy-spica'],
    nativeCurrency: { name: 'sFUEL', symbol: 'sFUEL', decimals: 18 },
    blockExplorer: 'https://parallel-stormy-spica.explorer.mainnet.skalenodes.com',
    icon: 'parallel-stormy-spica.explorer.mainnet.skalenodes.com',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 1380012617,
    name: 'RARI Chain Mainnet',
    shortName: 'rari-mainnet',
    rpcUrls: ['https://rari.calderachain.xyz/http'],
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://mainnet.explorer.rarichain.org',
    icon: 'mainnet.explorer.rarichain.org',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 1444673419,
    name: 'SKALE Europa Hub Testnet',
    shortName: 'europa-testnet',
    rpcUrls: ['https://testnet.skalenodes.com/v1/juicy-low-small-testnet'],
    nativeCurrency: { name: 'sFUEL', symbol: 'sFUEL', decimals: 18 },
    blockExplorer: 'https://juicy-low-small-testnet.explorer.testnet.skalenodes.com',
    icon: 'juicy-low-small-testnet.explorer.testnet.skalenodes.com',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 1482601649,
    name: 'SKALE Nebula Hub',
    shortName: 'nebula-mainnet',
    rpcUrls: ['https://mainnet.skalenodes.com/v1/green-giddy-denebola'],
    nativeCurrency: { name: 'sFUEL', symbol: 'sFUEL', decimals: 18 },
    blockExplorer: 'https://green-giddy-denebola.explorer.mainnet.skalenodes.com',
    icon: 'green-giddy-denebola.explorer.mainnet.skalenodes.com',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 1511670449,
    name: 'GPT Mainnet',
    shortName: 'GPT',
    rpcUrls: ['https://rpc.gptprotocol.io'],
    nativeCurrency: { name: 'GPT', symbol: 'GPT', decimals: 18 },
    blockExplorer: 'https://explorer.gptprotocol.io',
    icon: 'explorer.gptprotocol.io',
    testnet: false,
    category: 'mainnet' as const,
  },,
  {
    id: 1564830818,
    name: 'SKALE Calypso Hub',
    shortName: 'calypso-mainnet',
    rpcUrls: ['https://mainnet.skalenodes.com/v1/honorable-steel-rasalhague'],
    nativeCurrency: { name: 'sFUEL', symbol: 'sFUEL', decimals: 18 },
    blockExplorer: 'https://honorable-steel-rasalhague.explorer.mainnet.skalenodes.com',
    icon: 'honorable-steel-rasalhague.explorer.mainnet.skalenodes.com',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 1666600000,
    name: 'Harmony Mainnet Shard 0',
    shortName: 'hmy-s0',
    rpcUrls: ['https://api.harmony.one', 'https://a.api.s0.t.hmny.io', 'https://rpc.ankr.com/harmony', 'https://1rpc.io/one'],
    nativeCurrency: { name: 'ONE', symbol: 'ONE', decimals: 18 },
    blockExplorer: 'https://explorer.harmony.one',
    icon: 'explorer.harmony.one',
    testnet: false,
    category: 'sidechain' as const,
  },,
  {
    id: 1702448187,
    name: 'WITNESS CHAIN',
    shortName: 'Witness',
    rpcUrls: ['https://sequencer.witnesschain.com'],
    nativeCurrency: { name: 'ETHER', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.witnesschain.com',
    icon: 'explorer.witnesschain.com',
    testnet: false,
    category: 'l2' as const,
  },,
  {
    id: 1918988905,
    name: 'RARI Chain Testnet',
    shortName: 'rari-testnet',
    rpcUrls: ['https://testnet.rpc.rarichain.org/http'],
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
    blockExplorer: 'https://explorer.rarichain.org',
    icon: 'explorer.rarichain.org',
    testnet: true,
    category: 'testnet' as const,
  },,
  {
    id: 2046399126,
    name: 'SKALE Europa Hub',
    shortName: 'europa',
    rpcUrls: ['https://mainnet.skalenodes.com/v1/elated-tan-skat'],
    nativeCurrency: { name: 'sFUEL', symbol: 'sFUEL', decimals: 18 },
    blockExplorer: 'https://elated-tan-skat.explorer.mainnet.skalenodes.com',
    icon: 'elated-tan-skat.explorer.mainnet.skalenodes.com',
    testnet: false,
    category: 'sidechain' as const,
  },
];

/* ------------------------------------------------------------------ */
/*  Lookup Maps                                                        */
/* ------------------------------------------------------------------ */

/** Map from numeric chain ID to registry entry. */
export const CHAIN_BY_ID: Map<number, ChainRegistryEntry> = new Map(
  CHAIN_REGISTRY.map(c => [c.id, c])
);

/** Map from lowercase chain name to registry entry. */
export const CHAIN_BY_NAME: Map<string, ChainRegistryEntry> = new Map(
  CHAIN_REGISTRY.map(c => [c.name.toLowerCase(), c])
);

/* ------------------------------------------------------------------ */
/*  Search & Filter Helpers                                            */
/* ------------------------------------------------------------------ */

/** Search chains by name or shortName (fuzzy match). */
export function searchChains(query: string): ChainRegistryEntry[] {
  const q = query.toLowerCase();
  return CHAIN_REGISTRY.filter(
    c =>
      c.name.toLowerCase().includes(q) ||
      c.shortName.toLowerCase().includes(q) ||
      c.category.includes(q) ||
      String(c.id).includes(q),
  );
}

/** Get all chains matching a category. */
export function getChainsByCategory(category: ChainCategory): ChainRegistryEntry[] {
  return CHAIN_REGISTRY.filter(c => c.category === category);
}
