name = "cinacoin-auth"
compatibility_date = "2024-12-01"
pages_build_output_dir = "out"

[vars]
JWT_SECRET = "change-me-in-production"
JWT_REFRESH_SECRET = "change-me-in-production-refresh"

[[d1_databases]]
binding = "DB"
database_name = "cinacoin-auth-db"
database_id = "7da0bdfd-cbdd-4bde-a4f2-dd410b4970e0"
