export const aptosSuiWallets = [
  {
    id: "petra",
    name: "Petra Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/petra",
    homepage: "https://petra.app",
    supportedChainFamilies: ["aptos"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/petra-aptos-wallet/ejbalmkoplchlggaogmmbbjmmghlmbnn",
    supportsCinacoinV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 38,
    description: "Leading wallet for the Aptos blockchain.",
    developer: "Petra",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/petra_app" },
  },
  {
    id: "martian",
    name: "Martian Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/martian",
    homepage: "https://martianwallet.xyz",
    supportedChainFamilies: ["aptos", "sui", "bitcoin"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "martian://",
    universalLink: "https://martianwallet.xyz",
    appStoreUrl: "https://apps.apple.com/app/martian-wallet/id6443407689",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.martianwallet",
    extensionUrl: "https://chromewebstore.google.com/detail/martian-aptos-wallet/efbglaiasppcgjgdgklmdofjhfljgmci",
    supportsCinacoinV2: true,
    openSource: false,
    walletType: "hot",
    popularity: 32,
    description: "Multi-chain wallet for Aptos, Sui, and Bitcoin.",
    developer: "Martian",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/MartianWallet" },
  },
  {
    id: "sui-wallet",
    name: "Sui Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/suiwallet",
    homepage: "https://suiwallet.com",
    supportedChainFamilies: ["sui"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/sui-wallet/opcgpfmipidbgponhmajmpahiigminig",
    supportsCinacoinV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 30,
    description: "Official wallet for the Sui blockchain.",
    developer: "Mysten Labs",
    yearFounded: 2023,
    social: { twitter: "https://twitter.com/SuiNetwork", github: "https://github.com/MystenLabs/sui-wallet" },
  },
  {
    id: "suro-wallet",
    name: "Suro Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/suiwallet",
    homepage: "https://suro.app",
    supportedChainFamilies: ["sui"],
    platforms: ["mobile"],
    deepLink: "suro://",
    universalLink: "https://suro.app",
    appStoreUrl: "https://apps.apple.com/app/suro/id6444458424",
    playStoreUrl: "https://play.google.com/store/apps/details?id=app.suro.wallet",
    walletType: "hot",
    popularity: 20,
    description: "Mobile-first wallet for the Sui ecosystem.",
    developer: "Suro",
    yearFounded: 2023,
    social: { twitter: "https://twitter.com/suro_app" },
  },
];
