export const bitcoinWallets = [
  {
    id: "blue-wallet",
    name: "BlueWallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/bluewallet",
    homepage: "https://bluewallet.io",
    supportedChainFamilies: ["bitcoin"],
    supportedChains: ["bip122:000000000019d6689c085ae165831e93"],
    platforms: ["mobile", "desktop"],
    deepLink: "bluewallet://",
    universalLink: "https://bluewallet.io",
    appStoreUrl: "https://apps.apple.com/app/bluewallet-bitcoin-wallet/id1376878040",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.bluewallet.bluewallet",
    openSource: true,
    walletType: "hot",
    popularity: 51,
    description: "Bitcoin-only wallet with Lightning Network support.",
    developer: "BlueWallet",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/bluewalletio", github: "https://github.com/BlueWallet" },
  },
  {
    id: "sparrow-wallet",
    name: "Sparrow Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/sparrow",
    homepage: "https://sparrowwallet.com",
    supportedChainFamilies: ["bitcoin"],
    supportedChains: ["bip122:000000000019d6689c085ae165831e93"],
    platforms: ["desktop"],
    openSource: true,
    walletType: "hot",
    popularity: 35,
    description: "Bitcoin desktop wallet focused on privacy and advanced features.",
    developer: "Craig Raw",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/SparrowWallet", github: "https://github.com/sparrowwallet" },
  },
  {
    id: "electrum",
    name: "Electrum",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/electrum",
    homepage: "https://electrum.org",
    supportedChainFamilies: ["bitcoin"],
    supportedChains: ["bip122:000000000019d6689c085ae165831e93"],
    platforms: ["desktop", "cli"],
    openSource: true,
    walletType: "hot",
    popularity: 53,
    description: "The original Bitcoin lightweight wallet, since 2011.",
    developer: "Thomas Voegtlin",
    yearFounded: 2011,
    social: { twitter: "https://twitter.com/ElectrumWallet", github: "https://github.com/spesmilo/electrum" },
  },
  {
    id: "xverse",
    name: "Xverse Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/xverse",
    homepage: "https://www.xverse.app",
    supportedChainFamilies: ["bitcoin"],
    supportedChains: ["bip122:000000000019d6689c085ae165831e93"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "xverse://",
    universalLink: "https://www.xverse.app",
    appStoreUrl: "https://apps.apple.com/app/xverse-wallet/id1640649756",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.xverse.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/xverse-wallet/idnnbdaxmphpflfnlkmjfbmikopedbbj",
    supportsCinacoinV2: true,
    openSource: false,
    walletType: "hot",
    popularity: 39,
    description: "Bitcoin wallet with Ordinals and BRC-20 support.",
    developer: "Secret Key Labs",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/xverseApp" },
  },
  {
    id: "unisat",
    name: "UniSat Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/unisat",
    homepage: "https://unisat.io",
    supportedChainFamilies: ["bitcoin"],
    supportedChains: ["bip122:000000000019d6689c085ae165831e93"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/unisat/ppbibelpcjmhbdihakflkdcocmkgbkbc",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 34,
    description: "Bitcoin wallet for Ordinals and BRC-20 tokens.",
    developer: "UniSat",
    yearFounded: 2023,
    social: { twitter: "https://twitter.com/unisat_wallet" },
  },
];
