export const cardanoWallets = [
  {
    id: "eternl",
    name: "Eternl",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/eternl",
    homepage: "https://eternl.io",
    supportedChainFamilies: ["cardano"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "eternl://",
    universalLink: "https://eternl.io",
    appStoreUrl: "https://apps.apple.com/app/eternl/id6446363156",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.eternl.mobile",
    extensionUrl: "https://chromewebstore.google.com/detail/eternl/khclkbglgdgbdgkgbfhbpkgbpkgbdfhg",
    supportsCinacoinV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 42,
    description: "Feature-rich Cardano wallet with NFT and DeFi support.",
    developer: "Eternl",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/Eternl_io" },
  },
  {
    id: "nami",
    name: "Nami",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/nami",
    homepage: "https://namiwallet.io",
    supportedChainFamilies: ["cardano"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/nami/lpfcbjknjpeeillaihoekokdamcmoken",
    openSource: true,
    walletType: "hot",
    popularity: 38,
    description: "Simple and elegant Cardano browser wallet.",
    developer: "Berry Pool",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/namiwallet" },
  },
  {
    id: "yoroi",
    name: "Yoroi",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/yoroi",
    homepage: "https://yoroi-wallet.com",
    supportedChainFamilies: ["cardano"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "yoroi://",
    universalLink: "https://yoroi-wallet.com",
    appStoreUrl: "https://apps.apple.com/app/yoroi-wallet/id1468288179",
    playStoreUrl: "https://play.google.com/store/apps/details?id=co.jp.emurgo.yoroi",
    extensionUrl: "https://chromewebstore.google.com/detail/yoroi/ppbibelpcjmhbdihakflkdcocmkgbkbc",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 45,
    description: "Light Cardano wallet by EMURGO. One of the first Cardano wallets.",
    developer: "EMURGO",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/YoroiWallet" },
  },
];
