export const cosmosWallets = [
  {
    id: "keplr",
    name: "Keplr",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/keplr",
    homepage: "https://www.keplr.app",
    supportedChainFamilies: ["cosmos"],
    supportedChains: ["cosmos:cosmoshub-4", "cosmos:osmosis-1", "cosmos:juno-1", "cosmos:injective-1"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "keplrwallet://",
    universalLink: "https://www.keplr.app",
    appStoreUrl: "https://apps.apple.com/app/keplr-wallet/id1567119399",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.chainapsis.keplr",
    extensionUrl: "https://chromewebstore.google.com/detail/keplr/dmkamcknogkgcdfhhbddcghachkejeap",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 62,
    description: "The leading wallet for Cosmos/IBC ecosystem.",
    developer: "Chainapsis",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/keplrwallet", github: "https://github.com/chainapsis" },
  },
  {
    id: "leap",
    name: "Leap Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/leap",
    homepage: "https://www.leapwallet.io",
    supportedChainFamilies: ["cosmos", "evm"],
    supportedChains: ["cosmos:cosmoshub-4", "cosmos:osmosis-1", "eip155:1"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "leapcosmos://",
    universalLink: "https://www.leapwallet.io",
    appStoreUrl: "https://apps.apple.com/app/leap-cosmos-wallet/id1633501428",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.leapwallet.cosmos",
    extensionUrl: "https://chromewebstore.google.com/detail/leap-cosmos-wallet/fcfcfllfndlomdhbehjjcoimbgafcncg",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 50,
    description: "Cosmos ecosystem wallet with staking and IBC transfer support.",
    developer: "Leap Wallet",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/LeapWallet" },
  },
  {
    id: "station",
    name: "Station (Terra)",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/terra",
    homepage: "https://terra.money",
    supportedChainFamilies: ["cosmos"],
    supportedChains: ["cosmos:columbus-5", "cosmos:phoenix-1"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "station://",
    universalLink: "https://terra.money",
    appStoreUrl: "https://apps.apple.com/app/terra-station/id1589711895",
    playStoreUrl: "https://play.google.com/store/apps/details?id=earth.terra.station",
    extensionUrl: "https://chromewebstore.google.com/detail/terra-station/aiifbnmgebopokdgljpcbmolbbimefnp",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 29,
    description: "Official Terra ecosystem wallet.",
    developer: "Terraform Labs",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/terra_money" },
  },
  {
    id: "xdefi",
    name: "XDEFI Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/xdefi",
    homepage: "https://www.xdefi.io",
    supportedChainFamilies: ["evm", "bitcoin", "cosmos", "thorchain"],
    supportedChains: ["eip155:1", "eip155:56", "bip122:000000000019d6689c085ae165831e93", "cosmos:thorchain-mainnet-v1"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/xdefi-wallet/hmeobnfnfcbbkhdaccgchmejnfhpdgpn",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "io.xdefi",
    openSource: true,
    walletType: "hot",
    popularity: 43,
    description: "Multi-chain Web3 wallet with THORChain and Bitcoin support.",
    developer: "XDEFI",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/xdefi_wallet", github: "https://github.com/XDeFi-tech" },
  },
];
