export const emergingWallets = [
  {
    id: "clv-wallet",
    name: "CLV Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/clv",
    homepage: "https://clv.org",
    supportedChainFamilies: ["evm", "bitcoin", "polkadot"],
    supportedChains: ["eip155:1"],
    platforms: ["mobile"],
    deepLink: "clv://",
    universalLink: "https://clv.org",
    appStoreUrl: "https://apps.apple.com/app/clv-wallet/id1571005876",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.clv.wallet",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 15,
    description: "Multi-chain wallet by Clover Finance.",
    developer: "Clover Finance",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/clover_finance" },
  },
  {
    id: "tp-wallet",
    name: "TP Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tpwallet",
    homepage: "https://www.tpwallet.io",
    supportedChainFamilies: ["evm", "solana", "tron"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    deepLink: "tpoutside://",
    universalLink: "https://www.tpwallet.io",
    appStoreUrl: "https://apps.apple.com/app/tp-wallet/id1435673937",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.tokenpocket.tpwallet",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 21,
    description: "Multi-chain mobile wallet by TokenPocket team.",
    developer: "TP",
    yearFounded: 2018,
  },
  {
    id: "cool-wallet",
    name: "CoolWallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/coolwallet",
    homepage: "https://www.coolwallet.io",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "cardano", "polkadot", "cosmos", "aptos", "sui", "hedera"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile", "hardware"],
    deepLink: "coolwallet://",
    universalLink: "https://www.coolwallet.io",
    appStoreUrl: "https://apps.apple.com/app/coolwallet-s/id1464191401",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.coolbitx.cwsapp",
    supportsCinacoinV2: true,
    walletType: "cold",
    popularity: 32,
    description: "Bluetooth hardware wallet with mobile app.",
    developer: "CoolBitX",
    yearFounded: 2015,
    social: { twitter: "https://twitter.com/CoolBitX_" },
  },
  {
    id: "dcent",
    name: "D'CENT Biometric Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/dcent",
    homepage: "https://dcentwallet.com",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "cardano", "cosmos", "polkadot", "hedera", "xrpl"],
    supportedChains: ["eip155:1"],
    platforms: ["hardware"],
    deepLink: "dcent://",
    universalLink: "https://dcentwallet.com",
    appStoreUrl: "https://apps.apple.com/app/dcent-hardware-wallet/id1452898941",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.kr.iotrust.dcent.wallet",
    supportsCinacoinV2: true,
    walletType: "cold",
    popularity: 28,
    description: "Biometric hardware wallet with fingerprint authentication.",
    developer: "IoTrust",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/DcentWallet" },
  },
  {
    id: "keyring-pro",
    name: "Keyring Pro",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/keyring",
    homepage: "https://keyring.pro",
    supportedChainFamilies: ["evm", "solana"],
    supportedChains: ["eip155:1"],
    platforms: ["mobile"],
    deepLink: "keyring://",
    universalLink: "https://keyring.pro",
    appStoreUrl: "https://apps.apple.com/app/keyring-pro/id1583856512",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.keyring",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 17,
    description: "Secure multi-chain wallet for DeFi users.",
    developer: "Keyring",
    yearFounded: 2021,
  },
  {
    id: "infinitex",
    name: "Infinitex",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/infinitex",
    homepage: "https://infinitex.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile"],
    walletType: "smart_contract",
    supportsAccountAbstraction: true,
    popularity: 13,
    description: "Account abstraction wallet for gasless transactions.",
    developer: "Infinitex",
    yearFounded: 2023,
  },
  {
    id: "burner-wallet",
    name: "Burner Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/burner",
    homepage: "https://www.burnerwallet.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1"],
    platforms: ["web"],
    walletType: "hot",
];
