export const evmTier1Wallets = [
  {
    id: "metamask",
    name: "MetaMask",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/metamask",
    homepage: "https://metamask.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:56", "eip155:8453", "eip155:43114"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "metamask://",
    universalLink: "https://metamask.app.link",
    appStoreUrl: "https://apps.apple.com/app/metamask/id1438668043",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.metamask",
    extensionUrl: "https://chromewebstore.google.com/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "io.metamask",
    openSource: true,
    walletType: "hot",
    popularity: 99,
    description: "The most popular Ethereum wallet, available as a browser extension and mobile app.",
    developer: "ConsenSys",
    yearFounded: 2016,
    social: { twitter: "https://twitter.com/MetaMask", github: "https://github.com/MetaMask" },
  },
  {
    id: "rainbow",
    name: "Rainbow",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/rainbow",
    homepage: "https://rainbow.me",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:8453"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "rainbow://",
    universalLink: "https://rnbwapp.com",
    appStoreUrl: "https://apps.apple.com/app/rainbow-ethereum-wallet/id1457119021",
    playStoreUrl: "https://play.google.com/store/apps/details?id=me.rainbow",
    extensionUrl: "https://chromewebstore.google.com/detail/rainbow/opfgelmcmbiajamepnmloijbpoleiama",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "me.rainbow",
    openSource: true,
    walletType: "hot",
    popularity: 82,
    description: "A fun, friendly Ethereum wallet focused on DeFi and NFTs.",
    developer: "Rainbow",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/rainbowdotme", github: "https://github.com/rainbow-me" },
  },
  {
    id: "coinbase-wallet",
    name: "Coinbase Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/coinbase",
    homepage: "https://www.coinbase.com/wallet",
    supportedChainFamilies: ["evm", "solana"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:8453", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "cbwallet://",
    universalLink: "https://go.cb-w.com",
    appStoreUrl: "https://apps.apple.com/app/coinbase-wallet/id1278383455",
    playStoreUrl: "https://play.google.com/store/apps/details?id=org.toshi",
    extensionUrl: "https://chromewebstore.google.com/detail/coinbase-wallet/hnfanknocfeofbddgcijnmhnfnkdnaad",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "com.coinbase.wallet",
    openSource: false,
    walletType: "hot",
    popularity: 88,
    description: "Self-custody wallet from Coinbase with multi-chain support.",
    developer: "Coinbase",
    yearFounded: 2017,
    social: { twitter: "https://twitter.com/CoinbaseWallet" },
  },
  {
    id: "trust-wallet",
    name: "Trust Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/trust",
    homepage: "https://trustwallet.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "cosmos", "aptos", "sui", "ton", "hedera", "near", "starknet", "xrpl"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137", "eip155:43114", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["mobile", "browser_extension"],
    deepLink: "trust://",
    universalLink: "https://link.trustwallet.com",
    appStoreUrl: "https://apps.apple.com/app/trust-crypto-bitcoin-wallet/id1288339409",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.wallet.crypto.trustapp",
    extensionUrl: "https://chromewebstore.google.com/detail/trust-wallet/egjidjbpglichdcondbcbdnbbppckpln",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "com.trustwallet.app",
    openSource: true,
    walletType: "hot",
    popularity: 91,
    description: "Multi-chain crypto wallet supporting 65+ chains. Official Binance wallet.",
    developer: "Binance",
    yearFounded: 2017,
    social: { twitter: "https://twitter.com/TrustWallet", github: "https://github.com/trustwallet" },
  },
  {
    id: "zerion",
    name: "Zerion",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/zerion",
    homepage: "https://zerion.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:8453"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "zerion://",
    universalLink: "https://app.zerion.io",
    appStoreUrl: "https://apps.apple.com/app/zerion/id1456732164",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.zerion.android",
    extensionUrl: "https://chromewebstore.google.com/detail/zerion/klghhnkeealcohjajnjjcgbogebmnpma",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "io.zerion.wallet",
    openSource: true,
    walletType: "hot",
    popularity: 72,
    description: "Smart wallet with built-in DeFi portfolio management and swaps.",
    developer: "Zerion",
    yearFounded: 2016,
    social: { twitter: "https://twitter.com/zerion_io", github: "https://github.com/zeriontech" },
  },
  {
    id: "rabby",
    name: "Rabby Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/rabby",
    homepage: "https://rabby.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:56", "eip155:8453", "eip155:43114"],
    platforms: ["browser_extension", "desktop"],
    deepLink: "rabby://",
    universalLink: "https://rabby.io",
    appStoreUrl: "https://apps.apple.com/app/rabby-wallet/id1628947930",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.debank.rabby",
    extensionUrl: "https://chromewebstore.google.com/detail/rabby-wallet/acmacodkjbdgmoleebolmdjonilkdbch",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "io.rabby",
    openSource: true,
    walletType: "hot",
    popularity: 70,
    description: "DeFi-focused wallet with superior security and multi-chain support. By DeBank.",
    developer: "DeBank",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/Rabby_io", github: "https://github.com/RabbyHub" },
  },
  {
    id: "phantom",
    name: "Phantom",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/phantom",
    homepage: "https://phantom.app",
    supportedChainFamilies: ["solana", "evm", "bitcoin"],
    supportedChains: ["solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", "eip155:1", "eip155:137", "eip155:8453", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "phantom://",
    universalLink: "https://phantom.app",
    appStoreUrl: "https://apps.apple.com/app/phantom-crypto-wallet/id1598432977",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.phantom.app",
    extensionUrl: "https://chromewebstore.google.com/detail/phantom/bfnaelmomeimhlpmgjnjophhpkkoljpa",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "app.phantom",
    openSource: false,
    walletType: "hot",
    popularity: 90,
    description: "The leading Solana wallet, now multi-chain with Ethereum and Bitcoin support.",
    developer: "Phantom",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/phantom", github: "https://github.com/phantom" },
  },
  {
    id: "ledger",
    name: "Ledger Live",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/ledger",
    homepage: "https://www.ledger.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "polkadot", "cosmos", "near", "hedera", "algorand", "stellar", "cardano", "tron", "tezos", "elrond", "flow", "starknet"],
    platforms: ["mobile", "desktop", "hardware"],
    deepLink: "ledgerlive://",
    universalLink: "https://ledgerlive.onelink.me",
    appStoreUrl: "https://apps.apple.com/app/ledger-live/id1361671700",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.ledger.live",
    supportsWalletConnectV2: true,
    supportsEIP6963: false,
    rdns: "com.ledger.live",
    walletType: "cold",
    popularity: 85,
    description: "Hardware wallet companion app supporting 5500+ cryptocurrencies.",
    developer: "Ledger",
    yearFounded: 2014,
    social: { twitter: "https://twitter.com/Ledger", github: "https://github.com/LedgerHQ" },
  },
  {
    id: "trezor",
    name: "Trezor Suite",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/trezor",
    homepage: "https://trezor.io",
    supportedChainFamilies: ["evm", "bitcoin", "cardano", "stellar", "tezos"],
    platforms: ["desktop", "web", "hardware"],
    supportsWalletConnectV2: false,
    openSource: true,
    walletType: "cold",
    popularity: 78,
    description: "Hardware wallet with desktop and web interface. Pioneer of hardware wallets.",
    developer: "SatoshiLabs",
    yearFounded: 2013,
    social: { twitter: "https://twitter.com/Trezor", github: "https://github.com/trezor" },
  },
  {
    id: "uniswap-wallet",
    name: "Uniswap Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/uniswap",
    homepage: "https://wallet.uniswap.org",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:8453"],
    platforms: ["mobile"],
    deepLink: "uniswap://",
    universalLink: "https://wallet.uniswap.org",
    appStoreUrl: "https://apps.apple.com/app/uniswap-wallet/id6443944476",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.uniswap.mobile",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    supportsAccountAbstraction: true,
    popularity: 65,
    description: "Self-custody mobile wallet by Uniswap with built-in swap and limit orders.",
    developer: "Uniswap",
    yearFounded: 2023,
    social: { twitter: "https://twitter.com/Uniswap", github: "https://github.com/Uniswap" },
  },
  {
    id: "okx-wallet",
    name: "OKX Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/okx",
    homepage: "https://www.okx.com/web3",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "cosmos", "aptos", "sui", "ton", "starknet"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "okex://",
    universalLink: "https://www.okx.com",
    appStoreUrl: "https://apps.apple.com/app/okx/id1484717480",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.okinc.okex",
    extensionUrl: "https://chromewebstore.google.com/detail/okx-wallet/mcohilncbfahbmgdjkbpemcciiolgcge",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "com.okex",
    walletType: "hot",
    popularity: 75,
    description: "Multi-chain Web3 wallet from OKX exchange.",
    developer: "OKX",
    yearFounded: 2017,
    social: { twitter: "https://twitter.com/okx" },
  },
  {
    id: "imtoken",
    name: "imToken",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/imtoken",
    homepage: "https://token.im",
    supportedChainFamilies: ["evm", "bitcoin", "cosmos"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["mobile"],
    deepLink: "imtokenv2://",
    universalLink: "https://token.im",
    appStoreUrl: "https://apps.apple.com/app/imtoken/id1594723776",
    playStoreUrl: "https://play.google.com/store/apps/details?id=im.token.app",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 68,
    description: "One of the earliest Ethereum mobile wallets, popular in Asia.",
    developer: "imToken",
    yearFounded: 2016,
    social: { twitter: "https://twitter.com/imTokenOfficial" },
  },
  {
    id: "tokenpocket",
    name: "TokenPocket",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tokenpocket",
    homepage: "https://www.tokenpocket.pro",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "cosmos", "tron", "aptos", "near"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137", "eip155:43114"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "tpoutside://",
    universalLink: "https://www.tokenpocket.pro",
    appStoreUrl: "https://apps.apple.com/app/tokenpocket/id1436002486",
    playStoreUrl: "https://play.google.com/store/apps/details?id=vip.mytokenpocket",
    extensionUrl: "https://chromewebstore.google.com/detail/tokenpocket/mfgccjchihfkkindfppnaooecgfnefff",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 66,
    description: "Multi-chain wallet supporting 20+ public blockchains.",
    developer: "TokenPocket",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/TokenPocket_TP" },
  },
  {
    id: "safepal",
    name: "SafePal",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/safepal",
    homepage: "https://www.safepal.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "tron"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137"],
    platforms: ["browser_extension", "mobile", "hardware"],
    deepLink: "safepal://",
    universalLink: "https://www.safepal.com",
    appStoreUrl: "https://apps.apple.com/app/safepal/id1541662925",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.safepal.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/safepal/amkmjjmmflddogmhpjlojimipdpfnfji",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 55,
    description: "Hardware and software wallet backed by Binance Labs.",
    developer: "SafePal",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/SafePalWallet" },
  },
  {
    id: "bitget-wallet",
    name: "Bitget Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/bitget",
    homepage: "https://web3.bitget.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "tron", "aptos", "sui", "near", "ton"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137", "eip155:43114"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "bitkeep://",
    universalLink: "https://web3.bitget.com",
    appStoreUrl: "https://apps.apple.com/app/bitget-wallet/id1395301115",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.bitkeep.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/bitget-wallet/jiidiaatihmmhchjgbamgpeklnpdistg",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "com.bitget.wallet",
    walletType: "hot",
    popularity: 60,
    description: "Multi-chain Web3 wallet by Bitget (formerly BitKeep).",
    developer: "Bitget",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/BitgetWallet" },
  },
  {
    id: "exodus",
    name: "Exodus",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/exodus",
    homepage: "https://www.exodus.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "cardano", "stellar", "algorand", "tron", "hedera", "near", "cosmos", "aptos", "ton"],
    supportedChains: ["eip155:1", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["desktop", "mobile"],
    deepLink: "exodus://",
    universalLink: "https://www.exodus.com",
    appStoreUrl: "https://apps.apple.com/app/exodus-crypto-wallet/id1277214541",
    playStoreUrl: "https://play.google.com/store/apps/details?id=exodusmovement.exodus",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 63,
    description: "Beautiful multi-crypto wallet with built-in exchange. Desktop-first design.",
    developer: "Exodus Movement",
    yearFounded: 2015,
    social: { twitter: "https://twitter.com/ExodusWallet" },
  },
  {
    id: "solflare",
    name: "Solflare",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/solflare",
    homepage: "https://solflare.com",
    supportedChainFamilies: ["solana"],
    supportedChains: ["solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "solflare://",
    universalLink: "https://solflare.com",
    appStoreUrl: "https://apps.apple.com/app/solflare-wallet/id1580908064",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.solflare.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/solflare-wallet/bhhhlbepdkbapadjdnnojkbgioiodbic",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 58,
    description: "The first Solana wallet with full staking and DeFi integration.",
    developer: "Solflare",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/solflare_wallet", github: "https://github.com/solflare-wallet" },
  },
  {
    id: "backpack",
    name: "Backpack",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/backpack",
    homepage: "https://backpack.app",
    supportedChainFamilies: ["solana", "evm"],
    supportedChains: ["solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", "eip155:1"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "backpack://",
    universalLink: "https://backpack.app",
    appStoreUrl: "https://apps.apple.com/app/backpack/id6445964121",
    playStoreUrl: "https://play.google.com/store/apps/details?id=app.backpack.mobile",
    extensionUrl: "https://chromewebstore.google.com/detail/backpack/aflkmfhebedbjioipglgcbcmnbpgliof",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "app.backpack",
    openSource: true,
    walletType: "hot",
    popularity: 54,
    description: "Crypto wallet and xNFT browser by the founders of Magic Eden.",
    developer: "Coral / Magic Eden",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/Backpack", github: "https://github.com/coral-xyz" },
  },
  {
    id: "walletconnect",
    name: "WalletConnect",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/walletconnect",
    homepage: "https://walletconnect.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161"],
    platforms: ["mobile"],
    deepLink: "wc://",
    universalLink: "https://walletconnect.com",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 50,
    description: "Reference wallet implementation of the WalletConnect protocol.",
    developer: "WalletConnect Foundation",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/WalletConnect" },
  },
];
