export const evmMoreWallets = [
  {
    id: "onekey",
    name: "OneKey",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/onekey",
    homepage: "https://onekey.so",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "aptos", "sui", "near", "cosmos", "cardano", "ton"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["browser_extension", "mobile", "desktop", "hardware"],
    deepLink: "onekey://",
    universalLink: "https://onekey.so",
    appStoreUrl: "https://apps.apple.com/app/onekey/id1609559473",
    playStoreUrl: "https://play.google.com/store/apps/details?id=so.onekey.app.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/onekey/jnmbobjmhlngoefaiojfljckilhhlhcj",
    supportsCinacoinV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 50,
    description: "Open-source multi-chain wallet with hardware wallet support.",
    developer: "OneKey",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/OneKeyHQ", github: "https://github.com/OneKeyHQ" },
  },
  {
    id: "atomic",
    name: "Atomic Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/atomic",
    homepage: "https://atomicwallet.io",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "cardano", "stellar", "algorand", "tron", "hedera", "cosmos"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["desktop", "mobile"],
    deepLink: "atomic://",
    universalLink: "https://atomicwallet.io",
    appStoreUrl: "https://apps.apple.com/app/atomic-wallet/id1438600830",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.atomicwallet",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 35,
    description: "Multi-currency non-custodial wallet with built-in exchange.",
    developer: "Atomic Wallet",
    yearFounded: 2017,
    social: { twitter: "https://twitter.com/AtomicWallet" },
  },
  {
    id: "guarda",
    name: "Guarda Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/guarda",
    homepage: "https://guarda.com",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "cardano", "tron", "stellar", "polkadot", "cosmos", "near", "algorand", "hedera"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["browser_extension", "mobile", "desktop", "web"],
    deepLink: "guarda://",
    universalLink: "https://guarda.com",
    appStoreUrl: "https://apps.apple.com/app/guarda-crypto-wallet/id1372359351",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.crypto.multiwallet",
    extensionUrl: "https://chromewebstore.google.com/detail/guarda-wallet/hpglfhgfnhbgfhgfhgfhgfhgfhgfhgfh",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 31,
    description: "Multi-platform wallet supporting 50+ blockchains.",
    developer: "Guarda",
    yearFounded: 2017,
    social: { twitter: "https://twitter.com/Guarda_wallet" },
  },
  {
    id: "infinity-wallet",
    name: "Infinity Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/infinity",
    homepage: "https://infinitywallet.io",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "polkadot", "cosmos", "near"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["desktop"],
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 20,
    description: "Desktop multi-chain wallet with hardware support.",
    developer: "Infinity Wallet",
    yearFounded: 2022,
  },
  {
    id: "fox-wallet",
    name: "FoxWallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/foxwallet",
    homepage: "https://foxwallet.com",
    supportedChainFamilies: ["evm", "bsc", "harmony", "cronos"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    deepLink: "foxwallet://",
    universalLink: "https://foxwallet.com",
    appStoreUrl: "https://apps.apple.com/app/foxwallet/id1614001480",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.foxwallet",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 19,
    description: "Web3 mobile wallet with DeFi focus.",
    developer: "FoxWallet",
    yearFounded: 2021,
  },
  {
    id: "pillect",
    name: "Pillect Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/pillect",
    homepage: "https://pillect.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile"],
    deepLink: "pillect://",
    universalLink: "https://pillect.com",
    appStoreUrl: "https://apps.apple.com/app/pillect/id1614001481",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.pillect",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 15,
    description: "Multi-chain DeFi wallet.",
    developer: "Pillect",
    yearFounded: 2022,
  },
  {
    id: "tavern-wallet",
    name: "Tavern Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tavern",
    homepage: "https://tavernwallet.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1"],
    platforms: ["web"],
    walletType: "hot",
    popularity: 12,
    description: "Simple web wallet for quick transactions.",
    developer: "Tavern",
    yearFounded: 2023,
  },
  {
    id: "cyberconnect",
    name: "CyberConnect Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/cyberconnect",
    homepage: "https://cyberconnect.me",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["web"],
    supportsCinacoinV2: true,
    walletType: "social",
    popularity: 28,
    description: "Social graph wallet for decentralized social.",
    developer: "CyberConnect",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/CyberConnectHQ" },
  },
  {
    id: "mask-network",
    name: "Mask Network",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/mask",
    homepage: "https://mask.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/mask-network/dbeefadbfjcbmgfnfkfhfjcbmgfnfkfh",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 24,
    description: "Web3 bridge connecting social platforms to decentralized networks.",
    developer: "Mask Network",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/realMaskNetwork" },
  },
  {
    id: "gem-wallet",
    name: "Gem Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/gemwallet",
    homepage: "https://gemwallet.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "aptos", "cosmos", "near"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile"],
    deepLink: "gemwallet://",
    universalLink: "https://gemwallet.com",
    appStoreUrl: "https://apps.apple.com/app/gem-wallet-crypto-defi/id6444634568",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.gemwallet",
    supportsCinacoinV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 25,
    description: "Open-source multi-chain mobile wallet with privacy focus.",
    developer: "Gem Wallet",
    yearFounded: 2023,
    social: { twitter: "https://twitter.com/gemwalletcom", github: "https://github.com/gemwalletcom" },
  },
  {
    id: "zengo",
    name: "ZenGo",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/zengo",
    homepage: "https://zengo.com",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "polkadot", "cosmos", "ton", "near", "algorand", "hedera", "flow"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile"],
    deepLink: "zengo://",
    universalLink: "https://zengo.com",
    appStoreUrl: "https://apps.apple.com/app/zengo-crypto-nft-wallet/id1475296939",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.zengo.wallet",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 43,
    description: "Seedless wallet with biometric MPC security. No private keys to lose.",
    developer: "ZenGo",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/ZenGo" },
  },
  {
    id: "cryptocom",
    name: "Crypto.com DeFi Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/cryptocom",
    homepage: "https://crypto.com/defi-wallet",
    supportedChainFamilies: ["evm", "cosmos"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile", "browser_extension"],
    deepLink: "cryptowallet://",
    universalLink: "https://crypto.com/defi-wallet",
    appStoreUrl: "https://apps.apple.com/app/crypto-com-defi-wallet/id1512011270",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.crypto.defiwallet",
    extensionUrl: "https://chromewebstore.google.com/detail/crypto-com-defi-wallet/hfhgkbdalhbflcmkfhfljcbmgfnfkfh",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 49,
    description: "DeFi wallet by Crypto.com with multi-chain support.",
    developer: "Crypto.com",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/cryptocom" },
  },
  {
    id: "binance-wallet",
    name: "Binance Web3 Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/binance",
    homepage: "https://www.binance.com/web3wallet",
    supportedChainFamilies: ["evm", "solana", "bitcoin"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    appStoreUrl: "https://apps.apple.com/app/binance/id1436011491",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.binance.dev",
    supportsCinacoinV2: true,
    walletType: "custodial",
    popularity: 65,
    description: "Web3 wallet integrated into the Binance app.",
    developer: "Binance",
    yearFounded: 2023,
    social: { twitter: "https://twitter.com/binance" },
  },
  {
    id: "block-wallet",
    name: "BlockWallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/blockwallet",
    homepage: "https://blockwallet.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/blockwallet/iffmfpagmhkgffgffgfhgfhgfhgfhgfh",
    supportsCinacoinV2: true,
    supportsEIP6963: true,
    rdns: "io.blockwallet",
    openSource: true,
    walletType: "hot",
    popularity: 18,
    description: "Privacy-focused fork of MetaMask with zero tracking.",
    developer: "BlockWallet",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/BlockWallet_", github: "https://github.com/block-wallet" },
  },
  {
    id: "liquality",
    name: "Liquality Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/liquality",
    homepage: "https://liquality.io",
    supportedChainFamilies: ["evm", "bitcoin", "near"],
    supportedChains: ["eip155:1", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/liquality-wallet/kpfopkcmahbgfmjfcbfclmfhfgbfhcje",
    supportsCinacoinV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 16,
    description: "Multi-chain wallet with atomic swap capability.",
    developer: "Liquality",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/LiqualityIO" },
  },
  {
    id: "unstoppable",
    name: "Unstoppable Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/unstoppable",
    homepage: "https://unstoppable.money",
    supportedChainFamilies: ["evm", "bitcoin", "solana", "cardano", "polkadot", "cosmos"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    deepLink: "unstoppable://",
    universalLink: "https://unstoppable.money",
    appStoreUrl: "https://apps.apple.com/app/unstoppable-crypto-wallet/id1447619907",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.horizontalsystems.bankwallet",
    openSource: true,
    walletType: "hot",
    popularity: 27,
    description: "Open-source multi-chain wallet focused on privacy and security.",
    developer: "Horizontal Systems",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/UnstoppableByHS", github: "https://github.com/horizontalsystems" },
  },
  {
    id: "pocket-universe",
    name: "Pocket Universe",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/pocketuniverse",
    homepage: "https://www.pocketuniverse.app",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/pocket-universe/epapihdplmajcdmbkfedegpdgcgkdmfi",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 22,
    description: "Security-focused wallet that simulates transactions before signing.",
    developer: "Pocket Universe",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/pocketuniverse3" },
  },
  {
    id: "ripio",
    name: "Ripio Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/ripio",
    homepage: "https://ripio.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile"],
    deepLink: "ripio://",
    universalLink: "https://ripio.com",
    appStoreUrl: "https://apps.apple.com/app/ripio/id1447046828",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.ripio",
    walletType: "hot",
    popularity: 14,
    description: "Latin American focused crypto wallet and exchange.",
    developer: "Ripio",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/RipioInc" },
  },
  {
    id: "wallacy",
    name: "Wallacy",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/wallacy",
    homepage: "https://wallacy.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    walletType: "hot",
    popularity: 10,
    description: "Simple mobile crypto wallet.",
    developer: "Wallacy",
    yearFounded: 2022,
  },
];
