export const evmTier2Wallets = [
  {
    id: "frame",
    name: "Frame",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/frame",
    homepage: "https://frame.sh",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10"],
    platforms: ["desktop"],
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "sh.frame",
    openSource: true,
    walletType: "hot",
    popularity: 45,
    description: "Fast, privacy-focused Ethereum desktop wallet.",
    developer: "Frame",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/0xFrame", github: "https://github.com/floating" },
  },
  {
    id: "enkrypt",
    name: "Enkrypt",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/enkrypt",
    homepage: "https://www.enkrypt.com",
    supportedChainFamilies: ["evm", "polkadot"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/enkrypt-eth-polkadot-web/kkpllkodjeloidieedojogacfhpaihoh",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "com.enkrypt",
    walletType: "hot",
    popularity: 40,
    description: "Multi-chain wallet extension for Ethereum and Polkadot by MyCrypto.",
    developer: "MyCrypto",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/enkrypt" },
  },
  {
    id: "taho",
    name: "Taho",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tally",
    homepage: "https://taho.xyz",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10", "eip155:8453"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/taho/eajafomhmkipbjmfmhebemolkcicgfmd",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "xyz.taho",
    openSource: true,
    walletType: "hot",
    popularity: 42,
    description: "Community-owned, open-source Ethereum wallet. Previously Tally.",
    developer: "Taho",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/taho_xyz", github: "https://github.com/tahowallet" },
  },
  {
    id: "safeheron",
    name: "Safeheron",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/safeheron",
    homepage: "https://www.safeheron.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/safeheron/aiaghdjafodppgppdkgbmmgdcehbfmke",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 35,
    description: "Open-source self-custody wallet with MPC for secure key management.",
    developer: "Safeheron",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/Safeheron" },
  },
  {
    id: "ronin",
    name: "Ronin Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/ronin",
    homepage: "https://wallet.roninchain.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:2020"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "ronin://",
    universalLink: "https://wallet.roninchain.com",
    appStoreUrl: "https://apps.apple.com/app/ronin-wallet/id1616597823",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.skymavis.roninwallet",
    extensionUrl: "https://chromewebstore.google.com/detail/ronin-wallet/fnlmbmmdngkddcabnbgbommkcbjgokhj",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 52,
    description: "Official wallet for the Ronin blockchain (Axie Infinity ecosystem).",
    developer: "Sky Mavis",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/RoninWallet" },
  },
  {
    id: "core",
    name: "Core",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/core",
    homepage: "https://core.app",
    supportedChainFamilies: ["evm", "bitcoin"],
    supportedChains: ["eip155:1", "eip155:1116", "bip122:000000000019d6689c085ae165831e93"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "core://",
    universalLink: "https://core.app",
    appStoreUrl: "https://apps.apple.com/app/core-wallet/id6443857931",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.avaxwallet",
    extensionUrl: "https://chromewebstore.google.com/detail/core-crypto-wallet-nft-ex/agoakfejjabomempkjlepdflaleeobhb",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 48,
    description: "Multi-chain browser wallet by Avalanche (Core Web3 Wallet).",
    developer: "Avalanche / Core",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/CryptoCoreApp" },
  },
  {
    id: "subwallet",
    name: "SubWallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/subwallet",
    homepage: "https://subwallet.app",
    supportedChainFamilies: ["evm", "polkadot"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "subwallet://",
    universalLink: "https://subwallet.app",
    appStoreUrl: "https://apps.apple.com/app/subwallet/id1608591765",
    playStoreUrl: "https://play.google.com/store/apps/details?id=app.subwallet.mobile",
    extensionUrl: "https://chromewebstore.google.com/detail/subwallet-polkadot-wallet/onhogfjeacnfoofkfgppdlbmlmnplgbn",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 36,
    description: "Multi-chain wallet for Polkadot and Ethereum ecosystems.",
    developer: "SubWallet",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/SubWalletApp", github: "https://github.com/Koniverse" },
  },
  {
    id: "talisman",
    name: "Talisman",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/talisman",
    homepage: "https://talisman.xyz",
    supportedChainFamilies: ["evm", "polkadot"],
    supportedChains: ["eip155:1"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/talisman-polkadot-wallet/fijngjgcjhjmmpcmkeiomlglpeiijkld",
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "xyz.talisman",
    openSource: true,
    walletType: "hot",
    popularity: 34,
    description: "Ethereum and Polkadot wallet focused on security and UX.",
    developer: "Talisman",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/talismansmh", github: "https://github.com/TalismanSociety" },
  },
  {
    id: "nifty",
    name: "Nifty Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/nifty",
    homepage: "https://niftywallet.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/nifty-wallet/jbdaocneiiagmjnhpegcmpjkhggoicbf",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 30,
    description: "Multi-chain browser wallet with built-in swap and bridge.",
    developer: "Nifty",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/NiftyWallet" },
  },
  {
    id: "math-wallet",
    name: "Math Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/math",
    homepage: "https://mathwallet.org",
    supportedChainFamilies: ["evm", "solana", "cosmos", "polkadot", "near", "tron"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "mathwallet://",
    universalLink: "https://mathwallet.org",
    appStoreUrl: "https://apps.apple.com/app/math-wallet/id1444698701",
    playStoreUrl: "https://play.google.com/store/apps/details?id=mathwallet.android",
    extensionUrl: "https://chromewebstore.google.com/detail/math-wallet/afbcbjpbjdadlapmclkcinemddpiplgm",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 33,
    description: "Universal multi-chain wallet supporting 10+ blockchain ecosystems.",
    developer: "MathWallet",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/Mathwallet" },
  },
  {
    id: "huobi-wallet",
    name: "HTX Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/huobi",
    homepage: "https://www.htx.com",
    supportedChainFamilies: ["evm", "tron"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    appStoreUrl: "https://apps.apple.com/app/huobi-global/id1390818779",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.huobi.global",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 32,
    description: "HTX exchange integrated multi-chain wallet.",
    developer: "HTX",
    yearFounded: 2013,
    social: { twitter: "https://twitter.com/HTX_Global" },
  },
];
