export const evmTier3Wallets = [
  {
    id: "onto",
    name: "ONTO Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/onto",
    homepage: "https://onto.app",
    supportedChainFamilies: ["evm", "solana", "polkadot", "ontology", "eos"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    deepLink: "ontopro://",
    universalLink: "https://onto.app",
    appStoreUrl: "https://apps.apple.com/app/onto/id1436019325",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.github.ontio.onto",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 28,
    description: "Ontology-based multi-chain identity wallet.",
    developer: "Ontology",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/OntologyNetwork" },
  },
  {
    id: "atoken",
    name: "AToken",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/atoken",
    homepage: "https://atoken.com",
    supportedChainFamilies: ["evm", "tron"],
    supportedChains: ["eip155:1", "eip155:56"],
    platforms: ["mobile"],
    deepLink: "atoken://",
    universalLink: "https://atoken.com",
    appStoreUrl: "https://apps.apple.com/app/atoken/id1435488960",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.alink.aATP",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 22,
    description: "Multi-chain mobile wallet with staking support.",
    developer: "AToken",
    yearFounded: 2018,
  },
  {
    id: "coin98",
    name: "Coin98 Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/coin98",
    homepage: "https://coin98.com",
    supportedChainFamilies: ["evm", "solana", "cosmos", "near", "terra", "harmony", "kcc"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "coin98://",
    universalLink: "https://coin98.com",
    appStoreUrl: "https://apps.apple.com/app/coin98-super-app/id1561947711",
    playStoreUrl: "https://play.google.com/store/apps/details?id=coin98.crypto.finance.media",
    extensionUrl: "https://chromewebstore.google.com/detail/coin98-wallet/aeachknmefphepccionboohckonoeemg",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 44,
    description: "DeFi-focused multi-chain wallet with built-in DEX aggregator.",
    developer: "Coin98",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/coin98_wallet" },
  },
  {
    id: "frontier",
    name: "Frontier",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/frontier",
    homepage: "https://www.frontier.xyz",
    supportedChainFamilies: ["evm", "solana", "cosmos", "terra", "harmony", "near"],
    supportedChains: ["eip155:1", "eip155:56", "eip155:137"],
    platforms: ["browser_extension", "mobile", "hardware"],
    deepLink: "frontier://",
    universalLink: "https://www.frontier.xyz",
    appStoreUrl: "https://apps.apple.com/app/frontier-crypto-defi-wallet/id1499596111",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.frontierwallet",
    extensionUrl: "https://chromewebstore.google.com/detail/frontier-wallet/kppfdiipphfccemcignhifpjkapfbihd",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 38,
    description: "Multi-chain DeFi wallet with Ledger hardware integration.",
    developer: "Frontier",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/FrontierDotXYZ" },
  },
  {
    id: "grindery",
    name: "Grindery Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/grindery",
    homepage: "https://www.grindery.com",
    supportedChainFamilies: ["evm", "solana"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["mobile"],
    deepLink: "grindery://",
    universalLink: "https://www.grindery.com",
    appStoreUrl: "https://apps.apple.com/app/grindery-wallet/id6443488748",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.grindery.wallet",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 18,
    description: "Wallet for the Grindery multi-chain ecosystem.",
    developer: "Grindery",
    yearFounded: 2022,
  },
  {
    id: "fireblocks",
    name: "Fireblocks",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/fireblocks",
    homepage: "https://www.fireblocks.com",
    supportedChainFamilies: ["evm", "solana", "bitcoin", "near", "stellar"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["web"],
    supportsCinacoinV2: true,
    walletType: "custodial",
    popularity: 46,
    description: "Enterprise-grade digital asset custody platform.",
    developer: "Fireblocks",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/fireblocks_io" },
  },
  {
    id: "sequence",
    name: "Sequence Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/sequence",
    homepage: "https://sequence.xyz",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:8453"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "sequence://",
    universalLink: "https://sequence.xyz",
    appStoreUrl: "https://apps.apple.com/app/sequence-wallet/id1627894683",
    playStoreUrl: "https://play.google.com/store/apps/details?id=xyz.sequence.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/sequence-wallet/oknboefhahgkmjlbdlhnhdmokbhgaham",
    supportsCinacoinV2: true,
    supportsEIP6963: true,
    rdns: "xyz.sequence",
    walletType: "smart_contract",
    supportsAccountAbstraction: true,
    popularity: 37,
    description: "Smart contract wallet built for gaming and NFTs. By Horizon (Immutable).",
    developer: "Immutable",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/0xSequence" },
  },
  {
    id: "ambire",
    name: "Ambire Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/ambire",
    homepage: "https://www.ambire.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:10"],
    platforms: ["browser_extension", "web"],
    extensionUrl: "https://chromewebstore.google.com/detail/ambire-smart-wallet/kpckgngjbnenjjingobdgcmbkfbhcbcf",
    supportsCinacoinV2: true,
    walletType: "smart_contract",
    supportsAccountAbstraction: true,
    popularity: 26,
    description: "Open-source smart contract wallet with gasless transactions.",
    developer: "Ambire",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/AmbireWallet", github: "https://github.com/AmbireTech" },
  },
  {
    id: "loopring",
    name: "Loopring Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/loopring",
    homepage: "https://loopring.io",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1"],
    platforms: ["mobile"],
    deepLink: "loopring://",
    universalLink: "https://loopring.io",
    appStoreUrl: "https://apps.apple.com/app/loopring-wallet/id1558659968",
    playStoreUrl: "https://play.google.com/store/apps/details?id=loopring.org",
    supportsCinacoinV2: true,
    walletType: "smart_contract",
    popularity: 25,
    description: "ZK rollup Layer 2 wallet for Ethereum with low-fee trading.",
    developer: "Loopring",
    yearFounded: 2017,
    social: { twitter: "https://twitter.com/loopringorg" },
  },
  {
    id: "argent",
    name: "Argent",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/argent",
    homepage: "https://www.argent.xyz",
    supportedChainFamilies: ["evm", "starknet"],
    supportedChains: ["eip155:1"],
    platforms: ["mobile"],
    deepLink: "argent://",
    universalLink: "https://argent.xyz",
    appStoreUrl: "https://apps.apple.com/app/argent/id1358741812",
    playStoreUrl: "https://play.google.com/store/apps/details?id=im.argent.contractwalletclient",
    supportsCinacoinV2: true,
    walletType: "smart_contract",
    supportsAccountAbstraction: true,
    popularity: 41,
    description: "Smart contract wallet for Ethereum and Starknet with account recovery.",
    developer: "Argent",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/argentHQ" },
  },
];
