export const gamingNftWallets = [
  {
    id: "gamestop",
    name: "GameStop Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/gamestop",
    homepage: "https://nft.gamestop.com/wallet",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "gamestop://",
    universalLink: "https://nft.gamestop.com",
    appStoreUrl: "https://apps.apple.com/app/gamestop-wallet/id1618139316",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.gamestop.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/gamestop-wallet/annmjhdbfhjbkdmhjhdbkdmhjhdbkdmh",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 26,
    description: "NFT-focused wallet by GameStop.",
    developer: "GameStop",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/GameStop" },
  },
  {
    id: "eloop",
    name: "ELOOP Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/eloop",
    homepage: "https://eloop.wallet",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1"],
    platforms: ["mobile"],
    walletType: "hot",
    popularity: 11,
    description: "Gaming-focused Web3 wallet.",
    developer: "ELOOP",
    yearFounded: 2023,
  },
];
