export const hederaWallets = [
  {
    id: "blade",
    name: "Blade Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/blade",
    homepage: "https://blade.me",
    supportedChainFamilies: ["hedera"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/blade-hedera-wallet/mcocohpcbgafiiikaifmmgldfomcjfep",
    walletType: "hot",
    popularity: 23,
    description: "Hedera wallet with staking and DeFi support.",
    developer: "Blade",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/Blade_Hedera" },
  },
  {
    id: "hashpack",
    name: "HashPack",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/hashpack",
    homepage: "https://www.hashpack.app",
    supportedChainFamilies: ["hedera"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "hashpack://",
    universalLink: "https://www.hashpack.app",
    appStoreUrl: "https://apps.apple.com/app/hashpack/id6443840635",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com/hashpack/app",
    extensionUrl: "https://chromewebstore.google.com/detail/hashpack/gjagmgiddbbiigjhllhcfpglbgphicgj",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 30,
    description: "Most popular Hedera wallet with token management.",
    developer: "HashPack",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/itshashpack" },
  },
];
