export const nearWallets = [
  {
    id: "here-wallet",
    name: "HERE Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/here",
    homepage: "https://www.herewallet.app",
    supportedChainFamilies: ["near"],
    platforms: ["mobile", "browser_extension"],
    deepLink: "herewallet://",
    universalLink: "https://www.herewallet.app",
    appStoreUrl: "https://apps.apple.com/app/here-wallet/id1627690576",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.herewallet.app",
    extensionUrl: "https://chromewebstore.google.com/detail/here-wallet/aaaomknclhhlcgfogemampkdcgjbhkdm",
    supportsCinacoinV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 27,
    description: "Mobile-first wallet for the NEAR Protocol.",
    developer: "HERE Wallet",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/HEREwallet" },
  },
  {
    id: "near-wallet",
    name: "NEAR Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/near",
    homepage: "https://wallet.near.org",
    supportedChainFamilies: ["near"],
    platforms: ["web"],
    supportsCinacoinV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 40,
    description: "Official NEAR Protocol web wallet.",
    developer: "NEAR Foundation",
    yearFounded: 2020,
    social: { twitter: "https://twitter.com/NEARProtocol" },
  },
  {
    id: "sender",
    name: "Sender Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/sender",
    homepage: "https://senderwallet.io",
    supportedChainFamilies: ["near", "evm"],
    supportedChains: ["eip155:1"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/sender-wallet/epapihdplmajcdmbkfedegpdgcgkdmfh",
    supportsCinacoinV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 25,
    description: "Multi-chain wallet for NEAR and EVM chains.",
    developer: "Sender Wallet",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/SenderWallet" },
  },
];
