export const socialEmbeddedWallets = [
  {
    id: "dynamic",
    name: "Dynamic",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/dynamic",
    homepage: "https://www.dynamic.xyz",
    supportedChainFamilies: ["evm", "solana", "aptos"],
    supportedChains: ["eip155:1", "eip155:137", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["web"],
    supportsCinacoinV2: true,
    walletType: "embedded",
    supportsAccountAbstraction: true,
    popularity: 36,
    description: "Embedded wallet SDK for seamless Web3 onboarding.",
    developer: "Dynamic",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/dynamic_xyz" },
  },
  {
    id: "privy",
    name: "Privy",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/privy",
    homepage: "https://www.privy.io",
    supportedChainFamilies: ["evm", "solana"],
    supportedChains: ["eip155:1", "eip155:137", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["web"],
    walletType: "embedded",
    supportsAccountAbstraction: true,
    popularity: 42,
    description: "Authentication and embedded wallet infrastructure for Web3 apps.",
    developer: "Privy",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/privy_io" },
  },
  {
    id: "web3auth",
    name: "Web3Auth",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/web3auth",
    homepage: "https://web3auth.io",
    supportedChainFamilies: ["evm", "solana"],
    supportedChains: ["eip155:1"],
    platforms: ["web"],
    walletType: "social",
    supportsAccountAbstraction: true,
    popularity: 44,
    description: "Decentralized authentication and key management platform.",
    developer: "Web3Auth",
    yearFounded: 2019,
    social: { twitter: "https://twitter.com/Web3Auth" },
  },
  {
    id: "particle-network",
    name: "Particle Network",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/particle",
    homepage: "https://particle.network",
    supportedChainFamilies: ["evm", "solana", "aptos", "sui", "ton"],
    supportedChains: ["eip155:1", "eip155:137"],
    platforms: ["web", "mobile"],
    walletType: "social",
    supportsAccountAbstraction: true,
    popularity: 33,
    description: "Chain abstraction platform with social login and wallet-as-a-service.",
    developer: "Particle Network",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/ParticleNtwrk" },
  },
  {
    id: "thirdweb",
    name: "Thirdweb In-App Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/thirdweb",
    homepage: "https://thirdweb.com",
    supportedChainFamilies: ["evm"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "eip155:8453"],
    platforms: ["web"],
    walletType: "embedded",
    supportsAccountAbstraction: true,
    popularity: 40,
    description: "Embedded wallets and Web3 infrastructure by thirdweb.",
    developer: "thirdweb",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/thirdweb_", github: "https://github.com/thirdweb-dev" },
  },
];
