export const solanaWallets = [
  {
    id: "sollet",
    name: "Sollet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/sollet",
    homepage: "https://www.sollet.io",
    supportedChainFamilies: ["solana"],
    supportedChains: ["solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["web"],
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 24,
    description: "One of the original Solana web wallets.",
    developer: "Project Serum",
    yearFounded: 2020,
  },
  {
    id: "solfire",
    name: "Solfire Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/solfire",
    homepage: "https://solfire.com",
    supportedChainFamilies: ["solana"],
    supportedChains: ["solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/solfire/abc",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 20,
    description: "Lightweight Solana browser extension wallet.",
    developer: "Solfire",
    yearFounded: 2022,
  },
  {
    id: "brave-wallet",
    name: "Brave Wallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/brave",
    homepage: "https://brave.com/wallet",
    supportedChainFamilies: ["evm", "solana"],
    supportedChains: ["eip155:1", "eip155:137", "eip155:42161", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"],
    platforms: ["browser_extension"],
    supportsWalletConnectV2: true,
    supportsEIP6963: true,
    rdns: "com.brave.wallet",
    openSource: true,
    walletType: "hot",
    popularity: 56,
    description: "Built-in multi-chain wallet in the Brave browser.",
    developer: "Brave Software",
    yearFounded: 2021,
    social: { twitter: "https://twitter.com/brave", github: "https://github.com/brave/brave-wallet" },
  },
];
