  // ═══════════════════════════════════════════════════════════
  // Starknet
  // ═══════════════════════════════════════════════════════════
  {
    id: "braavos",
    name: "Braavos",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/braavos",
    homepage: "https://braavos.app",
    supportedChainFamilies: ["starknet"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "braavos://",
    universalLink: "https://braavos.app",
    appStoreUrl: "https://apps.apple.com/app/braavos-smart-wallet/id6445956473",
    playStoreUrl: "https://play.google.com/store/apps/details?id=io.braavos.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/braavos/jnlgamecbpmbajjfhmmmlhejkemejdma",
    supportsCinacoinV2: true,
    openSource: true,
    walletType: "smart_contract",
    supportsAccountAbstraction: true,
    popularity: 44,
    description: "Leading Starknet wallet with hardware-grade security.",
    developer: "Braavos",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/BraavosWallet" },
  },
  {
    id: "argent-x",
    name: "Argent X",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/argentx",
    homepage: "https://www.argent.xyz/argent-x",
    supportedChainFamilies: ["starknet"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "argent://",
    universalLink: "https://www.argent.xyz",
    extensionUrl: "https://chromewebstore.google.com/detail/argent-x/dlcobpjiigpikoobohmabnhhmhfdnnii",
    supportsCinacoinV2: true,
    walletType: "smart_contract",
    supportsAccountAbstraction: true,
    popularity: 40,
    description: "Starknet wallet by Argent with social recovery.",
    developer: "Argent",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/argentHQ" },
  },
  // ═══════════════════════════════════════════════════════════
];
