export const tonWallets = [
  {
    id: "tonkeeper",
    name: "Tonkeeper",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tonkeeper",
    homepage: "https://tonkeeper.com",
    supportedChainFamilies: ["ton"],
    platforms: ["mobile", "browser_extension"],
    deepLink: "tonkeeper://",
    universalLink: "https://tonkeeper.com",
    appStoreUrl: "https://apps.apple.com/app/tonkeeper/id1455019088",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.ton_keeper",
    extensionUrl: "https://chromewebstore.google.com/detail/tonkeeper/nbdhibgjnjpnkajaghbffjbkcgljfgdi",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 55,
    description: "The leading TON blockchain wallet.",
    developer: "Tonkeeper",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/ton_keeper" },
  },
  {
    id: "tonhub",
    name: "Tonhub",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tonhub",
    homepage: "https://tonhub.com",
    supportedChainFamilies: ["ton"],
    platforms: ["mobile"],
    deepLink: "tonhub://",
    universalLink: "https://tonhub.com",
    appStoreUrl: "https://apps.apple.com/app/tonhub-wallet/id1605678378",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.parallax.tonhub",
    supportsWalletConnectV2: true,
    walletType: "hot",
    popularity: 35,
    description: "Secure TON wallet with DeFi integration.",
    developer: "Ton Foundation",
    yearFounded: 2022,
    social: { twitter: "https://twitter.com/tonhub_app" },
  },
  {
    id: "mytonwallet",
    name: "MyTonWallet",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/mytonwallet",
    homepage: "https://mytonwallet.io",
    supportedChainFamilies: ["ton"],
    platforms: ["browser_extension"],
    extensionUrl: "https://chromewebstore.google.com/detail/mytonwallet/nmepcmlhncfifkbgmmhfbkncjnbmncbj",
    supportsWalletConnectV2: true,
    openSource: true,
    walletType: "hot",
    popularity: 22,
];
