export const tronWallets = [
  {
    id: "tronlink",
    name: "TronLink",
    logo: "https://registry.walletconnect.com/api/v2/logo/md/tronlink",
    homepage: "https://www.tronlink.org",
    supportedChainFamilies: ["tron", "evm"],
    platforms: ["browser_extension", "mobile"],
    deepLink: "tronlink://",
    universalLink: "https://www.tronlink.org",
    appStoreUrl: "https://apps.apple.com/app/tronlink/id1439361739",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.tronlink.wallet",
    extensionUrl: "https://chromewebstore.google.com/detail/tronlink- wallet/ibnejdfjmmkpcnlpebklmnkoeoihofec",
    supportsCinacoinV2: true,
    walletType: "hot",
    popularity: 47,
    description: "Official Tron blockchain wallet.",
    developer: "TronLink",
    yearFounded: 2018,
    social: { twitter: "https://twitter.com/Tronlinkwallet" },
  },
];
