/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Cinacoin",
  "tagline": "Onchain Access, Simplified",
  "favicon": "img/logo.svg",
  "url": "https://cinacoin.com",
  "baseUrl": "/docs/",
  "trailingSlash": false,
  "organizationName": "cinagroup",
  "projectName": "cinacoin",
  "onBrokenLinks": "throw",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownLinks": "throw",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "headTags": [
    {
      "tagName": "meta",
      "attributes": {
        "name": "theme-color",
        "content": "#ffffff"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "color-scheme",
        "content": "light dark"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:type",
        "content": "website"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:site_name",
        "content": "Cinacoin Docs"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:title",
        "content": "Cinacoin — Onchain UX Toolkit Documentation"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:description",
        "content": "Self-hosted Wallet Connection Toolkit. Complete API reference, guides, and SDK documentation for building onchain applications."
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:url",
        "content": "https://cinacoin.com/docs/"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:image",
        "content": "https://cinacoin.com/docs/img/og-image.png"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:locale",
        "content": "en_US"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:site",
        "content": "@cinacoin"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:creator",
        "content": "@cinacoin"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:title",
        "content": "Cinacoin — Onchain UX Toolkit Documentation"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:description",
        "content": "Self-hosted Wallet Connection Toolkit. Complete API reference, guides, and SDK documentation."
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:image",
        "content": "https://cinacoin.com/docs/img/og-image.png"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "keywords",
        "content": "cinacoin, wallet, web3, blockchain, dapp, walletconnect, eip-6963, erc-4337, smart accounts, defi, sdk"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "author",
        "content": "Cinacoin Team"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "msapplication-TileColor",
        "content": "#171717"
      },
      "customElement": false
    },
    {
      "tagName": "link",
      "attributes": {
        "rel": "preconnect",
        "href": "https://fonts.googleapis.com"
      },
      "customElement": false
    },
    {
      "tagName": "link",
      "attributes": {
        "rel": "preconnect",
        "href": "https://fonts.gstatic.com",
        "crossorigin": "anonymous"
      },
      "customElement": false
    },
    {
      "tagName": "link",
      "attributes": {
        "rel": "stylesheet",
        "href": "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400&display=swap"
      },
      "customElement": false
    },
    {
      "tagName": "link",
      "attributes": {
        "rel": "dns-prefetch",
        "href": "https://github.com"
      },
      "customElement": false
    }
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/cinagroup/cinacoin/tree/main/docs-site/docs/",
          "routeBasePath": "/",
          "showLastUpdateTime": true
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5
        }
      }
    ]
  ],
  "plugins": [
    [
      "/home/cina/.openclaw/workspace/apps/docs-site/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "indexBlog": false,
        "docsRouteBasePath": "/",
        "searchResultLimits": 8,
        "searchResultContextMaxLength": 50,
        "explicitSearchResultPath": true,
        "searchBarShortcut": true,
        "searchBarShortcutHint": true,
        "indexPages": true,
        "language": [
          "en"
        ],
        "highlightSearchTermsOnTargetPage": true
      }
    ],
    [
      "@docusaurus/plugin-pwa",
      {
        "debug": false,
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "pwaHead": [
          {
            "tagName": "link",
            "attributes": {
              "rel": "icon",
              "href": "/docs/img/logo.svg"
            }
          },
          {
            "tagName": "link",
            "attributes": {
              "rel": "manifest",
              "href": "/docs/manifest.json"
            }
          },
          {
            "tagName": "meta",
            "attributes": {
              "name": "theme-color",
              "content": "#171717"
            }
          },
          {
            "tagName": "meta",
            "attributes": {
              "name": "apple-mobile-web-app-capable",
              "content": "yes"
            }
          },
          {
            "tagName": "meta",
            "attributes": {
              "name": "apple-mobile-web-app-status-bar-style",
              "content": "#171717"
            }
          },
          {
            "tagName": "link",
            "attributes": {
              "rel": "apple-touch-icon",
              "href": "/docs/img/logo.svg"
            }
          }
        ]
      }
    ]
  ],
  "themeConfig": {
    "image": "img/logo.svg",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "title": "Cinacoin",
      "logo": {
        "alt": "Cinacoin",
        "src": "img/logo.svg",
        "width": 24,
        "height": 24
      },
      "items": [
        {
          "href": "https://cinacoin.com",
          "label": "Home",
          "position": "left",
          "target": "_self"
        },
        {
          "type": "docSidebar",
          "sidebarId": "guideSidebar",
          "position": "left",
          "label": "Docs"
        },
        {
          "type": "docSidebar",
          "sidebarId": "apiSidebar",
          "position": "left",
          "label": "API"
        },
        {
          "href": "https://github.com/cinagroup/cinacoin",
          "label": "GitHub",
          "position": "right",
          "className": "navbar-github-link"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "Product",
          "items": [
            {
              "label": "Overview",
              "href": "https://cinacoin.com/products"
            },
            {
              "label": "Wallet",
              "href": "https://cinacoin.com/products#wallet"
            },
            {
              "label": "Exchange",
              "href": "https://cinacoin.com/products#exchange"
            },
            {
              "label": "Staking",
              "href": "https://cinacoin.com/products#staking"
            }
          ]
        },
        {
          "title": "Solutions",
          "items": [
            {
              "label": "Enterprise",
              "href": "https://cinacoin.com/solutions#enterprise"
            },
            {
              "label": "DeFi",
              "href": "https://cinacoin.com/solutions#defi"
            },
            {
              "label": "Payments",
              "href": "https://cinacoin.com/solutions#payments"
            }
          ]
        },
        {
          "title": "Developers",
          "items": [
            {
              "label": "Documentation",
              "to": "/"
            },
            {
              "label": "API Reference",
              "to": "/api/core-sdk"
            },
            {
              "label": "SDKs",
              "href": "https://github.com/cinagroup/cinacoin"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/cinagroup/cinacoin"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Blog",
              "href": "https://cinacoin.com/resources"
            },
            {
              "label": "Whitepaper",
              "href": "https://cinacoin.com/resources#whitepaper"
            },
            {
              "label": "Community",
              "href": "https://cinacoin.com/resources#community"
            },
            {
              "label": "Support",
              "href": "https://cinacoin.com/resources#support"
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "About",
              "href": "https://cinacoin.com/about"
            },
            {
              "label": "Careers",
              "href": "https://cinacoin.com/about#careers"
            },
            {
              "label": "Contact",
              "href": "https://cinacoin.com/about#contact"
            }
          ]
        }
      ],
      "copyright": "<div class=\"footer-newsletter\">\n  <h4>Stay Updated</h4>\n  <p>Get the latest news and updates</p>\n  <form class=\"footer-newsletter-form\" onsubmit=\"event.preventDefault()\">\n    <input type=\"email\" placeholder=\"Enter your email\" aria-label=\"Email for newsletter\" />\n    <button type=\"submit\">Subscribe</button>\n  </form>\n</div>\n<div class=\"footer-bottom-bar\">\n  <div class=\"footer-bottom-logo\">\n    <svg width=\"20\" height=\"20\" viewBox=\"0 0 32 32\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n      <rect width=\"32\" height=\"32\" rx=\"6\" fill=\"currentColor\"/>\n      <text x=\"16\" y=\"22\" font-family=\"Inter,system-ui,sans-serif\" font-size=\"18\" font-weight=\"600\" fill=\"var(--ifm-background-color)\" text-anchor=\"middle\">C</text>\n    </svg>\n    <span>CinaCoin</span>\n  </div>\n  <span class=\"footer-bottom-copyright\">&copy; 2026 CinaCoin. All rights reserved.</span>\n</div>"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": false
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false,
      "siteStorageNamespacing": false,
      "fasterByDefault": false,
      "mdx1CompatDisabledByDefault": false
    },
    "faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false,
      "gitEagerVcs": false
    },
    "experimental_vcs": {},
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
