/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "CinaCoin",
  "tagline": "Onchain access, simplified.",
  "favicon": "img/logo.svg",
  "url": "https://cinacoin.com",
  "baseUrl": "/",
  "trailingSlash": false,
  "organizationName": "cinagroup",
  "projectName": "cinacoin",
  "onBrokenLinks": "throw",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownLinks": "throw",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "headTags": [
    {
      "tagName": "meta",
      "attributes": {
        "name": "theme-color",
        "content": "#000000"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "color-scheme",
        "content": "light dark"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:type",
        "content": "website"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:site_name",
        "content": "CinaCoin Docs"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:title",
        "content": "CinaCoin — Onchain UX Toolkit Documentation"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:description",
        "content": "Self-hosted wallet connection toolkit. Complete API reference, guides, and SDK documentation for building onchain applications."
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:url",
        "content": "https://cinacoin.com/"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:image",
        "content": "https://cinacoin.com/img/og-image.png"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:locale",
        "content": "en_US"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:site",
        "content": "@cinacoin"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:creator",
        "content": "@cinacoin"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:title",
        "content": "CinaCoin — Onchain UX Toolkit Documentation"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:description",
        "content": "Self-hosted wallet connection toolkit. Complete API reference, guides, and SDK documentation."
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:image",
        "content": "https://cinacoin.com/img/og-image.png"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "keywords",
        "content": "cinacoin, coin, wallet, web3, blockchain, dapp, walletconnect, eip-6963, erc-4337, smart accounts, defi, sdk"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "author",
        "content": "CinaCoin Team"
      },
      "customElement": false
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "msapplication-TileColor",
        "content": "#000000"
      },
      "customElement": false
    },
    {
      "tagName": "link",
      "attributes": {
        "rel": "dns-prefetch",
        "href": "https://github.com"
      },
      "customElement": false
    }
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/cinagroup/cinacoin/tree/main/docs-site/docs/",
          "routeBasePath": "/",
          "showLastUpdateTime": true
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5
        }
      }
    ]
  ],
  "plugins": [
    [
      "/home/cina/.openclaw/workspace/node_modules/.pnpm/@easyops-cn+docusaurus-search-local@0.44.6_@docusaurus+theme-common@3.10.1_@docusaurus+plugin_r625qv4obwa6d6hqc2ffiv54m4/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "indexBlog": false,
        "docsRouteBasePath": "/",
        "searchResultLimits": 8,
        "searchResultContextMaxLength": 50,
        "explicitSearchResultPath": true,
        "searchBarShortcut": true,
        "searchBarShortcutHint": true,
        "indexPages": true,
        "language": [
          "en"
        ],
        "highlightSearchTermsOnTargetPage": true
      }
    ],
    [
      "@docusaurus/plugin-pwa",
      {
        "debug": false,
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "pwaHead": [
          {
            "tagName": "link",
            "attributes": {
              "rel": "icon",
              "href": "/img/logo.svg"
            }
          },
          {
            "tagName": "link",
            "attributes": {
              "rel": "manifest",
              "href": "/manifest.json"
            }
          },
          {
            "tagName": "meta",
            "attributes": {
              "name": "theme-color",
              "content": "#000000"
            }
          },
          {
            "tagName": "meta",
            "attributes": {
              "name": "apple-mobile-web-app-capable",
              "content": "yes"
            }
          },
          {
            "tagName": "meta",
            "attributes": {
              "name": "apple-mobile-web-app-status-bar-style",
              "content": "#000000"
            }
          },
          {
            "tagName": "link",
            "attributes": {
              "rel": "apple-touch-icon",
              "href": "/img/logo.svg"
            }
          }
        ]
      }
    ]
  ],
  "themeConfig": {
    "image": "img/logo.svg",
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "CinaCoin",
      "logo": {
        "alt": "CinaCoin",
        "src": "img/logo.svg",
        "width": 24,
        "height": 24
      },
      "items": [
        {
          "href": "https://cinacoin.com",
          "label": "Home",
          "position": "left",
          "target": "_self"
        },
        {
          "type": "docSidebar",
          "sidebarId": "guideSidebar",
          "position": "left",
          "label": "Docs"
        },
        {
          "type": "docSidebar",
          "sidebarId": "apiSidebar",
          "position": "left",
          "label": "API"
        },
        {
          "href": "https://github.com/cinagroup/cinacoin",
          "label": "GitHub",
          "position": "right",
          "className": "navbar-github-link"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Product",
          "items": [
            {
              "label": "Overview",
              "href": "https://cinacoin.com/products"
            },
            {
              "label": "Wallet",
              "href": "https://cinacoin.com/products#wallet"
            },
            {
              "label": "Exchange",
              "href": "https://cinacoin.com/products#exchange"
            },
            {
              "label": "Staking",
              "href": "https://cinacoin.com/products#staking"
            }
          ]
        },
        {
          "title": "Solutions",
          "items": [
            {
              "label": "Enterprise",
              "href": "https://cinacoin.com/solutions#enterprise"
            },
            {
              "label": "DeFi",
              "href": "https://cinacoin.com/solutions#defi"
            },
            {
              "label": "Payments",
              "href": "https://cinacoin.com/solutions#payments"
            }
          ]
        },
        {
          "title": "Developers",
          "items": [
            {
              "label": "Documentation",
              "to": "/"
            },
            {
              "label": "API Reference",
              "to": "/api/core-sdk"
            },
            {
              "label": "SDKs",
              "href": "https://github.com/cinagroup/cinacoin"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/cinagroup/cinacoin"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Blog",
              "href": "https://cinacoin.com/resources"
            },
            {
              "label": "Whitepaper",
              "href": "https://cinacoin.com/resources#whitepaper"
            },
            {
              "label": "Community",
              "href": "https://cinacoin.com/resources#community"
            },
            {
              "label": "Support",
              "href": "https://cinacoin.com/resources#support"
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "About",
              "href": "https://cinacoin.com/about"
            },
            {
              "label": "Careers",
              "href": "https://cinacoin.com/about#careers"
            },
            {
              "label": "Contact",
              "href": "https://cinacoin.com/about#contact"
            }
          ]
        }
      ],
      "copyright": "<div class=\"footer-newsletter\">\n  <h4>Stay Updated</h4>\n  <p>Get the latest news and updates</p>\n  <form class=\"footer-newsletter-form\" onsubmit=\"event.preventDefault()\">\n    <input type=\"email\" placeholder=\"Enter your email\" aria-label=\"Email for newsletter\" />\n    <button type=\"submit\">Subscribe</button>\n  </form>\n</div>\n<div class=\"footer-bottom-bar\">\n  <div class=\"footer-bottom-logo\">\n    <svg width=\"20\" height=\"20\" viewBox=\"0 0 32 32\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n      <rect width=\"32\" height=\"32\" rx=\"6\" fill=\"currentColor\"/>\n      <text x=\"16\" y=\"22\" font-family=\"Inter,system-ui,sans-serif\" font-size=\"18\" font-weight=\"600\" fill=\"var(--ifm-background-color)\" text-anchor=\"middle\">C</text>\n    </svg>\n    <span>CinaCoin</span>\n  </div>\n  <span class=\"footer-bottom-copyright\">&copy; 2026 CinaCoin. All rights reserved.</span>\n</div>"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#d6deeb",
          "backgroundColor": "#011627"
        },
        "styles": [
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(162, 191, 252)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgba(239, 83, 80, 0.56)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "inserted",
              "attr-name"
            ],
            "style": {
              "color": "rgb(173, 219, 103)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(99, 119, 119)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "url"
            ],
            "style": {
              "color": "rgb(173, 219, 103)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(214, 222, 235)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "selector",
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(255, 203, 139)"
            }
          },
          {
            "types": [
              "tag",
              "operator",
              "keyword"
            ],
            "style": {
              "color": "rgb(127, 219, 202)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "property"
            ],
            "style": {
              "color": "rgb(128, 203, 196)"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#d6deeb",
          "backgroundColor": "#011627"
        },
        "styles": [
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(162, 191, 252)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgba(239, 83, 80, 0.56)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "inserted",
              "attr-name"
            ],
            "style": {
              "color": "rgb(173, 219, 103)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(99, 119, 119)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "url"
            ],
            "style": {
              "color": "rgb(173, 219, 103)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(214, 222, 235)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "selector",
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(255, 203, 139)"
            }
          },
          {
            "types": [
              "tag",
              "operator",
              "keyword"
            ],
            "style": {
              "color": "rgb(127, 219, 202)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "property"
            ],
            "style": {
              "color": "rgb(128, 203, 196)"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "typescript",
        "javascript",
        "tsx"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": false
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false,
      "siteStorageNamespacing": false,
      "fasterByDefault": false,
      "mdx1CompatDisabledByDefault": false
    },
    "faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false,
      "gitEagerVcs": false
    },
    "experimental_vcs": {},
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
