workers_dev = true

name = "cinacoin-keys-server"
main = "cloudflare/worker.ts"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "keys.cinacoin.com", custom_domain = true }
]

[vars]
# Environment-specific configuration
KEYS_SERVICE_URL = "https://keys.cinacoin.com"

[[d1_databases]]
binding = "KEYS_DB"
database_name = "cinacoin-keys"

[[kv_namespaces]]
binding = "KEYS_CACHE"
id = "aabcbb80b702499bb508bd8114cc608d"

[dev]
ip = "localhost"
port = 8789
local_protocol = "http"
upstream_protocol = "https"