#!/usr/bin/env tsx
/**
 * Cinacoin Monorepo — Generate Changelog
 *
 * Generates a changelog from git history since the last tag,
 * grouped by commit type (feat, fix, chore, etc.).
 *
 * Usage:
 *   tsx scripts/generate-changelog.ts              # since last tag
 *   tsx scripts/generate-changelog.ts --from v1.0.0  # from specific ref
 *   tsx scripts/generate-changelog.ts --output CHANGELOG.md
 */

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const args = process.argv.slice(2);

function getArg(flag: string): string | undefined {
  const idx = args.indexOf(flag);
  return idx >= 0 ? args[idx + 1] : undefined;
}

const OUTPUT = getArg("--output");
const FROM_REF = getArg("--from");

// ── Determine range ─────────────────────────────────────────
let fromRef: string;
if (FROM_REF) {
  fromRef = FROM_REF;
} else {
  try {
    fromRef = execSync("git describe --tags --abbrev=0 HEAD^", {
      cwd: ROOT,
      encoding: "utf-8",
    }).trim();
  } catch {
    fromRef = execSync("git rev-list --max-parents=0 HEAD", {
      cwd: ROOT,
      encoding: "utf-8",
    }).trim();
  }
}

const toRef = "HEAD";
console.log(`Generating changelog: ${fromRef}..${toRef}`);

// ── Collect commits ─────────────────────────────────────────
const logFormat = "%H|%s|%an|%aI";
const raw = execSync(`git log ${fromRef}..${toRef} --pretty=format:"${logFormat}"`, {
  cwd: ROOT,
  encoding: "utf-8",
});

interface Commit {
  hash: string;
  subject: string;
  author: string;
  date: string;
  type: string;
  scope: string;
  description: string;
}

const commits: Commit[] = raw
  .split("\n")
  .filter(Boolean)
  .map((line) => {
    const [hash, subject, author, date] = line.split("|");
    const match = subject.match(/^(\w+)(?:\(([^)]+)\))?:\s*(.+)$/);
    return {
      hash: hash.slice(0, 7),
      subject,
      author,
      date,
      type: match?.[1] ?? "other",
      scope: match?.[2] ?? "",
      description: match?.[3] ?? subject,
    };
  });

// ── Group by type ───────────────────────────────────────────
const typeOrder = ["feat", "fix", "perf", "refactor", "docs", "test", "chore", "ci", "build", "other"];
const typeLabels: Record<string, string> = {
  feat: "🚀 Features",
  fix: "🐛 Bug Fixes",
  perf: "⚡ Performance",
  refactor: "♻️ Refactoring",
  docs: "📚 Documentation",
  test: "🧪 Tests",
  chore: "🔧 Chores",
  ci: "👷 CI/CD",
  build: "📦 Build",
  other: "📝 Other",
};

const grouped = new Map<string, Commit[]>();
for (const commit of commits) {
  const type = typeOrder.includes(commit.type) ? commit.type : "other";
  if (!grouped.has(type)) grouped.set(type, []);
  grouped.get(type)!.push(commit);
}

// ── Format output ───────────────────────────────────────────
const now = new Date().toISOString().slice(0, 10);
const lines: string[] = [];
lines.push(`# Changelog`);
lines.push(``);
lines.push(`## [Unreleased] — ${now}`);
lines.push(``);
lines.push(`Comparing: \`${fromRef}...${toRef}\``);
lines.push(``);

for (const type of typeOrder) {
  const group = grouped.get(type);
  if (!group || group.length === 0) continue;

  lines.push(`### ${typeLabels[type]}`);
  lines.push(``);

  // Sub-group by scope
  const byScope = new Map<string, Commit[]>();
  for (const c of group) {
    const scope = c.scope || "general";
    if (!byScope.has(scope)) byScope.set(scope, []);
    byScope.get(scope)!.push(c);
  }

  for (const [scope, scopeCommits] of byScope) {
    if (byScope.size > 1) {
      lines.push(`**${scope}**`);
    }
    for (const c of scopeCommits) {
      lines.push(`- ${c.description} (${c.hash})`);
    }
    if (byScope.size > 1) lines.push(``);
  }
  lines.push(``);
}

lines.push(`---`);
lines.push(`_Generated by \`scripts/generate-changelog.ts\`_`);

const output = lines.join("\n") + "\n";

if (OUTPUT) {
  writeFileSync(resolve(ROOT, OUTPUT), output);
  console.log(`✅ Changelog written to ${OUTPUT}`);
} else {
  console.log(output);
}
