import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        cc: {
          primary: 'var(--cc-primary)',
          onPrimary: 'var(--cc-on-primary)',
          ink: 'var(--cc-ink)',
          body: 'var(--cc-body)',
          muted: 'var(--cc-muted)',
          hairline: 'var(--cc-hairline)',
          'hairline-strong': 'var(--cc-hairline-strong)',
          canvas: 'var(--cc-canvas)',
          'canvas-soft': 'var(--cc-canvas-soft)',
          'canvas-soft-2': 'var(--cc-canvas-soft-2)',
          link: 'var(--cc-link)',
          'link-deep': 'var(--cc-link-deep)',
          'link-bg-soft': 'var(--cc-link-bg-soft)',
          success: 'var(--cc-success)',
          error: 'var(--cc-error)',
          'error-soft': 'var(--cc-error-soft)',
          'error-deep': 'var(--cc-error-deep)',
          warning: 'var(--cc-warning)',
          'warning-soft': 'var(--cc-warning-soft)',
          'warning-deep': 'var(--cc-warning-deep)',
          violet: 'var(--cc-violet)',
          'violet-soft': 'var(--cc-violet-soft)',
          'violet-deep': 'var(--cc-violet-deep)',
          cyan: 'var(--cc-cyan)',
          'cyan-soft': 'var(--cc-cyan-soft)',
          'cyan-deep': 'var(--cc-cyan-deep)',
          'highlight-pink': 'var(--cc-highlight-pink)',
          'highlight-magenta': 'var(--cc-highlight-magenta)',
          'selection-bg': 'var(--cc-selection-bg)',
          'selection-fg': 'var(--cc-selection-fg)',
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'monospace'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '48px', letterSpacing: '-2.4px', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-1.28px', fontWeight: '600' }],
        'display-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.96px', fontWeight: '600' }],
        'display-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.6px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md-strong': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', letterSpacing: '-0.28px', fontWeight: '400' }],
        'body-sm-strong': ['14px', { lineHeight: '20px', letterSpacing: '-0.28px', fontWeight: '500' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      borderRadius: {
        'cc-none': 'var(--cc-radius-none)',
        'cc-xs': 'var(--cc-radius-xs)',
        'cc-sm': 'var(--cc-radius-sm)',
        'cc-md': 'var(--cc-radius-md)',
        'cc-lg': 'var(--cc-radius-lg)',
        'cc-xl': 'var(--cc-radius-xl)',
        'cc-pill': 'var(--cc-radius-pill)',
        'cc-pill-sm': 'var(--cc-radius-pill-sm)',
        'cc-full': 'var(--cc-radius-full)',
      },
      boxShadow: {
        'cc-0': 'var(--cc-level0)',
        'cc-1': 'var(--cc-level1)',
        'cc-2': 'var(--cc-level2)',
        'cc-3': 'var(--cc-level3)',
        'cc-4': 'var(--cc-level4)',
        'cc-5': 'var(--cc-level5)',
      },
      spacing: {
        'cc-xxs': 'var(--cc-xxs)',
        'cc-xs': 'var(--cc-xs)',
        'cc-sm': 'var(--cc-sm)',
        'cc-md': 'var(--cc-md)',
        'cc-lg': 'var(--cc-lg)',
        'cc-xl': 'var(--cc-xl)',
        'cc-2xl': 'var(--cc-2xl)',
        'cc-3xl': 'var(--cc-3xl)',
        'cc-4xl': 'var(--cc-4xl)',
        'cc-5xl': 'var(--cc-5xl)',
        'cc-6xl': 'var(--cc-6xl)',
        'cc-section': 'var(--cc-section)',
      },
    },
  },
  plugins: [],
};

export default config;
