// Code generated by protoc-gen-go. DO NOT EDIT.
package icsdns

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryParamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryParamsRequest) Reset() { *x = QueryParamsRequest{} }
func (x *QueryParamsRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*QueryParamsRequest) ProtoMessage() {}
func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message { return nil }

type QueryParamsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Params        *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *QueryParamsResponse) Reset() { *x = QueryParamsResponse{} }
func (x *QueryParamsResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*QueryParamsResponse) ProtoMessage() {}
func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Params) Reset() { *x = Params{} }
func (x *Params) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Params) ProtoMessage() {}
func (x *Params) ProtoReflect() protoreflect.Message { return nil }

type MsgUpdateParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Authority     string  `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params        *Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *MsgUpdateParams) Reset() { *x = MsgUpdateParams{} }
func (x *MsgUpdateParams) String() string { return protoimpl.X.MessageStringOf(x) }
func (*MsgUpdateParams) ProtoMessage() {}
func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message { return nil }
func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}
func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgUpdateParamsResponse) Reset() { *x = MsgUpdateParamsResponse{} }
func (x *MsgUpdateParamsResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*MsgUpdateParamsResponse) ProtoMessage() {}
func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message { return nil }

var Query_ServiceDesc = struct {
	ServiceName string
	HandlerType interface{}
	Methods     []struct{ MethodName string }
}{
	ServiceName: "cina.icsdns.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []struct{ MethodName string }{
		{MethodName: "Params"},
	},
}

var Msg_ServiceDesc = struct {
	ServiceName string
	HandlerType interface{}
	Methods     []struct{ MethodName string }
}{
	ServiceName: "cina.icsdns.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []struct{ MethodName string }{
		{MethodName: "UpdateParams"},
	},
}

type QueryServer interface {
	Params(interface{}, *QueryParamsRequest) (*QueryParamsResponse, error)
}

type MsgServer interface {
	UpdateParams(interface{}, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

type QueryClient interface {
	Params(interface{}, *QueryParamsRequest, ...interface{}) (*QueryParamsResponse, error)
}

type MsgClient interface {
	UpdateParams(interface{}, *MsgUpdateParams, ...interface{}) (*MsgUpdateParamsResponse, error)
}
