workers_dev = true

name = "cinacoin-push-server"
main = "cloudflare/worker.ts"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "push.cinacoin.com", custom_domain = true }
]

[vars]
# Environment-specific configuration
PUSH_SERVICE_URL = "https://push.cinacoin.com"

[durable_objects]
bindings = [
  { name = "PushSubscription", class_name = "PushSubscription" }
]

[[kv_namespaces]]
binding = "PUSH_CACHE"
id = "10680718388843678a48f5f2ed045cc0"

[dev]
ip = "localhost"
port = 8788
local_protocol = "http"
upstream_protocol = "https"